### ISSUE TITLE
Allow Themes to feature Specified Background Image Files instead of Colors

### ISSUE THREAD

**Issue by ForeignExchangeZtudent** [aome510/spotify-player#105]
Honestly, everything about this is amazing.

The only thing I can request is being able to add background Images to themes to override background colors. It's the only thing really missing from this. (Either that or have an option to default to Terminal BG)

Thanks so much for working on this project!

**Comment by aome510** [comment]
hi @ForeignExchangeZtudent, thanks for the kind words. Hope u enjoy using `spotify-player`.

I don't think adding background image to override background color is possible. The app needs an allocated space to render the image. If that space is the whole application's window, the rendered image will hide the display text and other things.

I think what you want is a dim background image, which should be handled by your terminal. For example, in iterm2, you can set the terminal's background image by "Preferences > Profiles > Window > Background Image"

**Comment by ForeignExchangeZtudent** [comment]
Ah, that's unfortunate. I usually prefer themeing with Transparency in mind around my Terminal windows and considering the ease of themeing and switching themes. It just feels a bit less on the customizable side to not allow for transparency color code, at least if background-image is impossible.

But, eh it is whatever I guess.

**Comment by ForeignExchangeZtudent** [comment]
Figured this one out, as well. No need for any additions! (Not that it was possible due to working in RGB Space (256colors))

Thanks again for this project and keeping minimalist spotify alive in the best way possible.
