### ISSUE TITLE
Installing Image + Lyric_Finder Issues with Aur PKGBuild

### ISSUE THREAD

**Issue by ForeignExchangeZtudent** [aome510/spotify-player#106]
Tried to Install spotify-player with Image and Lyric_Finder unfortunately Image does not have Binaries and is just a library and should hence be listed as a dependencies rather than as a package.

Uncertain but it should be clarified that lyric_finder is the name and not lyric-finder as the github page states.

Uncertain what the PKGBuild would look like may need to wait for an update to list Image as a dependency in cargo.lock  assumedly as just adding to build():

cargo build --locked --release --features image, lyric_finder would work unless dependencies work differently

and package() adding: 

cargo install --features image, lyric_finder.

Did not work.

Anyways, I wait for an update that may fix these build issues. Cheers.

I tried installing with Cargo but it got messier as I couldn't specify the playback backend and had the same issues, as well. 

Also no clue if lyric_finder has the same problems as Image or not. Image is not a binary and has to be set as a [dependencies]. It would error out immediately.

Again, if you could show the modified PKGBUILD that would feature image and lyric_finder that would be appreciated unless there is an issue in the cargo.lock file as I suspect.

**Comment by aome510** [comment]
hi @ForeignExchangeZtudent, I don't have access to an arch machine nor have an experience dealing with this kind of issue, so I'm afraid I couldn't help.

Maybe @alosarjos (the package's AUR maintainer) can have a thought on this

**Comment by alosarjos** [comment]
Hmmm, if I'm understanding this correctly, the issue is that the AUR package is missing some optional features right?

Right now I'm packaging with the default settings. I have no issue updating the package to include more features by default on Arch, but I think that it's @aome510 who should decide what features are enabled by default when redistributing this proyect.

**Comment by alosarjos** [comment]
@ForeignExchangeZtudent If you want a modified PKGBUILD with those features included, it's pretty straighforward

```PKGBUILD
# Maintainer: Thang Pham <phamducthang1234 at gmail dot com>

pkgname=spotify-player
pkgver=0.10.0
pkgrel=1
pkgdesc="A command driven spotify player."
arch=('x86_64' 'aarch64' 'armv7h')
url="https://github.com/aome510/spotify-player"
license=('MIT')
depends=('alsa-lib' 'openssl')
makedepends=('cargo')
source=("${pkgname}-${pkgver}.tar.gz::https://github.com/aome510/spotify-player/archive/v${pkgver}.tar.gz")
sha512sums=('a8e93e20292863d5d172eb3ae095c22efa15ad3ccbcbb5fb11e1c6c4b86088662d758e283eac24e3c3e9378cbd457e8b085d0fb611e278e1030d5613fc27dd98')

build() {
    cd "${pkgname}-${pkgver}"

    cargo build --release --locked --features image,lyric_finder
}

package() {
    cd "${pkgname}-${pkgver}"

    install -Dm755 target/release/spotify_player -t "${pkgdir}/usr/bin"
    install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
}   
```

**Comment by aome510** [comment]
Yeah, I think the current set of default features should work for most people. If you want to build the app with additional features, you can always do it manually with `cargo install` (assuming that you have `cargo` installed on your machine):

```
cargo install spotify_player --features lyric-finder,image
```

> cargo install --features image, lyric_finder.
> Did not work.

I think it didn't work because you have an **extra space** between two features, so it tried to also install `image` package.

**Comment by ForeignExchangeZtudent** [comment]
Thanks guys, I figured it out you have to build:

cargo build --release --locked --features lyric-finder,image 

if you want both features through AUR. Anyways, resolved. Thanks again for the help, my apologies for not understanding cargo properly.

**Comment by alosarjos** [comment]
No problem. You can always build it locally and move the generated binary to where the AUR package installs it (`/usr/bin/spotify_player`)

You have some options to get it the way you want it. :+1:

**Comment by RainerZufahl** [comment]
Is there a way to verify image support has been properly installed? I'm running arch and used `yay --editfile -S spotify-player` to edit the PKGBUILD before building, adding the `--features image` part as described above. building went without apparent issues, on top of my existing installation. 

spotify-player is running inside a kitty window. I've verified that image support is working via `kitty +kitten icat "path/to/image"`. The player window shows no image: 
![image](https://user-images.githubusercontent.com/18621898/213432161-22b91732-2659-4238-982c-09aaf9fce7a7.png)
To make sure, i added the two lines `cover_image_width` and `cover_img_length` to my config as well, but it didnt help.

When running `yay -Qi spotify-player` the build date shows my last build time, and the packager is unknown as well, so i assume it was built on top of the last install successfully.

**Comment by RainerZufahl** [comment]
Ah, that did the trick. And I found the issue with my previous approach: since I didnt uninstall the player before reinstalling it with the new flag, i (obviously) have to cleanBuild the package, which i declined before. But now I tested it with cleanBuild and it worked just as well.

Thank you!

**Comment by slikie** [comment]
@aome510 `notify` seems to be pretty stable. please consider ship it by default or on arch

**Comment by aome510** [comment]
Imo, the default should be minimal and should only include features needed to make the app function like a music player. `notify` is definitely not one of them. Also, I think it's not too difficult to update the `PKGBUILD` by yourself to include any additional features.
