### ISSUE TITLE
MPRIS position/duration data not being exported properly(?)

### ISSUE THREAD

**Issue by apprehensions** [aome510/spotify-player#108]
**Describe the bug**
the MPRIS data for the duration of the song, and the position and the remaining is unknown.

**To Reproduce**
```
~ teapot$ playerctl metadata --format "{{ position }}"
62
~ teapot$ playerctl metadata --format "{{ position }}"
15
~ teapot$ playerctl metadata --format "{{ position }}"
110
~ teapot$ playerctl metadata --format "{{ position }}"
33
~ teapot$ playerctl metadata --format "{{ position }}"
85
~ teapot$ playerctl metadata --format "{{ position }}"
14
~ teapot$ playerctl metadata --format "{{ position }}"
80
~ teapot$ playerctl metadata --format "{{ duration(position) }}"
0:00
```

**Expected behavior**
Metadata about the duration and position is properly shown.

**Screenshots**
The most useless video ever:

https://user-images.githubusercontent.com/47404953/212978732-523d588a-e246-433d-8e91-2f440c4253d5.mp4

now, it may look like the wmusic dockapp is getting the 'information', but in reality it is guessing it.

**Environment**

- Application version: cc0fde5e9d7f5dd7dace9abe8cd9ea6fe563e7a5
- Application features: `alsa-backend,media-control`

**Comment by aome510** [comment]
Related: #99 

The incorrect "progress" metadata on Linux seems to be the result of these lines of codes: 
https://github.com/aome510/spotify-player/blob/cc0fde5e9d7f5dd7dace9abe8cd9ea6fe563e7a5/spotify_player/src/media_control.rs#L26-L39

Not sure if this can be really fixed. I'll need to do some experiments with my old ubuntu laptop, so it may take a while

**Comment by wael444** [comment]
yeah probably..

**Comment by apprehensions** [comment]
![image](https://user-images.githubusercontent.com/47404953/213629661-1fc9c9fd-a87c-4fae-b1f9-1c07101191ad.png)
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU, what a great song.
