### ISSUE TITLE
API for consume/dispatch actions from third-party applications

### ISSUE THREAD

**Issue by diegoulloao** [aome510/spotify-player#111]
**Is your feature request related to a problem? Please describe.**
Not a problem. is possible to dispose of a simple API to consume in order to dispatch actions from third-party applications, actions like:
- get current song title that's playing
- get the current playlist that's playing
- play a specific song of the current playlist
- go to next/previous song of the current playlist

**Describe the solution you'd like**
This would work sending commands to any existent instance of spotify-player running.
I would like to write a neovim plugin to control spotify-player while coding, as a widget of spotify-player for neovim, but it needs an API exposed.

E.g.
```bash
spotify_player --cmd="get-playlist"
spotify_player --cmd="play-song id"
```

I'm not sure if I can do this by using the service that spotify_player is using in background.
I don't know if that will get sync with spotify_player either (without hit an API for auth, etc)

I would like to get this idea working hand to hand with spotify-player, because I think is an app with a great future ahead.

Sounds crazy?

**Comment by aome510** [comment]
Hi @diegoulloao, thanks for creating this issue. Actually, I have a plan to create a similar one as I've got some related requests regarding external APIs to communicate with the app.

Related issues:
- https://github.com/aome510/spotify-player/issues/103

> Sounds crazy?

I thought about implementing the same thing before. I don't think it's impossible. I'll try and see xD.

**Comment by diegoulloao** [comment]
Yes, excellent. LMK if you try something, you can start with simple actions to test. In parallel I can start building the bases for the neovim/plugin widget if something comes out.
