### ISSUE TITLE
playback_progress_bar option is ignored

### ISSUE THREAD

**Issue by 0323pin** [aome510/spotify-player#120]
@aome510 Sorry to bother you again :(

**Describe the bug**
`playback_progress_bar` doesn't respect configuration options set by the user.

**To Reproduce**
Set the variable `playback_progress_bar` in `theme.toml` to anything but the default. Start the player and watch the default values being applied to the UI progress bar.

**Expected behavior**
The options in the config file should be honored.

**Log and backtrace**
Reference log, https://pastebin.com/4bn7Qcxx

**Screenshots**

![2023-02-05-093855_1366x768_scrot](https://user-images.githubusercontent.com/90570748/216809934-e6ff3e73-2b66-4f25-b7d0-d57970b40910.png)

![2023-02-05-094018_1366x768_scrot](https://user-images.githubusercontent.com/90570748/216809947-ecc33d07-c054-406a-aa24-d4f31d72529d.png)

The config file is shown in the screenshots but, if you want to look closer you can find it [here](https://codeberg.org/pin/netbsd/src/branch/master/.config/spotify-player/theme.toml)
Notice in the screenshots, that if I reverse `fg` and `bg` (screenshot 1 and 2) the UI looks exactly the same.

**Environment**

- OS: NetBSD
- Application version: 0.11.0
- Application features: portaudio

**EDIT**

Actually, it doesn't respect the defaults either. The `foreground` should be _Green_ on defaults but, it's _White_.

**Comment by 0323pin** [comment]
Reproduced on Void linux. Binary built with `cargo build --release --no-default-features --features alsa-backend`

v0.10.0
![v0 10 0](https://user-images.githubusercontent.com/90570748/216821905-94780883-4e8a-42ce-9e8f-d2e9ec5677dc.png)

v0.11.0
![v0 11 0](https://user-images.githubusercontent.com/90570748/216821936-b209071b-b26b-4479-b06d-218ff4864c34.png)

**Comment by aome510** [comment]
Hi pin, thanks for reporting. Should be fixed by #121. 

The bug was because of a typo in https://github.com/aome510/spotify-player/pull/121/commits/44a1a6f257fcfdf73765da6e293a63bf034f018d#diff-82d73b66336ce17de09822c7a042192a440ac81555460ae4b725e6b5d0cda3efL234.

**Comment by aome510** [comment]
If no bug is reported by eod, I can release a new minor version.

**Comment by 0323pin** [comment]
@aome510 Thanks! Just re-built from git-HEAD and it's fixed.

**Comment by aome510** [comment]
@0323pin released https://github.com/aome510/spotify-player/releases/tag/v0.11.1

**Comment by 0323pin** [comment]
@aome510 On my way to work right now, will update the package tonight. Thanks!

**Comment by 0323pin** [comment]
![2023-02-06-202906_1366x768_scrot](https://user-images.githubusercontent.com/90570748/217068862-471d8a5a-f022-41ff-9e32-cc50f13cad8d.png)

Updated and merged now.
