### ISSUE TITLE
feature request: notifications for tracks

### ISSUE THREAD

**Issue by justchokingaround** [aome510/spotify-player#123]
The official Spotify client (on linux) sends notifications when a new track is played, or when you reach the end of a song, and the next one starts playing. It would be great if this could be added to `spotify-player` :point_right: :point_left: 

Here's an example of how it looks like with the official client:
![image](https://user-images.githubusercontent.com/44473782/217357525-e0f62cbf-4d6f-42de-b8a4-76ffaee5c714.png)

**Comment by apprehensions** [comment]
this tbh

**Comment by aome510** [comment]
@justchokingaround @apprehensions implemented in https://github.com/aome510/spotify-player/pull/137.

You guys can test it out by running `cargo run --features notify`.

Also @apprehensions, I've implemented the first section in your #103

> download the current playing song's album cover into a file or into a cache for another script to use; my usecase for this is to display the album cover with an image viewer, as i missed this feature from playing music with mpv.

You can find the downloaded album covers in `$APP_CACHE_FOLDER/images`.

**Comment by justchokingaround** [comment]
it works really well, except one minor detail. when you select a song to play and then select another one a few seconds after that, it will display 2 notifications, which is different from the behavior of the official client, where the first song notification gets replaced by the second one. hopefully this screenshot helps you understand:
![image](https://user-images.githubusercontent.com/44473782/219707716-0bd93cb7-9c28-4884-a283-316edf1829c2.png)

**Comment by apprehensions** [comment]
that is because the notifications have completely seperate ids, if they had the same ids the notification daemon will automatically replace the previous if existing, i hope that can provide a solution

```
dunstify --replace=293 hi
```
for example

**Comment by aome510** [comment]
> it works really well, except one minor detail. when you select a song to play and then select another one a few seconds after that, it will display 2 notifications, which is different from the behavior of the official client, where the first song notification gets replaced by the second one. hopefully this screenshot helps you understand:

Yeah, you're right. It's because `spotify-player` creates new notification on each track change event. In theory, it can reuse the previous notification with an `update` function. I'm not too sure if that'll work well. Will try and get back to you later.

**Comment by aome510** [comment]
@justchokingaround, I did take a look. It's possible to implement updating functionality, but it is not trivial as it's only available in OSes with `xdg`. In other words, the implementation will involve some flag setup to avoid compilation failing in other OSes (`macos`, `windows`). I would avoid doing that if possible.

Hopefully, this is enough for now. I may go back to this in the future.
