### ISSUE TITLE
Shortcut to add to queue

### ISSUE THREAD

**Issue by bartlibert** [aome510/spotify-player#125]
I can add a track to the queue by using the "AddToQueue" action in the actions list, but I would like to be able to do this with a direct shortcut. So just pressing "Z" to add the selected track to the queue (or something similar)

**Comment by aome510** [comment]
Should be fixed with #130, which added AddSelectedItemToQueue command (default bind to `Z`)

**Comment by bartlibert** [comment]
Great, such fast work!
Due to some unforseen circumstances, I cannot test it immediately, but I look forward to it!
