### ISSUE TITLE
More navigation commands

### ISSUE THREAD

**Issue by bartlibert** [aome510/spotify-player#127]
I'd like to have some more navigation commands in the app

- PageDown/PageUp (by default mapped to CTRL-F and CTRL-B for example)
- Scroll to bottom/scroll to top (mapped to 'gg' and 'G' by default for example)
- "count" prefixes for j/k, so for example 10j will scroll 10 lines down.

**Comment by aome510** [comment]
> "count" prefixes for j/k, so for example 10j will scroll 10 lines down.

Adding other navigation commands should be a trivial change except this one =)). IMHO, it should be enough to navigate with a combination of page(up/down) (which can be implemented as moving up/down 10 rows) and (up/down) commands. Also, I tend to avoid complicating the handling code.

I did implement a similar thing for my other app (`hackernews-tui`) but it feels really hacky to me.

**Comment by bartlibert** [comment]
No problem. I'm a developer myself, so I understand wanting to keep code simple. Some combination of the other ones would indeed already cover almost all cases. (I'm just a vim freak I guess 😉)
