### ISSUE TITLE
customization of tui

### ISSUE THREAD

**Issue by apprehensions** [aome510/spotify-player#128]
Is it possible that the rust TUI libraries used by Spotify_player can move the current 'widgets'? I would love to remove the borders and move the progress bar at the bottom. And to disable certain text as it can get very cluttered.

Another thing is to change the text or icons to have a progress bar similar to musikcube.

Thanks.

**Comment by aome510** [comment]
By moving the widgets, do you mean re-ordering the app's layout? Removing borders can be easily added as a config option, layout re-ordering is not as trivial as a large part of UI constructing codes involves fixed layout. Flexible layout can be implemented but I don't have any plans to do it in the near future.

> Another thing is to change the text or icons to have a progress bar similar to musikcube.

`tui` only supports two types of progress bars `Gauge` and `LineGague`. `Gauge` is what we currently have in `spotify-player`. Changing to `LineGauge` will make it look as follows:

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/40011582/218323256-8c5fc35e-24fa-499c-8d88-a97497925c92.png">

which seems to be pretty close to that of musikcube.

**Comment by apprehensions** [comment]
> By moving the widgets, do you mean re-ordering the app's layout?

Yes.

> Flexible layout can be implemented but I don't have any plans to do it in the near future.
so, no progress bar at the bottom? :(

**Comment by aome510** [comment]
> so, no progress bar at the bottom? :(

:'( well technically, if all you need is to only move the playback block to the bottom, it should be easy to implement.

By playback block, I mean this whole thing
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/40011582/218323879-714cedae-15eb-401e-b65c-c8e07ddff51b.png">

**Comment by apprehensions** [comment]
yes thats what i mean, the whole playblock block thing thingy to be at the botom yes yes yes

**Comment by aome510** [comment]
@apprehensions you should now be able to move the playback window's position to the bottom by changing the `playback_position` config option to `Bottom`.

**Comment by apprehensions** [comment]
how do i use this `LineGague` thing though.

**Comment by aome510** [comment]
Oh, I missed. Will implement in a follow-up PR

**Comment by apprehensions** [comment]
thanks :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart:

**Comment by aome510** [comment]
updated TODO:
- [ ] gauge customization
- [ ] border customization

**Comment by apprehensions** [comment]
btw, is it possible that when the `LineGauge` support comes out, can the icon for `play` and `pause` be moved there just like in the format support?

**Comment by aome510** [comment]
> btw, is it possible that when the `LineGauge` support comes out, can the icon for `play` and `pause` be moved there just like in the format support?

do you mean moving it to be a part of the gauge? If yes, I'm afraid not. The play/pause icon is a part of `{track}` indicating the track's playing status. Because you cannot interact with the icon (e.g by clicking), it's not a part of the progress bar.
