### ISSUE TITLE
spotify-player via bash/CLI

### ISSUE THREAD

**Issue by lenlennart** [aome510/spotify-player#135]
**Is your feature request related to a problem? Please describe.**
I am looking for a substitution of my current setup using libspotify/mopidy.

**Describe the solution you'd like**
Control the spotify-player via bash.
Essentially, i would like to issue a bash command on my machine (providing Spotify URI or alike) which then starts steaming the music. I dont want to have to go over the tui.

**Describe alternatives you've considered**
hmm... no idea.

**Additional context**
< imagine a screenshot of an empty terminal window here >

**Comment by lenlennart** [comment]
if this is already possible, could you point me to an example/documentation?

**Comment by aome510** [comment]
I assume that you want a **headless** `spotify-player`. I don't really have any plans to do that as `spotify-player` is a TUI application. I think you may want to look into [spotifyd](https://github.com/Spotifyd/spotifyd).

**Comment by lenlennart** [comment]
ok thanks.
spotifyd (just as 99% of the forks of [librespot](https://github.com/librespot-org/librespot) ) requires a dedicated spotify client (eg mobile phone) to operate... so they do me no good.

**Comment by aome510** [comment]
No iirc, `spotifyd` itself is a client, so you don't need another one. From the project's README:

> Spotifyd streams music just like the official client, but is more lightweight and supports more platforms. Spotifyd also supports the Spotify Connect protocol, which makes it show up as a device that can be controlled from the official clients.

**Comment by lenlennart** [comment]
naah, spotifyd is only the deamon for playback. Most people seem to use spotify-tui to control it (which offered a nice clean CLI), but thats no longer maintaned. This is why i ended up on your repo in the first place :-)

But thanks anyway, much appreciation!

**Comment by lenlennart** [comment]
FYI - for anyone also interested: librespot-java offers an HTTP-Endpoints which can be served by curling:
https://github.com/librespot-org/librespot-java/tree/dev/api

**Comment by apprehensions** [comment]
i think a workaround is to *literally* spawn `spotify-player` into an empty shell, and have one of #103 (control and query spotify-player, and other devices) feature request.

however, you can simply use `spotifyd` and control it with `playerctl` :D

**Comment by cheyngoodman** [comment]
This appears to be related to https://github.com/aome510/spotify-player/issues/42 in terms of replacing other music daemons.

**Comment by aome510** [comment]
Yeah, I'm aware of this issue and the other one. Currently working on implementing daemon support.
