### ISSUE TITLE
[Windows] Every keypress is duplicated

### ISSUE THREAD

**Issue by scarlettekk** [aome510/spotify-player#136]
**Describe the bug**
On windows, every keypress is sent both on the press down, and on the key release. This makes the app near impossible to use as searches can't be made and only even rows can be selected

**To Reproduce**
`cargo install spotify_player` on Windows 11
`spotify_player.exe` (Issue occurs in both cmd.exe and powershell)
Navigate up and down, try searching, etc

**Expected behavior**
A key is sent to the app once per keypress.

**Log and backtrace**
Reference log and backtrace, which are usually located in `$HOME/.cache/spotify-player/`, of a run reproducing the bug.
'spotify-player-23-02-16-17' in the cache directory seems to be an empty file even after using the program

**Screenshots**
https://user-images.githubusercontent.com/42524580/219504557-0267b5c6-52ea-441b-b5d5-f29fc40ed41d.mp4

**Environment**

- OS: Windows 11 build 25295
- Application version: 0.11.1
- Application features: if applicable, provide [cargo features](https://doc.rust-lang.org/cargo/reference/features.html) used to build with `spotify-player`: Defaults (Installed with `cargo install spotify_player`

**Additional context**
Doesn't appear to happen on my Linux install.

**Comment by aome510** [comment]
Hi @scarlettekk, I don't have access to windows machine and I'm not too familiar with development on Win, so I couldn't really test/fix this issue. Hopefully, I can in the near future or someone can pick this up.

> 'spotify-player-23-02-16-17' in the cache directory seems to be an empty file even after using the program

Log file `spotify-player-*.log` should not empty. I wonder if this is because the app cannot interact with the OS properly.

**Comment by scarlettekk** [comment]
Can confirm issue is resolved

**Comment by aome510** [comment]
Thanks. This fix will be included in the upcoming release, which should be released soon!
