### ISSUE TITLE
No sound on gentoo/alsa

### ISSUE THREAD

**Issue by PetrifiedOak** [aome510/spotify-player#139]
**Describe the bug**
no sound with alsa-backend 

**To Reproduce**
1 use alsa
2 install with "cargo install spotify-player --git https://github.com/aome510/spotify-player --no-default-features --features alsa-backend"
3 no sound

**Expected behavior**
I can hear my music

**Log and backtrace**
        called Result::unwrap() on an Err value: StreamError(BuildStreamError(BackendSpecific { err: BackendSpecificError { description: "ALSA function 'snd_pcm_sw_params' failed with error 'EINVAL: Invalid argument'" } })),

**Screenshots**

**Environment**

- OS: Gentoo linux
- Application version: spotify-player 0.12.0
- Application features: --no-default-features --features alsa-backend

**Comment by 0323pin** [comment]
I've built `spotify-player` 0.12.0 on Void musl yesterday with `cargo build spotify-player --no-default-features --features alsa-backend` and everything is working fine.

I can check which `alsa` packages I have installed if that could help (on mobile right now).

**Comment by aome510** [comment]
@PetrifiedOak can you install/reinstall the `pulseaudio-alsa` package and try again? Context: https://github.com/aome510/spotify-player/issues/38#issuecomment-1136512745.

The `StreamError` error looks familiar, but it can be because of many things. Does using different audio backends work?

**Comment by PetrifiedOak** [comment]
> @PetrifiedOak can you install/reinstall the `pulseaudio-alsa` package and try again? Context: [#38 (comment)](https://github.com/aome510/spotify-player/issues/38#issuecomment-1136512745).
> 
> The `StreamError` error looks familiar, but it can be because of many things. Does using different audio backends work?

Pulseaudio-alsa? I cant find it in the gentoo repos.

**Comment by aome510** [comment]
Maybe https://wiki.gentoo.org/wiki/PulseAudio#No_sound could help

**Comment by PetrifiedOak** [comment]
> Maybe https://wiki.gentoo.org/wiki/PulseAudio#No_sound could help

I am using pure alsa, no pulseaudio/pipewire involved. Every other app works perfectly fine.

**Comment by aome510** [comment]
Hmm, I'm afraid that there is nothing else I could help. The error is from the third-party library (`librespot`) the `spotify-player` uses for streaming. I would suggest you try different [backends](https://github.com/aome510/spotify-player#audio-backend).

**Comment by aome510** [comment]
Close this issue for now as it's related to a third-party library and cannot be fixed within `spotify_player`.
