### ISSUE TITLE
Keybindings for playlist/songlist navigation

### ISSUE THREAD

**Issue by etlhsu** [aome510/spotify-player#140]
> Big fan of the project! Here's an idea I had :) 

**Is your feature request related to a problem? Please describe.**
Navigating large playlists can be somewhat cumbersome especially if they have 50+ songs. Support for `/` searching is really useful, but wish there were more methods for traversing playlists. 

**Describe the solution you'd like**
Including some vertical navigation keybindings would help allow for faster navigation. Not everyone is a Vim fan but I think a couple motions would be cool to have:
- `gg` and `G` to go to the start and end of a song list
- `:123` to go to a specific line item (ex. line 123)
- `Ctrl-u` and `Ctrl-d` to go up and down a playlist by a half-page (or simply a larger amount of songs)

**Comment by aome510** [comment]
> - `gg` and `G` to go to the start and end of a song list
> - `:123` to go to a specific line item (ex. line 123)
> - `Ctrl-u` and `Ctrl-d` to go up and down a playlist by a half-page (or simply a larger amount of songs)

Hi @etlhsu, are you using the latest version of `spotify-player` (`v0.12.0`)? If yes, the first and last items are already implemented. 

<img width="747" alt="Screen Shot 2023-02-20 at 9 16 32 PM" src="https://user-images.githubusercontent.com/40011582/220230626-575baded-8201-40ba-b66b-13f466ec0987.png">

as in https://github.com/aome510/spotify-player#commands. `:123` can also be helpful but with 1 and 3 should be enough most of the time.

**Comment by etlhsu** [comment]
Thanks for the callout, will leave this open for the feature request of `:123` but can close if this is unplanned.

**Comment by aome510** [comment]
Unfortunately, `:123` is unplanned, so let's close this issue for now. Feel free to reopen if you encounter any related issues.
