### ISSUE TITLE
no devices are seen

### ISSUE THREAD

**Issue by apprehensions** [aome510/spotify-player#142]
**Describe the bug**
title, cant explain it more

**To Reproduce**
+ play music on another device
+ shift+D
+ observe

**Expected behavior**
i can actually see devices, including #141 

**Log and backtrace**
none interesting

**Screenshots**

![image](https://user-images.githubusercontent.com/47404953/220661263-77c3aea7-d112-4d43-bb4b-c32ea6cc8178.png)

**Environment**

- Application version: 0.12.0
- Application features: `alsa-backend,media-control,notify`

**Additional context**
sorry for not being comprehensive

**Comment by aome510** [comment]
#142 and #141 should be resolved already with [spotify connect feature](https://github.com/aome510/spotify-player#spotify-connect). If u used `spotify-tui` previously, you should be familiar with the process of creating a Spotify app. Unlike `spotify-tui`, spotify only needs the client's ID, **not** your secret.

**Comment by apprehensions** [comment]
bru iom stupid

**Comment by apprehensions** [comment]
it would be nice if the spotify applications site tab thing was linked in the same area in the readme

**Comment by apprehensions** [comment]
https://developer.spotify.com/dashboard/applications i think its this

**Comment by scarlettekk** [comment]
Seeming to have an issue similar to this, but I have setup spotify connect with no help - the device is connected through my account, not my local network, and web client sees it but spotify_player can only see its own internal device
