### ISSUE TITLE
Failed to authenticate

### ISSUE THREAD

**Issue by Devinaut** [aome510/spotify-player#149]
**Describe the bug**
I try to authenticate with my Spotify username and password (as uncomfortable as that makes me), but authentication fails. I have a Premium Student account.

**To Reproduce**
Execute spotify-player, type username, then type password

**Expected behavior**
Authentication succeeds and I can finally listen to my music

**Log and backtrace**
Doesn't get far enough to generate a log

**Environment**

- OS: Void Linux x86_64 glibc
- Application version: latest commit
- Application features: built with `cargo build -r --target x86_64-unknown-linux-gnu -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort` and the following added to all `Cargo.toml` files:

```toml
[profile.release]
strip = true
lto = true
opt-level = 3
panic = "abort"
```

**Additional context**
I suspect my password having unusual characters, specifically a double-quote, may be causing this issue.

**Comment by apprehensions** [comment]
>  Premium Student

what is this?

**Comment by aome510** [comment]
I'm also on my premium student account right now. However, I've never failed to authenticate.

**Comment by Devinaut** [comment]
Username needs to be email; that fixes it.
