### ISSUE TITLE
cover_img none

### ISSUE THREAD

**Issue by 0323pin** [aome510/spotify-player#154]
Hi @aome510 

Not really an issue but, would it be possible to implement `cover_img` = `none` as a configuration option?
This would be great for people using the app without the `image` feature on, _e.g._ me :)

The logs get unnecessarily _"flooded"_  with `/image` .

Just a thought!
Regards

**Comment by aome510** [comment]
Yeah, it should be possible. I'll find a way to implement this as both `notify` and `image` features need to look images in `$APP_CACHE_FOLDER/images` folder.

**Comment by 0323pin** [comment]
Thanks!

**Comment by 0323pin** [comment]
@aome510 Didn't think it was necessary to start a new issue for this, maybe it's wrong.

Just in case you'd have missed it, https://github.com/tui-rs-revival/ratatui

**Comment by 0323pin** [comment]
Thank you ❤️
