### ISSUE TITLE
Unavailable tracks should be marked differently

### ISSUE THREAD

**Issue by Xevion** [aome510/spotify-player#158]
**Is your feature request related to a problem? Please describe.**
When a track is unavailable by spotify, it is not greyed out, marked and generally does not show any sort of error when one tries to play it. As it happens, my current top track is one such track.

**Describe the solution you'd like**
An error should display, the song should be greyed out or otherwise 'marked'. Worst case, it should not be displayed.

**Additional context**
![image](https://user-images.githubusercontent.com/44609630/224180312-59a82510-2e9d-4fb0-95ba-89f91d085a54.png)
The top track, _Lyfe Guitar Remix_ by _itsnot.theis_ is the unavailable track in question.

**Comment by rileyallyn** [comment]
Tried to take a crack at this in #207
