### ISSUE TITLE
Consistently document that command is `spotify_player`, not `spotify-player`

### ISSUE THREAD

**Issue by ahelwer** [aome510/spotify-player#161]
**Describe the bug**
After installation (via AUR) I expected to run `spotify-player`, but this resulted in `bash: spotify-player: command not found`. I thought this was an issue with the install script, because the README repeatedly mentions `spotify-player`. Someone in the AUR comments replied that actually the command is `spotify_player`, following rust naming conventions.

**To Reproduce**
Read the README and note that `spotify-player` is used in many places, and nowhere is it mentioned that the command is `spotify_player`.

**Expected behavior**
The text `spotify_player` should be used in the README instead of `spotify-player`, and the Commands section should start out by noting the command is called `spotify_player`.

**Log and backtrace**
N/A

**Screenshots**
N/A

**Environment**

- OS: Arch Linux
- Application version: Latest

**Additional context**
N/A

**Comment by aome510** [comment]
@ahelwer thanks for raising this. I've updated the documents to use `spotify_player`. I hope this can avoid confusion.
