### ISSUE TITLE
Way to like songs

### ISSUE THREAD

**Issue by emagaram** [aome510/spotify-player#163]
**Is your feature request related to a problem? Please describe.**
Frustrated when I can't like a song, have to open the GUI client.

**Describe the solution you'd like**
A keyboard shortcut maybe just 'L' to like the currently playing song or currently highlighted song.

**Comment by aome510** [comment]
The app does support liking a song. You can do it by running `ShowActionsOnCurrentTrack` command and then selecting `AddToLikedTracks` action. Reference: https://github.com/aome510/spotify-player#actions.

**Comment by aome510** [comment]
Close for now as the feature is already implemented. Feel free to re-open if u need anything related.

**Comment by jacksongoode** [comment]
This would be nice implemented as a global shortcut toggle!
