### ISSUE TITLE
playlist actions

### ISSUE THREAD

**Issue by apprehensions** [aome510/spotify-player#164]
to put it simply, since spotify-player has a `AddToPlaylist` command, which doesn't matter on the context, it would be nice to have playlist actions (`ShowACtionsOnCurrentPlaylist`) such as `RemoveFromPlaylist`, and incorperate #153 as `EnhancePlaylist`.

yes i want to remove a song from a playlist.

other playlist related actions include: `CreatePlaylist`

**Comment by aome510** [comment]
Related: https://github.com/aome510/spotify-player/issues/87

> yes i want to remove a song from a playlist.

Isn't `DeleteFromCurrentPlaylist` already a `TrackAction`?

> it would be nice to have playlist actions (ShowACtionsOnCurrentPlaylist) such as RemoveFromPlaylist, and incorperate https://github.com/aome510/spotify-player/issues/153 as EnhancePlaylist.

I can only see `EnhancePlaylist` is valid for `ShowACtionsOnCurrentPlaylist` which can be added as a separate command instead. `RemoveFromPlaylist` should be a track's action and is already implemented

**Comment by apprehensions** [comment]
> Isn't DeleteFromCurrentPlaylist already a TrackAction?

mfw i am so drowned with the help page i didnt find `ShowActionsOnSelectedItem`

**Comment by apprehensions** [comment]
there is no `CreatePlaylist`

**Comment by apprehensions** [comment]
and no `RefreshCurrentView` for when new playlists are created
