### ISSUE TITLE
Program won't start after exiting

### ISSUE THREAD

**Issue by Selmer443** [aome510/spotify-player#166]
**Describe the bug**
Hangs on startup after running spotify_player command

**To Reproduce**
Open spotify-player once on boot, after exiting, will not open again.

**Log and backtrace**
INFO spotify_player: No playback found on startup, trying to connect to an available device...

^^ last log, always hangs here

- OS: NixOS

Would appreciate some insight into this last log output, It always hangs here, thx

**Comment by apprehensions** [comment]
it might fail to initialize a gui, try doing `strace spotify_player` and see what you get

**Comment by Selmer443** [comment]
note for any other nixos users, I believe I have resolved this by removing lyric-finder, and image, from the build options in the nix package. These are enabled by default in the package right now that is maintained, I'm new to nixos, but I created my own package and omitted these two options. Hopefully someone else may glean some useful info from this issue, thank you for the strace recommendation

**Comment by apprehensions** [comment]
huh interesting lyric-finder makes it die

**Comment by aome510** [comment]
I think `image` might be the reason as it is initialized on startup. I couldn't test it tho as I don't have access to NixOS machine. 

Do you use kitty? If yes, I think it may be related to https://github.com/aome510/spotify-player/issues/148. Try to remove temp files in `/tmp/.tmp.viuer.*` and try again.

**Comment by aome510** [comment]
@Selmer443 did you still encounter this issue with `image` and `lyric_finder` using `v0.13.1`?

**Comment by aome510** [comment]
I would assume this is fixed for now.
