### ISSUE TITLE
dbus failure should concur to not attempt

### ISSUE THREAD

**Issue by apprehensions** [aome510/spotify-player#170]
**Log and backtrace**
```
Got a panic: PanicInfo {
    payload: Any { .. },
    message: Some(
        called `Result::unwrap()` on an `Err` value: SendError { .. },
    ),
    location: Location {
        file: "/home/sewn/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/souvlaki-0.6.0/src/platform/mpris/dbus.rs",
        line: 160,
        col: 53,
    },
    can_unwind: true,
}
```

After spotify-player realizes there is no dbus daemon running, it should instead simply stop sending requests when there isn't one available, instead of crashing immediately.

**Comment by aome510** [comment]
Looks like a third-party problem to me. It's kinda annoying sometimes when the third-party library doesn't implement error handling probably and use `unwrap` which results in panicking the whole program.

**Comment by apprehensions** [comment]
Hmm, so its either no dbus support or contact the repository? Damn

**Comment by aome510** [comment]
wdym by no dbus support? I thought the `dbus` still works fine. IIUC from the issue description, this issue seems to happen when the DBUS dies unexpected or something, which should happen rarely.

**Comment by apprehensions** [comment]
I had no dbus session. And spotify-player was built with the features that depend on Spotify, such as mpris and notify.

**Comment by aome510** [comment]
Wait, it used to work fine for you right? Like the `notify` and `media-control` feature. I'm not familiar with `dbus`, so I don't know how you have no dbus session.

**Comment by aome510** [comment]
FYI, `spotify_player` with `notify` and `media-control` still works for on my other Ubuntu machine.

**Comment by apprehensions** [comment]
> I had no dbus session.

One would revoke all possible starting sessions, a way to do this is to unset the DBUS environmental variables.

**Comment by Sinono3** [comment]
This was just fixed in the latest version of Souvlaki. If dbus was not detected when attaching the media controls, it will return an error.

**Comment by apprehensions** [comment]
yay htanks
