### ISSUE TITLE
How does spotify-player store the password?

### ISSUE THREAD

**Issue by apprehensions** [aome510/spotify-player#176]
From the looks of it, `~/.cache/credentials.json:auth_data` contain a base64 string, how does it handle this? I'm asking this for a friend (discordo maintainer)

**Comment by apprehensions** [comment]
```rust
    #[serde(alias = "encoded_auth_blob")]
    #[serde(serialize_with = "serialize_base64")]
    #[serde(deserialize_with = "deserialize_base64")]
    pub auth_data: Vec<u8>,
}

```

**Comment by aome510** [comment]
It is stored using _authentication blob_. More details: https://github.com/librespot-org/librespot/blob/dev/docs/authentication.md#zeroconf-based-authentication. I'm not too familiar with the scheme tho, if you want a more in-depth explanation, I would recommend reaching out the `librespot` library's maintainer.

**Comment by apprehensions** [comment]
aigh

**Comment by apprehensions** [comment]
t
