### ISSUE TITLE
Very long podcast/ song causes no audio

### ISSUE THREAD

**Issue by IanQS** [aome510/spotify-player#180]
**Describe the bug**

- So I've got a few songs in my "work" playlist that are about 8 hours each. When I try to play one of those songs, nothing happens; when I then try something more reasonable, like a song that's 5 minutes (or even up to 10 minutes, possibly longer, but I haven't tried), things work fine, and I can hear audio.

**To Reproduce**

- Try to play some songs from [spotify playlist](https://open.spotify.com/playlist/7q0ExSkUozKiW1FQI0DfMo?si=f3182aa1f6504b2f)

**Expected behavior**

- Songs to play and have audio

**Log and backtrace**

- [spotify-player-23-04-07-18-54.log](https://github.com/aome510/spotify-player/files/11182315/spotify-player-23-04-07-18-54.log)

- The backtrace is just an empty file

**Environment**

- OS: MacOS
- Application version: 0.13.1
- Application features: Default installation

**Comment by aome510** [comment]
The "songs" you link in the issue are in the form of a podcast. `spotify-player` doesn't support podcasts, so there is no audio.

Related: #77 (podcast support)

**Comment by IanQS** [comment]
Ahh crap, sorry! I didn't realize that podcasts weren't supported. I just assumed they would all be processed as audio files. 

Thank you! I suppose I will have to find a workaround
