### ISSUE TITLE
On macOS automatically switch to new default sound output

### ISSUE THREAD

**Issue by yerke** [aome510/spotify-player#183]
**Is your feature request related to a problem? Please describe.**
When I connect my Bluetooth headphones I expect spotify-player to switch to them automatically.

**Describe the solution you'd like**
When I connect my Bluetooth headphones I expect spotify-player to switch to them automatically.

**Describe alternatives you've considered**
Keep existing behavior. Right now I have to close spotify-player and open it again after connecting to BT headphones (old way). Another way would be to use `RestartIntegratedClient`, which I just discovered.

**Additional context**
Once again, thanks for the spotify-player!

**Comment by aome510** [comment]
`RestartIntegratedClient` is one way that I usually use when connecting to a new bluetooth device. The command doesn't work sometimes in the first try (maybe because it takes time to retrieve the newly connected bluetooth) and I need to re-run the command. 

I don't know if it's possible to listen to new bluetooth device event and implement the automatically switching logic. Will take a look.

**Comment by Foxtrod89** [comment]
I didn't even expect this project to support wireless devices lol. 
Seems like `device_type = "wireless"` doesn't do anything.

**Comment by aome510** [comment]
> I didn't even expect this project to support wireless devices lol.

Not sure what you mean by supporting wireless devices. `device_type` only changes how the client is displayed in the official application. A list of options for `device_type` can be found in https://github.com/librespot-org/librespot/wiki/Options

<img width="314" alt="Screenshot 2023-05-14 at 10 55 02 PM" src="https://github.com/aome510/spotify-player/assets/40011582/f97c97f8-b15b-41d7-bffa-dc769bdb5a48">

**Comment by Foxtrod89** [comment]
> > I didn't even expect this project to support wireless devices lol.
> 
> Not sure what you mean by supporting wireless devices. `device_type` only changes how the client is displayed in the official application. A list of options for `device_type` can be found in https://github.com/librespot-org/librespot/wiki/Options
> 
> <img alt="Screenshot 2023-05-14 at 10 55 02 PM" width="314" src="https://user-images.githubusercontent.com/40011582/238232029-f97c97f8-b15b-41d7-bffa-dc769bdb5a48.png">
How to setup wireless connection?

**Comment by aome510** [comment]
I'll assume you mean hearing sound from a wireless device (bluetooth headphone). If you install the app with `streaming` feature, it should use the default output device on startup (in this case the bluetooth headphone), so no need to setup anything.

**Comment by Spuxy** [comment]
Yep the problem what u got is, that u don't have probably connected properly wireless hw to your Mac or u don't have Spotify daemon or u don't have opened Spotify (the official one) + Spotify_player. 

I got m1 with the newest OS and everything works correctly.

`brew info spotifyd`
`brew services list | grep spotifyd`

this should indicates if there is even chance to connect into spotify

**Comment by nazriel** [comment]
@aome510 from what I've gathered this is the issue with audio backends.

Spotifyd folks mention librespot as being the issue.
Librespot folks mention RustAudio/rodio as source of the problem: 
https://github.com/librespot-org/librespot/issues/547

I wonder if we could implement some workaround - detecting if default output device changes and automatically restarting streaming service (RestartIntegratedClient) - or if it is worth in the first place.

**Comment by aome510** [comment]
This seems to be handled automatically now with new `librespot v0.5.0` release
