### ISSUE TITLE
Extend CLI Functionality

### ISSUE THREAD

**Issue by cheyngoodman** [aome510/spotify-player#184]
**Is your feature request related to a problem? Please describe.**
I'm unable to use some Spotify features without interacting with a UI.

**Describe the solution you'd like**
I'd like to use CLI commands or bound keybinds to interact with `spotify_player` features.

The recent pull request [!159](https://github.com/aome510/spotify-player/pull/159) provided some CLI commands. 

Can we expand this CLI functionality to include these features?:

- ~~Play a specific playlist or song URL: `spotify_player playback play --url=<playlist|song>`~~
- Play liked songs: `spotify_player playback start --liked`
- Control like setting for current song:
  - Like the now playing song: `spotify_player playback like`
  - Unlike the now playing song: `spotify_player playback like --unlike`
  - Toggle like/unlike on the now playing song: `spotify_player playback like --toggle`
- Increase or decrease the current volume by an increment:
  - Increase volume: `spotify_player playback volume +5`
  - Decrease volume: `spotify_player playback volume -5`

**Describe alternatives you've considered**
I've tried `spt` from https://github.com/Rigellute/spotify-tui which now appears abandoned and missing some features. `playerctl` does not have these features. I'm unsure of another CLI utility that gives access to these functions.

**Additional context**
Combined with a daemon functionality mentioned in https://github.com/aome510/spotify-player/issues/42 & https://github.com/aome510/spotify-player/issues/135, these commands can help add window manager integration and GUI-less use of Spotify.

~~Unrelated, I've tried to build the latest change and test the `spotify_player playback` command but I'm getting `error: unexpected argument 'playback' found`. If possible, I'd like to help extend the `playback` subcommand but I'm new to rust and running into issues accessing the `playback` command.~~

Thanks for your work on `spotify-player`, I appreciate the product and your support.

**Comment by aome510** [comment]
> Unrelated, I've tried to build the latest change and test the spotify_player playback command but I'm getting error: unexpected argument 'playback' found. If possible, I'd like to help extend the playback subcommand but I'm new to rust and running into issues accessing the playback command.

Based on the error, I'm assuming you ran `cargo build` then `spotify_player playback ...`. `cargo build` builds a binary in the `target/debug/` folder. So instead, you should run `./target/debug/spotify_player playback ...`. You can also use `cargo run` which is the command combining building and running the application:
```
cargo run -- playback ...
```

**Note**: `cargo run|build` runs/builds the application in debug mode so the performance may not be good. You can run/build the app in a release mode for better performance (with slower build time):
```
cargo run --release -- playback ...
```
