### ISSUE TITLE
External applications dont register(?)

### ISSUE THREAD

**Issue by apprehensions** [aome510/spotify-player#185]
I'm not sure if this is related with Librespot; trying anyway.

I have a last.fm account that is connected to my apotify account, which tracks the music I play and is able to play. However if I play a song under spotify-player it does not register on last.fm, I hadn't noticed this for a LONG time and seems many scrobbles were wasted. For example it won't scrobble a song when I listen to it on Spotify-player, but would if I'm using the proprietary clients. I should probay try out spotifyd.

**Comment by aome510** [comment]
This is a well-known issue of librespot: https://github.com/librespot-org/librespot/issues/913. Hopefully, it will be fixed with their new APIs. `spotifyd` also uses librespot under hood so I don't think it helps.

**Comment by apprehensions** [comment]
arg

**Comment by aome510** [comment]
Close this issue for now as it's related to a third-party library and cannot be fixed within `spotify_player`.

**Comment by apprehensions** [comment]
Because of this, I have to stop using this project unfortunately, cause I need lastfm registration...

**Comment by aome510** [comment]
That’s unfortunate ;(.
