### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by flexwie** [aome510/spotify-player#189]
**Is your feature request related to a problem? Please describe.**
Using cargo to install the player is the easiest way for Mac users, but still requires to have the rust toolchain installed on the machine. 

**Describe the solution you'd like**
Many if not most applications for Mac can be installed with Homebrew. It would be nice to have a formula to do so.

**Describe alternatives you've considered**
I guess a simple bash script that grabs the binaries from the releases would work as well, but its less elegant and won't support updating and uninstalling.

**Comment by aome510** [comment]
I don't have any experience dealing with `homebrew` before. Any help on this will be greatly appreciated.

**Comment by flexwie** [comment]
I don't have any experience either so far, but I would be open to trying it out!

**Comment by tresni** [comment]
I did this 3 weeks ago 😁  https://github.com/Homebrew/homebrew-core/pull/128997

**Comment by flexwie** [comment]
Looks great! One thing I'd love to have is the ability to choose between the different features instead of installing them all. Maybe that could be done with [options](https://docs.brew.sh/Formula-Cookbook#adding-optional-steps)?

**Comment by tresni** [comment]
That is possible. At one point I know it was being discouraged to have options in `homebrew-core` and instead to do that in a separate tap (similar to the ffmpeg example they give in the documentation.) I don't know if that's still the case, I'll do some grepping through the core formulas and see.

**Comment by aome510** [comment]
> https://github.com/Homebrew/homebrew-core/pull/128997/files#diff-9de770de980848d0bc612b5e6cb4910f1da3e81348b2dafbc877303fe477787dR21

IMO, it's better to install the application with default features. Not all non-default features work well without setting up or further configurations.

**Comment by aome510** [comment]
Also thanks for the PR in the core repo, look forward to seeing it getting merged.

**Comment by tresni** [comment]
Okay,  confirming that you are not allowed to use options in homebrew/core:

```
  * 8: col 3: Formulae in homebrew/core should not use `option`.
  * 26: col 27: Formulae in homebrew/core should not use `build.with?`.
  * 27: col 27: Formulae in homebrew/core should not use `build.with?`.
  * 28: col 34: Formulae in homebrew/core should not use `build.with?`.
  * 29: col 29: Formulae in homebrew/core should not use `build.with?`.
```

Using the [ffmpeg formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ffmpeg.rb) as a guide, it would appear that enabling some optional features would generally be the recommendation.  I would suggest that we leave the formula as is unless I'm missing something and there are cases where enabling `images,lyric-finder,notify`  could actually cause the application to not work. In my (all be it) limited testing, I didn't find any issues with having them enabled if the underlying system didn't support the feature (e.g. running in Terminal vs iTerm with `images` just lead to block display, I haven't found a way to make `lyric-finder` not work, etc)

**Comment by aome510** [comment]
One case that `lyric-finder` doesn't work: https://github.com/aome510/spotify-player/issues/155. And `image` doesn't display a "nice-looking" image unless you use `kitty` or `iTerm2`. `notify` can be quite annoying if you don't really need one.

For me, I didn't find any problems with `image` and `lyric-finder` as my two additional features. 

My point is that not all people need the features listed above and sometimes they may not work as expected. Using the default features provide a good and comfortable baseline. Users can always install the app with more features enabled if they want.

That said, the PR is still yours so feel free to leave as-is if that's what you think the best.

**Comment by aome510** [comment]
Close this as https://github.com/Homebrew/homebrew-core/pull/128997 has been merged.
