### ISSUE TITLE
Not building?

### ISSUE THREAD

**Issue by hernangonzalez** [aome510/spotify-player#195]
**Describe the bug**
`cargo install` fails with the following message
> 108  |                 self.spotify.seek_track(position_ms, device_id).await?
     |                              ---------- ^^^^^^^^^^^ expected `Duration`, found `u32`
     |                              |
     |                              arguments to this method are incorrect
     |

**To Reproduce**
Just run cargo install, build will fail.

**Environment**

- OS: MacOS
- Application version: N/A
- Application features: if applicable, provide [cargo features](https://doc.rust-lang.org/cargo/reference/features.html) used to build `spotify_player`

**Additional context**
`rustc 1.69.0 (84c898d65 2023-04-16)`

**Comment by aome510** [comment]
Will close this issue for now as I assume `--locked` should fix it. Feel free to re-open if the issue still persists.
