### ISSUE TITLE
shortcuts for moving items in a playlist? 

### ISSUE THREAD

**Issue by deltahoch3** [aome510/spotify-player#197]
first of all, epic work! really love it, it only takes 40-55mb ram, i have image & notify enabled, orig. spotify uses up to 800mb, sometimes even more ... crazy

i would wish me a feature, i'm change the order of my songs quite alot (at least at the beginning), would  it be possible to move the songs around?
something like:
"ctrl-arrowUp" & "ctrl-arrowDown" or with shift? or dwm-style with "j" & "k" or whatever makes sense to you ;)

thanks for all the work which went into this project, as soon as i get my pay, i'll sent you a coffee ;)

cheers
hardy

**Comment by deltahoch3** [comment]
maybe you should setup a "buy me a coffee", i'm sure, you made a few people quite happy ;)

**Comment by aome510** [comment]
Hi @deltahoch3, thank you for the kind words and great to hear that you like this project. 

Regarding "buy me a coffee", I don't really need one lol. I only work on this project whenever I feel like I want to. I would prefer contributions instead xD as I couldn't work on all the requested features.
