### ISSUE TITLE
Search in playlist has some difficulties

### ISSUE THREAD

**Issue by Icelk** [aome510/spotify-player#203]
**Describe the bug**
When you search in a playlist (to e.g. cue songs), the filtered list of songs don't persist.

**To Reproduce**
Search in a playlist.

**Expected behavior**
When searching, Enter should return the focus to the playlist instead of playing the hovered song. To clear the search, press `/` again and remove the search text.

**Environment**

- OS: Arch
- Application version: 0.14.0
- Application features: `-F notify,image,lyric-finder,pulseaudio-backend,streaming,media-control --no-default-features`

Thanks for the awesome app!

**Comment by aome510** [comment]
This is **intended behavior**. Personally, I don't like the idea of *"enter should return the focus to the playlist ... press / again and remove the search text"*. 

The search popup only captures character inputs, so you can still use `up`, `down`, `ctrl-{char}`, etc to select filtered items in the playlist.

**Comment by Icelk** [comment]
I noticed that too. How do you recommend doing things when wanting to queue multiple songs with the same search term? Because after entering the song's context menu, the search is reset.

**Comment by aome510** [comment]
>  Because after entering the song's context menu, the search is reset.

For add to queue, there is a command to do that: `AddSelectedItemToQueue`, so you don't need to go through the track menu. The command is binded by default to `Z`, which doesn't work well with search, so you'll need to bind a different key to the command. For example,

```toml
[[keymaps]]
command = "AddSelectedItemToQueue"
key_sequence = "C-z" 
```

Then you can use `ctrl-z` to add an item to queue while keeping the search popup open.
