### ISSUE TITLE
Attempting to play blocked song prevents resuming current displayed song

### ISSUE THREAD

**Issue by Xevion** [aome510/spotify-player#211]
**Describe the bug**
If you attempt to play a blocked song (it's grayed out in the official Spotify interfaces), it won't play. It won't update the interface, it will simply stop whatever you're playing currently. However, the progress bar may continue.

**To Reproduce**
1. Play a blocked song while another song is 'active' (playing or not).
2. Attempt to unpause and continue the current song.

**Expected behavior**
The current song should resume no matter what song was attempted prior. Better, the interface should update and shown that no song is currently playing.

**Log and backtrace**
[spotify-player-23-06-23-16:02.log](https://gist.github.com/Xevion/018b472969251b5b8088f09b76dfbb10)

**Screenshots**
![image](https://github.com/aome510/spotify-player/assets/44609630/9626effe-aeaa-4553-9e9f-4be3902ae198)
I attempted to play 'Bookbag' but the interface remains unchanged. Also not shown in the screenshot is the progress bar progressing normally, despite nothing playing.

**Environment**

- OS: Pop!_OS 22.04 LTS
- Application version: 0.12.1

**Comment by aome510** [comment]
Related: https://github.com/aome510/spotify-player/issues/158. Look like this issue should also be fixed with https://github.com/aome510/spotify-player/pull/207. 

@rileyallyn do you have any updates on the PR or do you have any helps with that?

**Comment by aome510** [comment]
Ideally, unavailable/blocked/unplayable songs should be filtered out from the UI, so such confusion should not happen.
