### ISSUE TITLE
Add Flathub/Flatpak method of installation

### ISSUE THREAD

**Issue by emanuelserpa** [aome510/spotify-player#213]
It may sound like a strange request, but ncspot [already has a package on Flathub](https://flathub.org/apps/io.github.hrkfdn.ncspot), and it is a good way for installing it in immutable distros like openSUSE MicroOS and Fedora Silverblue.

**Comment by aome510** [comment]
Hi, I don't maintain the installation packages, but hopefully someone can take a look and add one.

**Comment by emanuelserpa** [comment]
@aome510 
I'm doing a Flatpak myself and while I still can't make it work (it runs, but it still breaks somehow).

What about an icon? I did this https://files.catbox.moe/wfhy7i.svg

**Comment by aome510** [comment]
> I still can't make it work (it runs, but it still breaks somehow).

Can you elaborate how it breaks?

> What about an icon? I did this https://files.catbox.moe/wfhy7i.svg

Looks good. ty

**Comment by apprehensions** [comment]
Why make a Flatpak for a TUI application?

**Comment by aome510** [comment]
Close this issue as the project doesn't provide support for maintaining build file for installing from external package managers. Feel free to make a PR to update the README if the support is added.
