### ISSUE TITLE
Add command to copy to clipboard a link to the song in Spotify

### ISSUE THREAD

**Issue by aromeronavia** [aome510/spotify-player#214]
**Is your feature request related to a problem? Please describe.**
I want to share a song with my friends but I'm unable to.

**Describe the solution you'd like**
A key shortcut when a song is "active" and I press a key, it binds the song URL into my clipboard

**Describe alternatives you've considered**
Nothing comes to mind but opening the actual spotify UI

**Additional context**
Nothing to share at the moment. Happy to help implementing this @aome510 🚀

**Comment by aome510** [comment]
`spotify_player` already supports this feature. You can call `ShowActionsOnCurrentTrack` (binded to `a`) and then select `CopyTrackLink` action  (binded to `5`)

**Comment by aromeronavia** [comment]
Ohhhh my bad then! I looked up for it in the codebase but didn't find it an assumed it didn't exist. We can safely close this one then!

Thank you @aome510!
