### ISSUE TITLE
Long delay when playing from very large liked tracks playlist

### ISSUE THREAD

**Issue by alexseitsinger** [aome510/spotify-player#215]
Sadly, I still have to report a delay when trying to play from this list. How about reducing the number from 200 down to something like 32 or 64? (My 1680x1024 display shows 32 songs when maximized).            

#78

**Comment by aome510** [comment]
I can make this variable configurable.

**Comment by alexseitsinger** [comment]
That's wonderful news, my fiend. Thanks again.

**Comment by aome510** [comment]
Should be configurable now with `tracks_playback_limit`. It is 50 by default so you may not need to configure.
