### ISSUE TITLE
Prepare for `v0.5.0` release

### ISSUE THREAD

**Issue by aome510** [aome510/spotify-player#22]
`spotify-player` has changed [a lot](https://github.com/aome510/spotify-player/compare/v0.1.0...master) since the version `v0.1.0`.

As the application has gradually become quite usable, `v0.5.0` is going to be the release to be announced on public forums such as HN and Reddit. 

To prepare for this release, things probably need to do:

- [x] add a file logger.
- [x] add a library page and use it as the welcoming page.
- [x] handle playback change events not from interactions with the application's integrated client but from interactions with other clients through Spotify connect.
- [ ] improve `README` and documentations in general. Add a new demo/examples for `v0.5.0-pre-release`.

**Comment by aome510** [comment]
Hey @0323pin, I have published the new version [`v0.5.0`](https://github.com/aome510/spotify-player/releases/tag/v0.5.0) and made a [HN post](https://news.ycombinator.com/item?id=29110108). You can check those out =)).

I probably will make another Reddit post later today. So stay tuned for that as well 💪

**Comment by aome510** [comment]
@0323pin posted in [Reddit](https://www.reddit.com/r/rust/comments/qmr4e4/spotify_player_a_command_driven_music_player_on/)

**Comment by 0323pin** [comment]
@aome510 If I knew, I'd wait until today.
Posted yesterday on reddit, https://www.reddit.com/r/UsabilityPorn/comments/qlwo8b/frankenwm_living_in_the_tui/

**Comment by aome510** [comment]
wow that looks nice 💪 !

**Comment by 0323pin** [comment]
@aome510 feel free to use them, https://codeberg.org/pin/franken-nbsd/src/branch/main/home/.config/hn-tui.toml

https://codeberg.org/pin/franken-nbsd/src/branch/main/home/.config/spotify-player

I've just returned to a dark theme after more then a year using a light one.
