### ISSUE TITLE
Liked songs displayed as playlist

### ISSUE THREAD

**Issue by Silimoon** [aome510/spotify-player#229]
**Is your feature request related to a problem? Please describe.**
I have tons of tracks just lying around in my liked songs collection and would like to play directly from there.

**Describe the solution you'd like**
Is there any way to include them as a playlist?

**Describe alternatives you've considered**
I could also add them into an external playlist, but with 450+ tracks that is pretty tedious.

**Comment by Silimoon** [comment]
After digging through the commands, I found the one for displaying all liked songs. Still I find it more convenient to have them show up as a playlist

**Comment by aome510** [comment]
You can start a playback from liked song page like a playlist page. 

Due to its API restriction, it's impossible to treat liked songs as a Spotify playlist.

Will close this issue for now as using liked song page should be enough.
