### ISSUE TITLE
Queue page has only scroll

### ISSUE THREAD

**Issue by Keep-Simple** [aome510/spotify-player#233]
**Describe the bug**
Queue page has only scroll feature
**To Reproduce**
Steps to reproduce the behavior.
Open queue page
**Expected behavior**
Ability to rearrange tracks as described in readme, ability to play any track from the queue by pressing enter, etc
**Log and backtrace**
Reference log and backtrace, which are usually located in `$HOME/.cache/spotify-player/`, of a run reproducing the bug.

**Screenshots**

**Environment**

- OS: macos
- Application version: 0.15.0
- Application features: brew install

**Additional context**

**Comment by aome510** [comment]
This is expected behavior, so not a bug. Spotify only provides very limited APIs for queues (get-queue and add-item-to-queue), so re-arranging a queue or playing an item from a queue is impossible.
