### ISSUE TITLE
Theme ignored

### ISSUE THREAD

**Issue by maglore9900** [aome510/spotify-player#236]
**Describe the bug**
The current documentation for using themes is incorrect, there are certain values that Spotify-Player is looking for, including capitalization, which it will complain about.

However, even after make the necessary changes so the theme is accepted, it ignores the theme values and continues to display with the default colors.

**To Reproduce**
create a theme, adjust colors, use RGB or Hex codes, run spotify-player -t [theme name], no display / color changes are applied

**Expected behavior**
theme should change

**Log and backtrace**
Reference log and backtrace, which are usually located in `$HOME/.cache/spotify-player/`, of a run reproducing the bug.

**Screenshots**

**Environment**

- OS: NixOS
- Application version: 23.05
- Application features: if applicable, provide [cargo features](https://doc.rust-lang.org/cargo/reference/features.html) used to build `spotify_player`
- player in distro apps

**Additional context**

**Comment by aome510** [comment]
> create a theme, adjust colors, use RGB or Hex codes, run spotify-player -t [theme name], no display / color changes are applied

Theme selection still works fine for me. Can you provide the corresponding theme configs? Without that, it's impossible to know the problem.

> The current documentation for using themes is incorrect, there are certain values that Spotify-Player is looking for, including capitalization, which it will complain about.

Can you elaborate on which part is incorrect or outdated?

**Comment by maglore9900** [comment]
Hello Aome510, certainly.

Here is an excerpt from the documentation in the configuration setting:
`bright_blue
bright_cyan
bright_green
bright_magenta
bright_red
bright_white
bright_yellow`

here is what it requests when I run spotify-player with the theme. as you see below it wants camel case
`
BrightBlack = "#555555"
BrightRed = "#ff5555"
BrightGreen = "#50fa7b"
BrightYellow = "#f1fa8c"
BrightBlue = "#bd93f9"
BrightMagenta = "#ff79c6"
BrightCyan = "#8be9fd"
BrightWhite = "#ffffff"`


here is an config where I took the existing theme and changed the values of Red and Magenta
`[[themes]]
name = "default"
[themes.palette]
background = "#1e1f29"
foreground = "#f8f8f2"
Black = "#000000"
Red = "#d21a75"
Green = "#50fa7b"
Yellow = "#f1fa8c"
Blue = "#bd93f9"
Magenta = "#972050"
Cyan = "#8be9fd"
White = "#bbbbbb"
BrightBlack = "#555555"
BrightRed = "#ff5555"
BrightGreen = "#50fa7b"
BrightYellow = "#f1fa8c"
BrightBlue = "#bd93f9"
BrightMagenta = "#ff79c6"
BrightCyan = "#8be9fd"
BrightWhite = "#ffffff"


[themes.component_style]
block_title = {fg="Red"}
border = {}
playback_track = { fg="Red", modifiers = ["Bold"] }
playback_artists = { fg="Red", modifiers = ["Bold"] }
playback_album = { fg="Red" }
playback_metadata = { fg = "BrightBlack" }
playback_progress_bar = { bg="Magenta", fg="Red" }
current_playing = { fg="Red", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
selection = { modifiers = ["Bold", "Reversed"] }`

after loading the theme name 'default'  the spotify-player shows no color changes.

any help you can provide is greatly appreciated!

**Comment by aome510** [comment]
> Here is an excerpt from the documentation in the configuration setting:
> `bright_blue
> bright_cyan
> bright_green
> bright_magenta
> bright_red
> bright_white
> bright_yellow`
> 
> here is what it requests when I run spotify-player with the theme. as you see below it wants camel case
> `
> BrightBlack = "#555555"
> BrightRed = "#ff5555"
> BrightGreen = "#50fa7b"
> BrightYellow = "#f1fa8c"
> BrightBlue = "#bd93f9"
> BrightMagenta = "#ff79c6"
> BrightCyan = "#8be9fd"
> BrightWhite = "#ffffff"`

Ah thanks for pointing this out. Will update the document accordingly.

> here is an config where I took the existing theme and changed the values of Red and Magenta

It's not possible to override the `default` configuration. You can name it something else and set the `theme` config variable in `app.toml`. Sorry for the confusion.

**Comment by maglore9900** [comment]
Thank you! Ill give it a go. I should have known the "default" name was probably in use. Not sure what I was thinking.

Thanks again!

**Comment by maglore9900** [comment]
Works!
