### ISSUE TITLE
Bluetooth Speak / Device support

### ISSUE THREAD

**Issue by maglore9900** [aome510/spotify-player#237]
**Is your feature request related to a problem? Please describe.**
I cannot select my bluetooth speakers from the device menu

**Describe the solution you'd like**
Support bluetooth

**Describe alternatives you've considered**
Alternative programs such as spotify-tui support this feature

**Comment by aome510** [comment]
Make sure you already follow the instructions described in https://github.com/aome510/spotify-player#spotify-connect to enable Spotify connect support.

Unlike `spotify-tui`, which also requires specifying `client_secret`, `spotify_player` only requires specifying `client_id`.

**Comment by maglore9900** [comment]
Hello Aome,
Yep, did that. So, at the moment I have both spotifiy-tui and spotify-player installed, as well as spotify itself. Once i get spotify or spotify-tui playing with the bluetooth speaker, I can see my spotify data in spotify-player and I can control it. 

What I cant do is only use spotify-player and select my bluetooth speaker as a device.

**Comment by maglore9900** [comment]
Wait, looking at the client id configuration stuff now, and I am not sure I did that. Let me confirm.

**Comment by maglore9900** [comment]
Sorry it was exactly that!

Set client_id to my spotify app client id was the solution.

thanks!
