### ISSUE TITLE
Allow creation of streaming device in daemon mode + don't register another device when spawning TUI

### ISSUE THREAD

**Issue by nazriel** [aome510/spotify-player#238]
**Is your feature request related to a problem? Please describe.**
Currently if I spawn spotify_player in daemon and then launch another instance in TUI mode - two streaming devices in total are being registered - both with the same name but different IDs

If I set `enable_streaming` to `false` TUI doesn't register new streaming device but then same happens to daemon mode.

**Describe the solution you'd like**
I would like to use spotify_player in daemon mode akin to spotifyd and let it register as streaming device.
Then I would like to use spotify_player in TUI mode from time to time in order to control what is being played.

I tend to control spotify device with Raycast plugin and thus I don't need TUI to be opened 100% of the time. 
I use spotify_player in --daemon mode so it registers itself as streaming device.
But from time to time when I want to change playlist I use TUI mode - I would expect TUI to NOT register another streaming device

I wonder if I miss some option to allow such setup or it isn't possible right now.

**Comment by aome510** [comment]
I don't think it's possible now to run TUI with streaming disabled beside setting `enable_streaming=false`.  Should be easy to add a new cli option to disable streaming when running the TUI. Maybe we can remove `enable_streaming` as a config option in favours of cli option as it's more flexible.
