### ISSUE TITLE
Feature: Ability to open menu on an item when using the / search function

### ISSUE THREAD

**Issue by noelpilled** [aome510/spotify-player#240]
**Is your feature request related to a problem? Please describe.**
When using the / search function on a page like your liked songs for example, you can't open the actions/shortcuts menu on an item without playing the track and exiting the / search first.

**Describe the solution you'd like**
The / search should be changed to be more in line with the g-s search page, where you can tab out of the search bar and interact with items as necessary.

**Describe alternatives you've considered**
When exiting search, currently selected item is reset to the top of the page. Consider leaving currently selected on where it was during the search. This way you still have to exit the search, but can open the shortcut menu on it without playing the track.

**Comment by aome510** [comment]
> you can't open the actions/shortcuts menu on an item without playing the track and exiting the / search first.

You can add a new binding to `ShowActionsOnSelectedItem` that doesn't involve character, e.g `control-{char}` or `alt-{char}`. Please note that `ShowActionsOnSelectedItem` already has a binding `control-space` for that purpose.
