### ISSUE TITLE
Application hangs if run inside zellij with sixel/image support

### ISSUE THREAD

**Issue by ErenKyojin** [aome510/spotify-player#241]
**Describe the bug**
Starting the application after installing either of sixel or image features does nothing and the process just hangs forever if ran in a zellij session in kitty, if i run it directly inside kitty everything works fine.

**To Reproduce**
Run kitty, start a zellij session and run spotify_player with image support installed

**Log and backtrace**
[spotify-player-23-08-31-11-27.log](https://github.com/aome510/spotify-player/files/12484674/spotify-player-23-08-31-11-27.log), the backtrace is empty.

**Environment**

- OS: Arch linux
- Application version: 0.15.0
- Application features: sixel, image

**Comment by apprehensions** [comment]
test if spotify_player runs under tmux, or use kitty's integrated terminal workspaces

**Comment by ErenKyojin** [comment]
In tmux it does work, as well as in kitty. 
I like to use zellij instead of tmux or kitty's multiplexer because of the clean interface and because i also use other emulators.

**Comment by apprehensions** [comment]
Then it is a zellij bug, close this issue and move it to there.

**Comment by funkycode** [comment]
I doubt the issue is inside zellij side, because if I set `TERM=tmux-256color` it does work in zellij.
On other hand when running in tmux with `TERM=xterm-kitty` it hangs the same way as in zellij without changing env variable.

**Comment by ikopytko** [comment]
Same issue with setup kitty+zellij, and setting TERM to tmux-256color works. Found out that app hangs on the line `viuer::get_kitty_support()`. But still unclear where this should be submitted.

**Comment by DrGenetik** [comment]
The Viuer crate project is at https://github.com/atanunq/viuer. There is an issue filed there that is probably the same as this: https://github.com/atanunq/viuer/issues/70.

I think the fix landed in https://github.com/atanunq/viuer/pull/90 and included in release 0.11.0 (https://github.com/atanunq/viuer/releases/tag/v0.11.0) of the Viuer crate.

Spotify-player is still on 0.9.2 of this crate (https://github.com/aome510/spotify-player/blob/master/spotify_player/Cargo.toml#L45) from June 2025. It would probably be worth trying to bump this dependency and see if this fixes this issue. A bonus is that spotify-player might get album image display under Konsole.

**Comment by luissolanodev** [comment]
Same issue here

**Comment by s1xs1x** [comment]
Same issue here

**Comment by s1xs1x** [comment]
Same issue here
