### ISSUE TITLE
mute

### ISSUE THREAD

**Issue by apprehensions** [aome510/spotify-player#243]
**Is your feature request related to a problem? Please describe.**
i don wan to constantly press - and wait a minute cuz volume is slow
 
**Describe the solution you'd like**
a mute keybind

**Describe alternatives you've considered**
muting alsa enitrely

**Comment by aome510** [comment]
> i don wan to constantly press - and wait a minute cuz volume is slow

don't you already have the system mute key? Because of that, it doesn't make sense to implement one for `spotify_player`. `spotify_player` also supports setting volume from CLI: `spotify_player playback volume 0` in case you may need.

**Comment by apprehensions** [comment]
I want to mute specifically spotify-player and not the rest of my system.
