### ISSUE TITLE
Genius API is sometimes weird

### ISSUE THREAD

**Issue by arcstur** [aome510/spotify-player#250]
**Is your feature request related to a problem? Please describe.**
Getting lyrics from its API behaves a bit weird sometimes.

Searching in their api "Peace Sells Megadeth" show the correct song, but "Peace Sells Remastered Megadeth" does not! And it even does not show Megadeth after the first results.

**Describe the solution you'd like**
Don't know how this could be solved.

**Describe alternatives you've considered**
Maybe we could search for a different API service which we could pass the song and the author as parameters, unlike Genius which is a general term.
Or maybe we could ask the user "is this lyrics wrong" yes -> "please type a search"?

I don't think this has a solution in the very near future, but tracking it could be useful, that's why I created this issue.

By the way, awesome project!! I'm enjoying a lot using it :)

**Comment by aome510** [comment]
Genius lyric doesn't work sometimes, especially when the query "{track} {artists}" has some additional info like "Remastered", "Remix", etc. 

This might be addressed by using the unreleased Spotify lyric API from https://github.com/librespot-org/librespot, so don't need to rely on third-party APIs. I'm not sure what their plan is to release the new version, so for now, I'll stick with just using Genius API.

Related: #155

**Comment by Icelk** [comment]
> Searching in their api "Peace Sells Megadeth" show the correct song, but "Peace Sells Remastered Megadeth" does not! And it even does not show Megadeth after the first results.

My PR converts "Peace Sells Remastered Megadeth" into "Peace Sells Megadeth"! (it's pretty general)

Should suffice until (if) another lyrics source is added.
