### ISSUE TITLE
"Where is use_default?"

### ISSUE THREAD

**Issue by AlJohri** [aome510/spotify-player#254]
**Describe the bug**
When I open `spotify_player` for the first time I get this window pop up. I'm not 100% sure if this is a spotify_player thing or an iTerm2 thing, but it only happens when I open spotify_player.

NOTE: I am using `enable_media_control = true`.

**To Reproduce**
Open `spotify_player` on macOS on iTerm2 using a dedicated hotkey window.

**Expected behavior**
I expect just `spotify_player` to open.

**Log and backtrace**
Logs: https://gist.github.com/AlJohri/d69bf94c677ee9dcda082de41bbd10f1

**Screenshots**
<img width="792" alt="Screenshot 2023-09-15 at 8 50 00 AM" src="https://github.com/aome510/spotify-player/assets/2790092/011c3523-5665-4377-a4c9-11bf5d84f6bd">

**Environment**

- OS: macOS
- Application version: `0.15.0`
- Application features: if applicable, provide [cargo features](https://doc.rust-lang.org/cargo/reference/features.html) used to build `spotify_player` (installed via brew, whatever the defaults are there). I also enabled `enable_media_control = true`.

**Additional context**

iTerm2 Settings for HotKey Window for `spotify_player`:

<img width="1030" alt="Screenshot 2023-09-15 at 8 57 23 AM" src="https://github.com/aome510/spotify-player/assets/2790092/4fa8f4a6-6c2c-41e9-ad61-204a4469a9ff">
<img width="1042" alt="Screenshot 2023-09-15 at 8 57 44 AM" src="https://github.com/aome510/spotify-player/assets/2790092/0e06fced-76c9-46bc-8ad1-c553e5263696">
<img width="1128" alt="Screenshot 2023-09-15 at 8 58 14 AM" src="https://github.com/aome510/spotify-player/assets/2790092/f7860df8-3a11-4add-afa7-543e4c8bc979">

**Comment by aome510** [comment]
With `media_control` enabled, MacOS specifically, the app will spawn a separate window named `spotify_player` for listening to OS media events. IIUC, the "Where is use_default?" popup is to select settings for the window and should happen only once. I don't exactly which option I chose but it shouldn't affect the way `spotify_player` is used.

**Comment by AlJohri** [comment]
Thank you! Once I selected an application from the list, the pop up went away. Indeed the `spotify_player` dock icon and notification icon all look like my selected application.
