### ISSUE TITLE
Lagginess while scrolling through liked tracks

### ISSUE THREAD

**Issue by jacksongoode** [aome510/spotify-player#257]
**Describe the bug**
Scrolling with arrows is laggy on liked tracks list. This doesn't happen on shorter track lists. Wondering what would be causing lagginess though?

**Environment**
- OS: macOS 13
- Application version: Latest
- Application features: default

**Comment by aome510** [comment]
What is the size of your liked track list?

**Comment by jacksongoode** [comment]
Around 8000 tracks I would say? But I don't think the size should matter in scrolling through the view? I would expect that behavior to be decoupled from the size of the playlist.

**Comment by aome510** [comment]
> Around 8000 tracks I would say? But I don't think the size should matter in scrolling through the view? I would expect that behavior to be decoupled from the size of the playlist.

yeah, it should not. I can try to reproduce by duplicating my local data.

**Comment by jacksongoode** [comment]
Super cool thanks!
