### ISSUE TITLE
Rename spotify_player?

### ISSUE THREAD

**Issue by jacksongoode** [aome510/spotify-player#264]
This is random but its about the naming of the project. The cli/binary is called `spotify_player` while the project is called `spotify-player`. Should the binary also be named `spotify-player`?

This is also a suggestion that the project might want to not use Spotify in its name as I believe its trademarked. This is more of a long term thought.

**Comment by PetrichorFlavour** [comment]
Yes, absolutely agree. The name is not searchable at all, very hard to find this project. Just something somewhat similar to Spotify would be much better. Like Spottie, Saponify, Reticuli, Rancidify, Interstratify anything ending with -ify or contains spot would work.

**Comment by jacksongoode** [comment]
Other short options:
- sptlr
- spotly
- spotler
- spotter
- splayer

**Comment by jacksongoode** [comment]
Any thoughts @aome510 ?

**Comment by aome510** [comment]
Hey, thanks for the discussions guys. I'm still in favor of keeping the name as-is mainly not to create any confusion for old users.

Regarding the trademark, I believe that as long as I don't profit from the project, Spotify won't do anything (hopefully). [`spotify-tui`](https://github.com/Rigellute/spotify-tui) is another project with `spotify` in its name and it has been there for a while now. `spotify-tui` is significantly more popular than `spotify_player`.

**Comment by jacksongoode** [comment]
Would it make sense to change the binary from the underscore to the dash then? There is some inconsistency there, unless there's a good reason for it?

**Comment by aome510** [comment]
> Would it make sense to change the binary from the underscore to the dash then? There is some inconsistency there, unless there's a good reason for it?

Agree there is some inconsistency between dash and underscore. I would avoid making such change for backward compatibility. 

`spotify-player` should only be used as** the Github project's name**. Uses in other places should be `spotify_player`. Feel free to make a PR to update README or other documents if you found any inconsistency in the use of the project name.

**Comment by apprehensions** [comment]
> spotify-tui is significantly more popular than spotify_player

in it's current state it is dead. i've been paying attention on the internet lately and have been moving a significant amount of spotify-tui users to spotify_player

**Comment by apprehensions** [comment]
related: #101

**Comment by catgoose** [comment]
> > spotify-tui is significantly more popular than spotify_player
> 
> in it's current state it is dead. i've been paying attention on the internet lately and have been moving a significant amount of spotify-tui users to spotify_player

I think this project is the only option since spotify-tui is no longer maintained.  If there were another project that was more like spotify-tui I'm sure it would be the favored choice over `spotify-player/spotify_player`

**Comment by TornaxO7** [comment]
May I suggest another name? `spotifyers` (Pronounced: "spotif-fires!")

**Comment by kensad-ops** [comment]
May i suggest `yats` stand for: `yet another tui spotify`  (took inspiration from [yay](https://github.com/Jguer/yay) initial through was `yast : yet another spotify-tui` but it have been taken)

**Comment by apprehensions** [comment]
`spire` from Spotify and rust file extension `.rs`

**Comment by 250h** [comment]
Maybe just change the name of executed binary instead of the whole project? It's a little bit annoying to start `spotify_player` in terminal. As I konw, spotify-tui's command is the shorter `spt`.

**Comment by apprehensions** [comment]
> Maybe just change the name of executed binary instead of the whole project?

Given `spt` for spotify-tui, `sp`.
