### ISSUE TITLE
0.5.0 crashing badly

### ISSUE THREAD

**Issue by 0323pin** [aome510/spotify-player#27]
@aome510 Unfortunately 0.5.0 is crashing badly, had no issues on 0.4.0

Log file by e-mail

**Comment by aome510** [comment]
Wow that sucks 😢 . I just looked into the log file and it looks fine to me. 

Can you elaborate in more details how did it crash? Does it happen frequently? I'm using `v0.5.0` atm and it works normally for me.

**Comment by aome510** [comment]
@0323pin I can partially guess the problem but it's pretty weird that it doesn't report the error in the log file.

I guess the issue is because you specify `client = '******'` which spotify libraries don't like. Hope this solves the problem.

**Comment by 0323pin** [comment]
> I guess the issue is because you specify client_id = '******' in app.toml which spotify libraries don't like

No, that was just me covering my actual client ID and username on the log file.

> Can you elaborate in more details how did it crash?

Thread panic. I'll try to write it down old fashion way because the window takes no input and I have to kill it through the window manager to close it.

> Does it happen frequently?

**Always**, as soon as I try to do a search or play a song, I haven't been able to do anything.

**Comment by 0323pin** [comment]
@aome510 just one question before I go ahead and rebuild 0.5.0, what DE/WM do you use?

**Comment by aome510** [comment]
@aome510 I currently use macos daily. I still occasionally use Linux with i3 and Manjaro linux.

If it is thread panic, can you run `spotify_player 2> log.txt` and then send me the log file so I can see the thread panic messages?

**Comment by 0323pin** [comment]
> If it is thread panic, can you run spotify_player 2> log.txt and then send me the log file so I can see the panic messages?

Yes, I can do that but, I need to re-build it first.
That said, i wonder if we can get anything there.
I can launch the app and navigatd the panes, the thread panic occurs when there is an input action.

I'll get back to you in 4 - 5 hours..

**Comment by 0323pin** [comment]
@aome510 Here's the requested output. I can actually play songs but, only those which are accessible without search. Hiting Enter or searching crashes the player.

At least, I can still listen to music but, I feel that I should not merge the update as is. 0.4.0 is for now the version available for any other user.

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', spotify_player/src/event/window.rs:588:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', spotify_player/src/event/window.rs:588:50
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', spotify_player/src/event/window.rs:588:50
stack backtrace:
   0:         0x94722efc - <unknown>
   1:         0x9475b40c - <unknown>
   2:         0x94711275 - <unknown>
   3:         0x94719a9b - <unknown>
   4:         0x947195f3 - <unknown>
   5:         0x9471a073 - <unknown>
   6:         0x94723250 - <unknown>
   7:         0x94723024 - <unknown>
   8:         0x94719ba2 - <unknown>
   9:         0x93f32591 - <unknown>
  10:         0x93f32552 - <unknown>
  11:         0x940913ee - <unknown>
  12:         0x9408d973 - <unknown>
  13:         0x94185a36 - <unknown>
  14:         0x94188f5f - <unknown>
  15:         0x940ce9d2 - <unknown>
  16:         0x941a3331 - <unknown>
  17:         0x9417fdcb - <unknown>
  18:         0x94076c57 - <unknown>
  19:         0x9418df0b - <unknown>
  20:         0x94033c54 - <unknown>
  21:         0x94138683 - <unknown>
  22:         0x9470e3d3 - <unknown>
  23:     0x71b0e0c0c84f - <unknown>
  24:     0x71b0e009af40 - <unknown>

```

**Comment by aome510** [comment]
Thanks @0323pin. The log is helpful.

Can you confirm that the below is what you did to produce the panic:
- Start `spotify-player` which gets you to the Library page
- Press '/' to search the page
- Type something then press `Enter`

Judging from the log, it seems that the error happens because `ChooseSelected` is called but there are any playlists to act on.

**Comment by 0323pin** [comment]
@aome510 Yes, that's what I did to produce the thread panic.

> Judging from the log, it seems that the error happens because ChooseSelected is called but there is no playlist to act on.

I don't use playlists. Right now I'm stuck with _Alice In Chains - Dirt_, could be worst :)

I can start the song I was on by pressing Space but, if I hit Enter the same happens.

**Comment by aome510** [comment]
@0323pin pushed a fix in https://github.com/aome510/spotify-player/commit/7fa610b7f5b60d8e765f328a5a9d5698f2643230. Please let me know if the error still persists

**Comment by 0323pin** [comment]
@aome510 This solved the issue, thanks! 🥇 

Should I merge 0.5.0 building the package from 7fa610b or, would you like to release 0.5.1?
Thank you.

**Comment by aome510** [comment]
@0323pin great! I'll release `0.5.1` with the fix soon 💪

**Comment by 0323pin** [comment]
Awesome thanks 👍

**Comment by 0323pin** [comment]
@aome510 merged, https://mail-index.netbsd.org/pkgsrc-changes/2021/11/05/msg242861.html
