### ISSUE TITLE
Enable extra features in a Homebrew Install

### ISSUE THREAD

**Issue by terryvfx** [aome510/spotify-player#270]
How do you enable the extra features like notify, lyrics, etc on a homebrew install? I was looking at the documentation and commands available but I couldn't figured out.

**Comment by aome510** [comment]
> How do you enable the extra features like notify, lyrics, etc on a homebrew install? I was looking at the documentation and commands available but I couldn't figured out.

You can enable a feature by specifying `--features` when running `cargo install/build`. IIRC, homebrew package does have all extra features enabled (notify, lyric, etc): https://github.com/Homebrew/homebrew-core/blob/master/Formula/s/spotify_player.rb#L33. [README](https://github.com/aome510/spotify-player/blob/master/README.md#lyric) does mention how to install it.
