### ISSUE TITLE
Loose focus on startup (macOS)

### ISSUE THREAD

**Issue by jacksongoode** [aome510/spotify-player#277]
**Describe the bug**
Starting causes the active terminal to loose focus. I think because of the mpris handler or whatever activity is being spawned outside the terminal that is taking focus.

Latest version, macOS

**Comment by aome510** [comment]
This is an expected behavior for MacOS if the media control feature is enabled. From the config document,

> MacOS and Windows require an open window to listen to OS media event. As a result, spotify_player needs to spawn an invisible window on startup, which may steal focus from the running terminal. To interact with spotify_player, which is run on the terminal, user will need to re-focus the terminal. Because of this extra re-focus step, the media control support is disabled by default on MacOS and Windows to avoid possible confusion for first-time users.

AFAIK, there is no good workaround this focus losing issue on startup.

**Comment by aome510** [comment]
@jacksongoode Will close this for now. Lmk if you figure a way to resolve this issues or have any related issues.
