### ISSUE TITLE
Lyric finder returns 18th century political pamphlet rather than correct lyrics

### ISSUE THREAD

**Issue by SebRollen** [aome510/spotify-player#280]
**Describe the bug**
This one is pretty funny. When I navigate to the lyric page for the track "Love Will Tear Us Apart - 2010 Remaster" by Joy Division, the lyric page displays the full text of the 1790 political pamphlet [Reflections on the Revolution in France](https://en.wikipedia.org/wiki/Reflections_on_the_Revolution_in_France) by Edmund Burke rather than the correct lyrics.

I have since gotten quite a few other random misses, including a chapter out of Joyce's "Ulysses" and Simone de Beauvoir's "The Second Sex"

The unifying characteristics between these three seem to be the presence of a hyphen in the name of the track, and some version of "Remaster" in the track name.

**To Reproduce**
Steps to reproduce the behavior.

Build spotify-player with the lyric-finder feature, start playback for "Love Will Tear Us Apart - 2010 Remaster" by Joy Division and go to the lyric page using "g L".

**Expected behavior**
Should return the correct lyrics from Genius.

**Log and backtrace**
Reference log and backtrace, which are usually located in `$HOME/.cache/spotify-player/`, of a run reproducing the bug.

Nothing particularly noteworthy in the logs, the lyric-finder seems to think it found the correct lyrics:

```
2023-11-01T19:14:12.913150Z  INFO client_request{request=GetLyric { track: "Kangaroo - Remastered", artists: "This Mortal Coil" }}: spotify_player::client: successfully handled the client request, took: 1173ms
```

**Screenshots**
![Screen Shot 2023-11-01 at 2 55 15 PM](https://github.com/aome510/spotify-player/assets/38324289/7ddfaac0-70ad-4677-b4c2-b6bf0e05b2b8)
![Screen Shot 2023-11-01 at 3 12 14 PM](https://github.com/aome510/spotify-player/assets/38324289/1ee83881-ad33-4180-81fe-781881745d0b)
![Screen Shot 2023-11-01 at 3 14 16 PM](https://github.com/aome510/spotify-player/assets/38324289/edf3c85e-66e8-469d-b154-30636a433308)

**Environment**

- OS: iOS
- Application version: 0.15.2
- Application features: lyric-finder

**Additional context**
I tried replicating the behavior by passing in the track and artist directly to the `lyric-finder` example binary, but when doing that, it actually returned the correct lyrics.

This is the funniest software bug I have run into, and I'm totally fine with it not being fixed for the easter-egg potential haha.

**Comment by aome510** [comment]
> This one is pretty funny. When I navigate to the lyric page for the track "Love Will Tear Us Apart - 2010 Remaster" by Joy Division, the lyric page displays the full text of the 1790 political pamphlet [Reflections on the Revolution in France](https://en.wikipedia.org/wiki/Reflections_on_the_Revolution_in_France) by Edmund Burke rather than the correct lyrics.

Haha, nice catch.

There is a commit to remove remastered and remix info when query the lyric (https://github.com/aome510/spotify-player/commit/bd1659a70ace449e90efbd25a543d17ad9df02f6). Can you try again with the latest `main` to see if it fixes the issue?

**Comment by SebRollen** [comment]
Missed that this had already been fixed, thanks for the quick response!
