### ISSUE TITLE
Sonos support

### ISSUE THREAD

**Issue by Lau-r-a** [aome510/spotify-player#288]
**Is your feature request related to a problem? Please describe.**
Currently Sonos speakers don't show up in the device list.
Its possible to see what song is currently is played if started from the spotify ui, but there's no controls whatsoever.

**Describe the solution you'd like**
Support for Sonos Devices.

**Describe alternatives you've considered**
Using the spotify ui...

**Comment by aome510** [comment]
Did you set up Spotify Connect as in https://github.com/aome510/spotify-player#spotify-connect? It should list all the available devices as the official Spotify app

**Comment by Lau-r-a** [comment]
I set it up like that. I'm also able to see all the other Spotify Clients but I can't see my two Sonos devices in the list, while they show up in the other clients.

**Comment by aome510** [comment]
> I set it up like that. I'm also able to see all the other Spotify Clients but I can't see my two Sonos devices in the list, while they show up in the other clients.

What happens if you connect to the sonos device from the official client. Does the device show up in `spotify_player` if you call `SwitchDevice`?

**Comment by Lau-r-a** [comment]
The sonos speaker shows up in the cli Playback info with it's name when the playback is started elsewhere. But not in the Device list itself.

**Comment by aome510** [comment]
Well after doing some research, look like Spotify APIs don't provide support for sonos https://github.com/spotify/web-api/issues/1337 and it is common problem for many people. Because of that, there is nothing I can do from `spotify_player` side.
