### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by 3JlOy-PYCCKUi** [aome510/spotify-player#29]
In the Requirements section of README.md it says
>A Spotify Premium account is **recommended** to enable all application's supported features.

But without Spotify Premium account I could not log in by entering a correct password (I checked on the sporify website). The error was `Failed to authenticate`.

**Comment by 3JlOy-PYCCKUi** [comment]
I just found an error in spotify-player.log (which is marked as WARN)
`spotify_player::auth: failed to authenticate: Login failed with reason: Premium account required`

I assume the readme should state that premium is required, not recommended

**Comment by aome510** [comment]
Hi @3JlOy-PYCCKUi, I just tried to reproduce by creating a new account and confirm the log you just sent. 

Sorry for the confusion. I'll update the readme accordingly.

**Comment by 3JlOy-PYCCKUi** [comment]
> Hi @3JlOy-PYCCKUi, I just tried to reproduce the issue by creating a new account and confirm the log you just sent.
> 
> Sorry for the confusion. I'll update the readme accordingly.

By the way, the fact that it does not work is not your fault, the library you use just does not support it, this is what it says in the librespot's readme

>Note: librespot only works with Spotify Premium. This will remain the case. We will not support any features to make librespot compatible with free accounts, such as limited skips and adverts.
