### ISSUE TITLE
Cache user's saved albums, artists, playlists

### ISSUE THREAD

**Issue by joebonneau** [aome510/spotify-player#291]
**Is your feature request related to a problem? Please describe.**
This may be a product of how I'm using spotify-player (see additional context), but I'm frequently creating new instances of the client and it takes a non-trivial amount of time to fetch all of my saved content every time, especially albums and artists. If possible, caching this content could alleviate the bottleneck I'm running into.

**Describe the solution you'd like**
I'd like for the saved content to be accessible shortly after the client launches. I often find myself waiting for that to occur before I can select an album I'd like to search for and play.

**Describe alternatives you've considered**
An alternative would be to keep a persistent tmux session with the player open so that the content doesn't need to be fetched every time. Another option (which will be an even better one when tracks are marked as explicit) would be to just search for whatever I'm looking for.

**Additional context**
As mentioned, I use tmux (specifically a tmux popup) to launch and interact with spotify-player. In doing so, every time I interact with spotify-player is a new instance of the client.

I'm not sure if there's an easy way to see how many albums I have saved, but I've definitely got well over a thousand.

**Comment by aome510** [comment]
Related: https://github.com/aome510/spotify-player/issues/235
