### ISSUE TITLE
Notification enabaled by default when installing via brew

### ISSUE THREAD

**Issue by TheCreatorAMA** [aome510/spotify-player#292]
**Describe the bug**
When installing spotify_player via brew on Mac OS the notifications are enabled by default. Havent found a way to disable the notifications other than installing spotify_player using cargo instead.

**To Reproduce**
Install spotify_player via brew

**Expected behavior**
Have no notification appear when the next songs plays on Mac OS (they stack up in notification center)

**Log and backtrace**
N/A

**Screenshots**
N/A

**Environment**

- OS: macOS Sonoma v 14.1.1
- Application version: 0.15.2
- Application features: if applicable, provide [cargo features](https://doc.rust-lang.org/cargo/reference/features.html) used to build `spotify_player`

**Additional context**
I may have missed something in the docs but I just want to disable the notifications without installing the application via cargo. I installed it using brew

**Comment by aome510** [comment]
`brew` package enables some extra features when building the application. Context: https://github.com/aome510/spotify-player/issues/189#issuecomment-1556300596.

I would suggest you either reach out to the maintainer or make a PR to `homebrew` repo to update the build file.

Just a note that `spotify_player` isn't responsible for maintaining package from external package manager.
