### ISSUE TITLE
Print `Artist - Song` after using CLI to control playback

### ISSUE THREAD

**Issue by catgoose** [aome510/spotify-player#294]
Related to #279

When using `spotify_player playback next|previous` I would like it if `spotify_player` would output the song that was switched to.  This should only print if there is no active `spotify_player` instance.

For example:

```
❯ spotify_player playback next
Artist - Song
```

**Comment by aome510** [comment]
This is difficult to do because it takes time for Spotify API to show up the changed playback. In other words, calling `current_playback` API after `next` API can give you the previous track. I would suggest you use a separate command (e.g `get key playback` to get the playback instead.

**Comment by ed9w2in6** [comment]
@catgoose This is how you can do it with `get key playback`:

```
spotify_player get key playback \
  | python3 -c 'import sys; import json; detail=json.loads(sys.stdin.read())["item"]; track=detail["name"]; album=detail["album"]["name"]; artists=", ".join([a["name"] for a in detail["artists"]]); link=detail["external_urls"]["spotify"]; print(f"\n{track} ∈ {album}\nby {artists}\n{link}")'
```

For future reference:
`spotify-tui` implemented this here, I believe it does not avoid the issue @aome510 mentioned:
https://github.com/Rigellute/spotify-tui/blob/master/src/cli/cli_app.rs#L393

It also shows if current playback is liked or not using `current_user_saved_tracks_contains`, in which we used for add to library function:

https://github.com/aome510/spotify-player/blob/e25c701f218a1057ea0e1c996cf20af06f7891e5/spotify_player/src/client/mod.rs#L959

**Comment by catgoose** [comment]
> or:
> 
> ```
> spotify_player get key playback | jq -r '.item | "\(.artists | map(.name) | join(", ")) - \(.name)"'
> ```

Thanks this works for me.  I can do:

```
spotify_player playback previous && spotify_player get key playback | jq -r '.item | "\(.artists | map(.name) | join(", ")) - \(.name)"'
```
