### ISSUE TITLE
[QUESTION]: How can I tell if there is a daemon running?

### ISSUE THREAD

**Issue by joebonneau** [aome510/spotify-player#295]
Hey there,

I was curious if there was any easy way to tell whether a spotify_player daemon is already running. I would need to do some more defined testing to provide context, but it seems that sometimes it's not running when I expect it to be, which then requires me to close the player and run `spotify_player -d` to spin it up again.

I have a feeling this might be accomplished by running some sort of system command - if it matters, I'm on MacOS.

Thanks in advance!

**Comment by aome510** [comment]
Daemon should also provide log and backtrace, you can check them in the cache folder

**Comment by joebonneau** [comment]
Gotcha, thanks. I was hoping for something less manual if it exists. Like a specifically named process within htop or a cli command I can run.

**Comment by aome510** [comment]
I'll close this issue for now. Feel free to re-open it if you have other related questions
