### ISSUE TITLE
Configuration option to disable notifications

### ISSUE THREAD

**Issue by oleksandr-oksenenko** [aome510/spotify-player#302]
**Is your feature request related to a problem? Please describe.**
No way to disable notifications in the configuration.

**Describe the solution you'd like**
Would be great to have a configuration option that would allow to disable all notifications from spotify_player.

**Describe alternatives you've considered**
Manually installing using cargo without `notify` feature is an alternative, however, it's not very convenient.

**Additional context**
spotify_player notifications on MacOS are a bit ugly (using Finder icon). Also, I try to limit to a minimum the amount of the notifications I get.

**Comment by aome510** [comment]
Related: https://github.com/aome510/spotify-player/issues/292. This issue seems to be specific to the brew package manager as it installs the application with `notify` feature when the feature is disabled by default.

**Comment by oleksandr-oksenenko** [comment]
@aome510 thanks for reply!
is it disabled by default specifically because it has some issues?
Generally, I feel like hiding features behind compilation flags instead of configurations is a bit inconvenient, since you either have to rely on defaults provided by the packager or resort to compiling the project yourself. Is there a specific reason for this?

**Comment by aome510** [comment]
> @aome510 thanks for reply! is it disabled by default specifically because it has some issues? Generally, I feel like hiding features behind compilation flags instead of configurations is a bit inconvenient, since you either have to rely on defaults provided by the packager or resort to compiling the project yourself. Is there a specific reason for this?

The main reason is to avoid redundant dependencies when building the application if people don't need the notification feature, not because it has some issues. This "feature-behind-compilation-flag" pattern is quite common in rust ecosystem (and possibly c++). That said, I agree that it's convenient to hide features behind compilation flags instead of configurations.
