### ISSUE TITLE
No sound devices available

### ISSUE THREAD

**Issue by kprzybys** [aome510/spotify-player#311]
**Describe the bug**
No sound devices avaliable

**To Reproduce**
Just run spotify_player

**Expected behavior**
Sound devices available

**Log and backtrace**

ALSA lib conf.c:4028:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so (/home/linuxbrew/.linuxbrew/Cellar/alsa-lib/1.2.10/lib/alsa-lib/libasound_module_conf_pulse.so: cannot open shared object file: No such file or directory)
ALSA lib pcm.c:2675:(snd_pcm_open_noupdate) Unknown PCM default

**Screenshots**

**Environment**

- OS: Linux Mint (5.4.0-167-generic #184-Ubuntu SMP Tue Oct 31 09:21:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux)
- Application version: spotify_player 0.16.0
- Application features: None

**Additional context**
None

**Comment by aome510** [comment]
What is the result of `ldconfig -p | grep libasound_module_conf_pulse.so`? Can you also try `sudo apt install alsa-base alsa-utils pulseaudio` and run again?

**Comment by kprzybys** [comment]
> What is the result of  `ldconfig -p | grep libasound_module_conf_pulse.so`? 

None - empty. But:
ldconfig -p | grep libasound
	libasound.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libasound.so.2
	libasound.so.2 (libc6) => /lib/i386-linux-gnu/libasound.so.2
	libasound.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libasound.so


>Can you also try installing the following packages `alsa-base alsa-utils pulseaudio` and run again?
Already installed:

alsa-base is already the newest version (1.0.25+dfsg-0ubuntu5).
alsa-utils is already the newest version (1.2.2-1ubuntu2.1).
pulseaudio is already the newest version (1:13.99.1-1ubuntu3.13).

**Comment by aome510** [comment]
Oh, I got the wrong package. `libasound_module_conf_pulse` should be in `libasound2-plugins`. Can you install it and try again?

**Comment by kprzybys** [comment]
Got it installed:

libasound2-plugins is already the newest version (1.2.2-1ubuntu1).
0 aktualizowanych, 0 nowo instalowanych, 0 usuwanych i 7 nieaktualizowanych.
(base) xxx:~$ spotify_player 
ALSA lib conf.c:4028:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so (/home/linuxbrew/.linuxbrew/Cellar/alsa-lib/1.2.10/lib/alsa-lib/libasound_module_conf_pulse.so: cannot open shared object file: No such file or directory)
ALSA lib pcm.c:2675:(snd_pcm_open_noupdate) Unknown PCM default

Problem persists.

**Comment by aome510** [comment]
At this point, I have no idea why this issue happens unfortunately. It's weird that `libasound2-plugins` installed but `ldconfig -p | grep libasound_module_conf_pulse.so` returns nothing. 

Maybe related: https://github.com/orgs/Homebrew/discussions/790. I saw people resolve the issue by re-installing the dependencies.

**Note**: this kind of dependency problem tends to be not related to `spotify_player` but how the user's system handles the dependency lookup.

**Comment by aome510** [comment]
great to hear that. Will close this issue for now.
