### ISSUE TITLE
`spotify_player authenticate` error message

### ISSUE THREAD

**Issue by liiyung** [aome510/spotify-player#312]
Not so much a bug and more of a support request. 
Trying to run for the first time with `spotify_player authenticate`, I get the error message :
```
Error: try to connect to a client

Caused by:
    No cached credentials found, please authenticate the application first.
```

I have no idea which folder this is scanning from, nor what cached credentials it is looking for. I've created an app with Spotify, and used the generated client ID in .config/spotify-player/app.toml. I may have missed something in the documentation, but I think this is all I need? 

**Environment**
- OS: macOS Monterey 12.6
- Application version: cargo 1.74.0
- Application features: default features, I didn't enable anything

**Comment by liiyung** [comment]
I ran `spotify_player` and I think it's currently working. Thanks for the quick workaround!

**Comment by Viranchee** [comment]
I enter my credentials but it fails to authenticate.

My username is: 31vb2vstos7wg5snxdz3hnwyp7ru
Password Regex: Matches both [A-Za-z0-9]* and \w
