### ISSUE TITLE
[feature]: add option for customize border color

### ISSUE THREAD

**Issue by diegoulloao** [aome510/spotify-player#313]
**Is your feature request related to a problem? Please describe.**
Not a problem at all.

**Describe the solution you'd like**
I'd like to be able to pass an option for change the border color in hexadecimal format.
e.g: `spotify_player --border-color=#ff44cc`

**Describe alternatives you've considered**
None. Open to new solutions.

**Additional context**
I'm using `spotify-player` inside neovim in an embed terminal for handy access. `spotify-player` is using the neovim theme colors, but sometimes the border color is not the best looking, I'd like to be able to customize it passing the arg mentioned above. For sure this will help a lot of neovim users that we want to use this player embed.

Here's a screenshot. I'm thinking in write an article teaching how to use `spotify-player` embed in neovim.

**Screenshot:**
<img width="1440" alt="Screenshot 1" src="https://github.com/aome510/spotify-player/assets/45423661/bf688fb1-3b8a-4295-92f9-c603b22e2d2a">

Here an embed terminal with customized border color (really nice looking):
<img width="1440" alt="Screenshot" src="https://github.com/aome510/spotify-player/assets/45423661/c0c8784b-f2b1-42ad-bfa1-a21d9d413157">

Hope you can take this request 🙏🏻

**Comment by aome510** [comment]
`spotify_player` already supports configuring `border` component style as described in https://github.com/aome510/spotify-player/blob/master/docs/config.md#component-styles.

The format for custom RGB color is quite awkward to use right now: `fg = { Rgb = { r = ..., g = ..., b = ... } }`, which I'll update in a future release.

For your use case, you can add a new theme based on the `default` theme and modifies the `border` component style as follows (`#ff44cc -> RGB(255, 68, 204)`)

```
[[themes]]
name = "test"
[themes.component_style]
border = { fg = { Rgb = { r = 255, g = 68, b = 204 } } }
```

**Comment by aome510** [comment]
> The format for custom RGB color is quite awkward to use right now: fg = { Rgb = { r = ..., g = ..., b = ... } }, which I'll update in a future release.

**Update**: for `v0.16.1` onwards, you can use the hex string to configure component style's color

```toml
[[themes]]
name = "test"
[themes.component_style]
border = { fg = "#ff44cc" }
```
