### ISSUE TITLE
Leak of memory on iTerm2 after long period of usage

### ISSUE THREAD

**Issue by diegoulloao** [aome510/spotify-player#318]
**Describe the bug**
For some reason after open spotify player the iterm2 memory is increasing little by little in the meanwhile the TUI is opened and playing music.

**To Reproduce**
Just play music for a more than 30 minutes and check the memory usage every so often.

**Expected behavior**
Do not see anomalies in the memory usage while using the TUI for long amount of time.

**Log and backtrace**
Not important, no error occurred.

**Screenshots**
<img width="270" alt="Screenshot 4" src="https://github.com/aome510/spotify-player/assets/45423661/02bca099-dbca-4660-91dc-438d390b6671">

**Environment**

- OS: macOs Sonoma 14.1.2
- Application version: latest
- Application features: image, media control

**Additional context**
Running on Iterm2 Build 3.4.22

Only 2 tabs/processes opened:
1. `spotify_player`
2. nvim

This behavior only occurs when spotify player is open.

## important
After a couple of hours of usage, the memory reached even `38GB`!!
The capture above is after 15 minutes of usage, it reached `3GB`.

**Comment by diegoulloao** [comment]
By the way I'm in love with this project, I was using it all the past days, now, the only thing that's stopping me of using it is the memory usage it causes.

Hope I can find some kind of solution on this issue.
Thank you!

**Comment by aome510** [comment]
@diegoulloao what is the value of `Scrollback lines` in the terminal tab of your ITerm2 settings? Using a large or unbounded scrollback buffer may cause a memory issue as rendered images are kept inside the scrollback buffer.

**Comment by aome510** [comment]
FYI, I use `1000` for scrollback lines and have never seen ITerm2 memory usage exceed 2GB.

**Comment by diegoulloao** [comment]
<img width="594" alt="Screenshot 6" src="https://github.com/aome510/spotify-player/assets/45423661/8ffe465f-baf1-4f1b-908e-d47107e22566">

Using `1000` too. Is very weird, after 3-4 hours of usage my memory reached `38GB` using +swap

**Comment by aome510** [comment]
@diegoulloao try to resolve the issue in https://github.com/aome510/spotify-player/pull/319. Can you checkout the branch and test the changes?

**Comment by diegoulloao** [comment]
> @diegoulloao try to resolve the issue in #319. Can you checkout the branch and test the changes?

Sure! first I need to know, how do I change the branch? Sorry, I'm not familiar with rust or cargo.
I installed the app using cargo so long time ago.

**Comment by aome510** [comment]
> > @diegoulloao try to resolve the issue in #319. Can you checkout the branch and test the changes?
> 
> Sure! first I need to know, how do I change the branch? Sorry, I'm not familiar with rust or cargo. I installed the app using cargo so long time ago.
> 
> Thanks for the quick fix and PR! ❤️

You can run the below command in the repo's root
```
git fetch && git checkout fix-memleak-with-image && cargo run --features image
```

**Comment by diegoulloao** [comment]
Ok, let me try it for 30 minutes 🕦 I'll reply

**Comment by diegoulloao** [comment]
replied.
