### ISSUE TITLE
Lazy load playlist (particularly, liked songs) tracks

### ISSUE THREAD

**Issue by khrj** [aome510/spotify-player#323]
**Is your feature request related to a problem? Please describe.**
Whenever I open the "Liked Tracks" view, spotify-player shows `Loading...` for a while before it actually displays the tracks. I believe this is because all the tracks are loaded first and then displayed.

**Describe the solution you'd like**
Ideally, the first batch of tracks should be shown immediately while the rest load in the background

**Describe alternatives you've considered**
Alternatively, you could lazy-load the tracks only on scrolling. However, this is less preferable as it makes searching not possible.

**Additional context**
![image](https://github.com/aome510/spotify-player/assets/44947946/6057e59d-21a6-42b7-ae15-c976047c9b3d)

**Comment by aome510** [comment]
Are you using `v0.16.0` or newer versions? `v0.16.0` should support loading liked tracks from a cached file, so the loading should be instant.

**Comment by khrj** [comment]
I was using 0.15.2 (since that's the latest on nixpkgs: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/audio/spotify-player/default.nix)

Using a cache file works just fine, if I find a little time later I'll try to update the package. Thanks!
