### ISSUE TITLE
Blank space drawn on top left blocking content if `playback_window_position` is `Bottom`

### ISSUE THREAD

**Issue by ed9w2in6** [aome510/spotify-player#326]
**Symptom**
Weird album art artefact drawn on terminal when `playback_window_position` is set to `Bottom` as shown in this screenshot:
![image](https://github.com/aome510/spotify-player/assets/22890124/f095897c-e53e-44f0-be2b-85c9f49bc250)

Blank space drawn on top left that matches the dimensions of the album art.
I guess some logic that allocates space fell through some branch checks. 
You won't notice this if `playback_window_position` is set to Top.

**Expected behavior**
There should NOT be blank space on the top left.

**To Reproduce**
1. clean install of `spotify_player` with the `image` feature
2. start `spotify_player` to generate default `app.toml`
3. change `playback_window_position` to `Bottom` 
4. start `spotify_player`

**Log and backtrace**
No obvious trace from logs, will provide if needed.

**Environment**
+ Application version: `spotify_player 0.16.2`
+ Application features: I build my `spotify_player` using `cargo` with these options:
```
cargo install spotify_player --no-default-features --features daemon,rodio-backend,streaming,lyric-finder,clipboard,image,notify
```
+ `fastfetch` output (truncated):
```
OS: macOS Big Sur 11.4 20F71 x86_64
Shell: zsh 5.8
Terminal: kitty 0.30.0
```

**Additional context**
Issue appeared since version `0.16.2`.

**Issue rating**
+ Reproducibility: always (always/sometimes)
+ Impact: non-breaking (breaking/non-breaking)
  - set `playback_window_position` to `Top` to avoid the issue for now
  - can be work around by typing extra space so I can see what I typed
  - scroll further up or down to see what is behind the blank space.
+ Size: entire app (entire app/specific feature)

**Comment by aome510** [comment]
@ed9w2in6 should be fixed by #328. Can you check out and run the branch locally to see if the fix works?

**Comment by apprehensions** [comment]
![20240103_200736](https://github.com/aome510/spotify-player/assets/47404953/4e93d0c2-cca7-47ba-bcec-aeaea6836b61)
Solves my issue!

**Comment by ed9w2in6** [comment]
@aome510 wow I did not expect you to fix this that quickly, thanks!  
I can confirm that it solves the issue for me as well and again thank you for your time on fixing this.
