### ISSUE TITLE
play icon needs a space lol.

### ISSUE THREAD

**Issue by derspyy** [aome510/spotify-player#335]
https://github.com/aome510/spotify-player/blob/8ea51d4829c4e234c5fd95fdab333eee41d0cd64/examples/app.toml#L20

**Comment by aome510** [comment]
play/pause icon looks fine on my end. If it doesn't work for you, you can always configure the icons to add extra space.

<img width="1429" alt="Screenshot 2024-01-15 at 10 10 15 AM" src="https://github.com/aome510/spotify-player/assets/40011582/cb5217c6-0c05-43e9-b46d-b85684e00604">

**Comment by derspyy** [comment]
on my end whenever you pause, it throws the whole title one space to the right. i thought it was because `pause` had a space after it.

**Comment by aome510** [comment]
> on my end whenever you pause, it throws the whole title one space to the right. i thought it was because `pause` had a space after it.

My guess is that the pause character doesn’t render nicely on your terminal. You can try another character, e.g non-unicode character like `=` to ensure the character’s width is 1.

Will close this issue for now.
