### ISSUE TITLE
Bug: The CLI does not detect a device the TUI is playing from

### ISSUE THREAD

**Issue by chrisgrieser** [aome510/spotify-player#338]
**Describe the bug**
Kind of a follow-up to #336: I tried `connect` but get this issue:
```bash
> spotify_player connect --name "Wohnzimmer Echo"
Bad request: No device with name=Wohnzimmer Echo found
> spotify_player get key devices
[]
```

However, in the interactive player, it clearly is playing from that device: 
![Pasted image 2024-01-16 at 09 42 07@2x](https://github.com/aome510/spotify-player/assets/73286100/788f538a-bf0d-4385-a072-233e15b649f1)

**To Reproduce**
Not sure how to reproduce this, tbh.

**Expected behavior**
The CLI should detect the device, just as the TUI is able to.

**Log and backtrace**
- [spotify-player-24-01-16-09-42.log](https://github.com/aome510/spotify-player/files/13947484/spotify-player-24-01-16-09-42.log)
- The corresponding .backtrace file is empty.

**Environment**
macOS 14.1 (arm)
spotify_player 0.16.3

**Comment by aome510** [comment]
Oh right, I forgot. You will need to setup Spotify Connect as mentioned in https://github.com/aome510/spotify-player#spotify-connect to connect to another device.

**Comment by chrisgrieser** [comment]
ah, I see! Wasn't aware of that. Thanks again.
