### ISSUE TITLE
Add album to user library

### ISSUE THREAD

**Issue by joebonneau** [aome510/spotify-player#347]
I'm not sure if I'm missing the keybinding to do this, so I didn't to label it a feature request prematurely. Is there a way to add an entire album to the user library from either the album page or from an individual track?

An example of what I'd like to do is to select a track from my Release Radar playlist and add the album it's from to my library. This could either be an action on an individual track or an action from the album page. This would help me out greatly to build up what I want to check out.

If this doesn't currently exist, feel free to label as a feature request :) Thanks in advance!

**Comment by aome510** [comment]
> I'm not sure if I'm missing the keybinding to do this, so I didn't to label it a feature request prematurely. Is there a way to add an entire album to the user library from either the album page or from an individual track?

No there is unfortunately. The only way to add album to library now is to select an album. It shouldn't be too difficult to add support for showing actions on track's album or current album page.

**Comment by aome510** [comment]
with #352 landed, you can add a track's album to user library by invoking either `ShowActionsOnCurrentTrack` or `ShowActionOnSelectedItem` (with a selected track), press `3` to select `ShowActionsOnAlbum`, then press `4` to select `AddToLibrary`.

**Comment by joebonneau** [comment]
Amazing! Thank you @aome510.
