### ISSUE TITLE
Failed to compile on 1a038865

### ISSUE THREAD

**Issue by apprehensions** [aome510/spotify-player#349]
```
$ cargo install --git 'https://github.com/aome510/spotify-player' --no-default-features --features pulseaudio-backend,lyric-finder,clipboard,media-control,notify
...
   Compiling config_parser2 v0.1.5
error[E0446]: private type `ServiceState` in public interface
  --> /home/meow/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/souvlaki-0.7.0/src/platform/mpris/dbus/interfaces.rs:19:1
   |
19 | / pub fn register_methods<F>(
20 | |     state: &Arc<Mutex<ServiceState>>,
21 | |     event_handler: &Arc<Mutex<F>>,
22 | |     friendly_name: String,
...  |
25 | | where
26 | |     F: Fn(MediaControlEvent) + Send + 'static,
   | |______________________________________________^ can't leak private type
   |
  ::: /home/meow/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/souvlaki-0.7.0/src/platform/mpris/dbus/mod.rs:54:1
   |
54 |   struct ServiceState {
   |   ------------------- `ServiceState` declared as private

For more information about this error, try `rustc --explain E0446`.
error: could not compile `souvlaki` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `spotify_player v0.16.3 (https://github.com/aome510/spotify-player#1a038865)`, intermediate artifacts can be found at `/tmp/cargo-installpP5ipQ`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by aome510** [comment]
@LucasFA can you take a look into this issue? Otherwise, I can take a look this weekend.

**Comment by LucasFA** [comment]
Mmh. It could be Sinono3/souvlaki#46. What Rust version and OS are you on? I'll do a check on CI Windows and MacOS

**Comment by LucasFA** [comment]
Yep, it seems that's the case. It breaks on 1.73 and older. Want to establish a MSRV policy for spotify-player? 

Relatedly, I'm going to raise an issue and start trying to implement a more comprehensive CI suite, to avoid issues like this.

**Comment by aome510** [comment]
> Yep, it seems that's the case. It breaks on 1.73 and older. Want to establish a MSRV policy for spotify-player?
> 
> Relatedly, I'm going to raise an issue and start trying to implement a more comprehensive CI suite, to avoid issues like this.

MSRV sounds good. Also thanks for taking on this, really appreciate ur contribution to the project ❤️ .

@apprehensions can you upgrade ur `rust` and try again?

**Comment by apprehensions** [comment]
I am on Alpine, and the maintainer of rust still has not updated to 1.75.0.

**Comment by LucasFA** [comment]
I just got a notification: the souvlaki maintainer apparently has managed to reduce the MSRV! I think cargo install doesn't use the Cargo.lock, so it should theoretically compile now

**Comment by LucasFA** [comment]
Just as a heads up, turns out Souvlaki is by far not the only dependency requiring rather new Rust versions. Current MSRV is 1.74
