### ISSUE TITLE
Changing device name doesn't work

### ISSUE THREAD

**Issue by Giuliopime** [aome510/spotify-player#358]
I tried changing the device name by using the following configs in the app.toml file:
```
default_device = "macos-terminal"

[device]
name = "macos-terminal"
```

But when running spotify_player with this config no audio comes out of my system, I able to see though that something is playing on a device called `macos-terminal` from the spotify client.

Am I missing something, or is it not possible to configure the device name?

**Comment by aome510** [comment]
Works perfectly fine for with `0.16.3`. Can you provide any logs or backtraces? Refer to https://github.com/aome510/spotify-player?tab=readme-ov-file#logging for more details

**Comment by aome510** [comment]
@Giuliopime let me know if it still doesn't work for you. Otherwise, I'll close this issue.
