### ISSUE TITLE
Is spotifyd required?

### ISSUE THREAD

**Issue by b-it01** [aome510/spotify-player#364]
I have recently switched over from spotify-tui. As such I had been using spotifyd as backend for the playing Spotify device. I have managed to configure spotify_player through the same client_id I was using before, but I have also noticed that when I run the SwitchDevice command I see both spotifyd and a spotify_player device. If I select the spotify_player device, nothing happens and songs do not play.

Am I doing something wrong? Do I need spotifyd or can I make it work just by using spotify_player?

**Comment by aome510** [comment]
No `spotifyd` is not required. `spotify_player` supports streaming directly from the terminal (https://github.com/aome510/spotify-player?tab=readme-ov-file#streaming).

**Comment by aome510** [comment]
> If I select the spotify_player device, nothing happens and songs do not play

Can you provide any applicable logs or backtraces? Refer to https://github.com/aome510/spotify-player?tab=readme-ov-file#logging for more details

**Comment by b-it01** [comment]
Oh. I believe it is because the default backend is rodio-backend and I am currently using pulseaudio. Is there a way to switch backends or do I have to reinstall by recompiling with the proper option?

**Comment by b-it01** [comment]
Yes. I can confirm doing so has solved the issue, my bad!
