### ISSUE TITLE
Media control spawned process is always in doc

### ISSUE THREAD

**Issue by skoch13** [aome510/spotify-player#373]
**Describe the bug**

Media control additional process is always in dock

**To Reproduce**
Being on MacOS enable `media_control`

**Expected behaviour**
Additional process is spawned, but it is not shown in the doc

**Screenshots**
![Screenshot 2024-02-16 at 15 07 47](https://github.com/aome510/spotify-player/assets/29177689/9de44fe6-4f64-4a5b-a504-c1fdf46badff)

**Environment**

- OS: MacOS 14.3.1
- Application version: latest

**Additional context**
Using with WezTerm, tried also with iTerm2.

**Comment by skoch13** [comment]
Yes, I mentioned that I read the docs. Is this process supposed to be hidden as stated in docs? This is why I opened the issue

**Comment by aome510** [comment]
> Yes, I mentioned that I read the docs. Is this process supposed to be hidden as stated in docs? This is why I opened the issue

The process corresponds to a separate window, so it's visible in the dock.
