### ISSUE TITLE
Cannot play any song

### ISSUE THREAD

**Issue by nolemretaWxd** [aome510/spotify-player#375]
**Describe the bug**
I can't play any song, spotify-player throws error `Failed to handle client request: no playback found` in logs

**To Reproduce**
1. Start spotify-player
2. Log in
3. Try to play anything

**Expected behaviour**
Song should start playing

**Log and backtrace**
Log: https://0x0.st/H5-K.log (I censored playlist and song IDs and access token) (Log is from Windows, the same exact error on Linux)

**Screenshots**

**Environment**

- OS: Linux 6.7.5 (Arch Linux) and Windows 11 build 10.0.22635.3209
- Application version: 0.16.3
- Application was installed from AUR package on Linux and from release builds here on Windows

**Additional context**
I can't connect to spotify-player device from any other device, and I can control other devices from spotify-player.

**Comment by nolemretaWxd** [comment]
Randomly started working again. I'm leaving this issue open because yesterday it was spotify-player fault because official client did work.

**Comment by aome510** [comment]
This kind of error happens sometimes as `spotify` API server may not respond, indicating by `500 Internal Server Error` error. Official Spotify client doesn't really work with API server, so it's possible that the API server doesn't work while the client still functions.

Will close this issue for now as there is nothing to be done here.
