### ISSUE TITLE
Missing mixes from my "made for you"

### ISSUE THREAD

**Issue by ALameLlama** [aome510/spotify-player#381]
**Describe the bug**
I've noticed some artist mixes don't seem to load under, Browse Page -> Made for you.

but If I start it via the Spotify desktop app and go CurrentlyPlayingContextPage, I can go to the mix

**Screenshots**
Not listed under Made for you
![image](https://github.com/aome510/spotify-player/assets/55490546/aac81ed7-1dea-4631-bb21-5591b8785c9b)

I can go to it via context
![image](https://github.com/aome510/spotify-player/assets/55490546/3658539f-518d-4b34-a7f0-4a42ed261e71)

I'm pretty sure this is just a normal generated artist mix so I'm not sure why it's acting weird
![image](https://github.com/aome510/spotify-player/assets/55490546/d57eaeb0-4aff-4823-8b3a-002655e97a17)

**Environment**
- OS: Windows Windows 10
- Application version: 0.16.3

**Additional context**

**Comment by aome510** [comment]
This is kinda expected as not all mixes are included in the "made for you" category. Spotify can, in fact, generate mix for every artist/song/album etc, so only a subset of them are listed
