### ISSUE TITLE
Cannot open song recommendation (TrackRadio) or artist page 

### ISSUE THREAD

**Issue by juan-28** [aome510/spotify-player#383]
---

### Bug Description
**Issue**: When attempting to open the song recommendation page (TrackRadio) on Spotify-player, the application fails to load the page. An error message briefly appears stating "cannot determine current page's context." Then I proceed to only see "loading...". Same for the artist page and information

Note - I applied the fix from here [https://github.com/ramsayleung/rspotify/pull/457] which worked initially but the bug has returned but now for both artist page and the recommendation page.

### Steps to Reproduce
1. Open Spotify-player.
2. Navigate to the TrackRadio or Artist page section.
3. Attempt to open either of the pages and see if it opens.

### Expected Behavior
The expected behavior is that the TrackRadio and artist page should open, displaying song recommendations based on the selected song and the artist song page.

### Screenshots
<img width="980" alt="Screenshot 2024-02-29 at 12 24 04 PM" src="https://github.com/aome510/spotify-player/assets/55826125/a3c1be22-3b7a-48b2-b0a7-c16775fc1f52">
<img width="1006" alt="Screenshot 2024-02-29 at 12 23 51 PM" src="https://github.com/aome510/spotify-player/assets/55826125/91f241eb-9566-402d-b994-a6398ef7ae26">

### Environment
- **OS**: [Macos 13.0  Ventura]
- **Application Version**: [v0.16.3]
- **Application Features**: [images, used latest commit of rspotify instead of the official release]

---

**Comment by aome510** [comment]
I can reproduce the issue with track radio on my end. FWICT, based on the log, it seems `Spotify` API returns floats for non-float fields again 🤦 . Not sure which field corresponds to the error yet. Will take a deeper look when I have more time.

**Comment by aome510** [comment]
Should be fixed by https://github.com/aome510/spotify-player/pull/386. Can you try running from the latest `master` to see if the issue is fixed now?

**Comment by juan-28** [comment]
The issue is fixed! thank you so much :)
