### ISSUE TITLE
Installing the Spotify API workaround (rspotify)

### ISSUE THREAD

**Issue by ociton** [aome510/spotify-player#384]
Hey, I can't find a way to install the fix for artist page [ramsayleung/rspotify#457](https://github.com/ramsayleung/rspotify/pull/457).

**Comment by juan-28** [comment]
The fix was working fine until today! something must have happened, I submitted an issue [here](https://github.com/aome510/spotify-player/issues/383)

**Comment by ociton** [comment]
Oh, ok. Also how do I install any future fixes, because I don't even know if I have installed it right. (im new to rust)

**Comment by aome510** [comment]
Currently, this issue is not fixed with the latest release. I'm still waiting for upstream to release a new version. Related https://github.com/aome510/spotify-player/issues/330
