### ISSUE TITLE
Looking for new maintainer for `spotify_player` AUR package

### ISSUE THREAD

**Issue by aome510** [aome510/spotify-player#39]
I'm the maintainer of the [AUR `spotify_player`](https://aur.archlinux.org/packages/spotify-player) package. However, I'm no longer have access to an Arch machine. I'm looking for a new maintainer for this package.

Anyone if interested, please reply to this issue.

**Comment by alosarjos** [comment]
Sure, it's `alosarjos`, the same as here :)

**Comment by aome510** [comment]
> Sure, it's alosarjos, the same as here :)

Thanks, added. Can you try update the AUR package?

**Comment by aome510** [comment]
> The AUR package is now updated to 0.7.0.
> I also added a .gitignore file to make things easier.

Thank you 🙇 . 

> Also we may look into providing a precompiled binary created through Github actions (Both on AUR and the Github releases page)

That's definitely one thing I plan to add but always forget to do 😆
