### ISSUE TITLE
OpenSpotifyLinkFromClipboard does not work on Wayland

### ISSUE THREAD

**Issue by apprehensions** [aome510/spotify-player#393]
**Describe the bug**
The action OpenSpotifyLinkFromClipboard to paste a spotify URL in spotify_player does not function on Wayland

**To Reproduce**
1. Be on Wayland, no Xwayland
2. Perform the action
3. Observe logs

**Expected behaviour**
It will get pasted and opened

**Log and backtrace**
```
2024-03-11T17:09:02.878456Z ERROR terminal_event{event=Key(KeyEvent { code: Char('O'), modifiers: KeyModifiers(SHIFT), kind: Press, state: KeyEventState(0x0) })}: spotify_player::event: Failed to handle event: get clipboard's content: XCB - couldn't establish conection: DisplayParsingError(DisplayNotSet)
2024-03-11T17:09:06.238562Z ERROR terminal_event{event=Key(KeyEvent { code: Char('O'), modifiers: KeyModifiers(SHIFT), kind: Press, state: KeyEventState(0x0) })}: spotify_player::event: Failed to handle event: get clipboard's content: XCB - couldn't establish conection: DisplayParsingError(DisplayNotSet)
```

**Comment by aome510** [comment]
The error is pretty self-explained: `DisplayParsingError(DisplayNotSet)`. Can you try to run in the terminal the `copy_command` in your config (default to `xclip -sel c` for linux) to see if that works?

**Comment by apprehensions** [comment]
Thats for copying. This issue is for pasting.

The routines used for copying `execute_copy_command` is not specific to a system clipboard, unlike pasting, which uses a library and imports XCB. That is why it doesn't work, because the logs are from a library not a specific program error.

**Comment by aome510** [comment]
ahhh, my bad. Will see if there is a way to fix this with the `copypasta` library.

**Comment by apprehensions** [comment]
Yay

**Comment by aome510** [comment]
https://github.com/alacritty/copypasta has support for wayland but it's pretty limited (require window pointer for clipboard access). #411 replaces use of library with `paste_command` (similar to `copy_command`), so you should be able to define custom one for your use case

**Comment by apprehensions** [comment]
It does not function:
```
2024-04-19T07:49:17.303701Z ERROR terminal_event{event=Key(KeyEvent { code: Enter, modifiers: KeyModifiers(0x0), kind: Press, state: KeyEventState(0x0) })}: spotify_player::event: Failed to handle event: No such file or directory (os error 2)
```

**Comment by aome510** [comment]
Did you define a new `paste_command`? The default is `xclip`

**Comment by apprehensions** [comment]
What? You said the new library doesn't require that anymore, and is automatic.

**Comment by apprehensions** [comment]
Wait. Now I'm confused, earlier it was using this library which was automatic? Why did it need a command then..?

**Comment by aome510** [comment]
I didn't say anything about using library and is automatic. I did say 

> [the PR] replaces use of library with paste_command (similar to copy_command), so you should be able to define custom one for your use case

Library supports `wayland` but is limited and not easy to integrate to the application

**Comment by apprehensions** [comment]
Sorry for the misunderstanding, and that is very unfortunate. I've scoured all over GitHub for any other suitable clipboard libraries and it seems there isn't. Don't get me wrong, using the `copy_command` and `paste_command` approach is acceptable, but it's very inconvenient for your users, including myself.

Programs such as helix have many many checks for a suitable clipboard provider, and yazi executing all clipboard providers for a suitable one. I suggest you take the helix approach (seen [here](https://github.com/blaggacao/helix/blob/master/helix-view/src/clipboard.rs#L59)). Again, it is very unfortunate Rust does not have a universal clipboard :(

**Comment by aome510** [comment]
Thanks for the suggestion. I'll think about what is the best way to handle this

**Comment by aome510** [comment]
@apprehensions implemented in #421. Can you try the latest `main`?

**Comment by apprehensions** [comment]
You might want to consider running some of these commands in the background, running `wl-copy` causes spotify_player to freeze because `wl-copy` needs to run in the background.

**Comment by apprehensions** [comment]
Scratch that, i'm not sure why this doesn't work, but it should.

I have this same issue with my editor and i don't know why.

**Comment by aome510** [comment]
Not sure what happened. I don't have linux machine, so couldn't really test the change myself. I do think that I implemented the command spawning logic similar to `helix`
