### ISSUE TITLE
List Que?

### ISSUE THREAD

**Issue by TheGassyNinja** [aome510/spotify-player#396]
First THANK YOU for this project! I live in this app and is a MUST for all of my machines. It functions well and I can theme it decently. 

I have been working on a few scripts that give me a current system status and I have no problem getting what is currently playing BUT I would like a list of what is in my que. I want to show the next 5-10 songs in my script or show them with a popup Conky.
I am not understanding the 'spotify_player get' command. I think that this is where I can 'get' the info I'm looking for.

Can you point me in the right direction?

**Comment by aome510** [comment]
`spotify_player get key queue` will give you a list of next 20 songs in queue. See `spotify_player get key -h`.  When running the UI, you can view the queue with `Queue` command (default bind: `z`).
