### ISSUE TITLE
Incredible! Thank you! 😄👍🏼

### ISSUE THREAD

**Issue by nicobrenner** [aome510/spotify-player#397]
I just installed `spotify_player` on my Mac, and it's such a delight

The official app for Mac always freezes and is super slow

This app on the other hand, is such a wonderful experience to use

Very grateful for everyone that has made this possible

Looking forward to using this app for many years to come

**Comment by diegoulloao** [comment]
> I just installed `spotify_player` on my Mac, and it's such a delight
> 
> The official app for Mac always freezes and is super slow
> 
> This app on the other hand, is such a wonderful experience to use
> 
> Very grateful for everyone that has made this possible
> 
> Looking forward to using this app for many years to come

exactly, sometimes I just wish to have vim key shortcuts 🤩
