### ISSUE TITLE
Glitchy image album cover image behavior in kitty Mac OS

### ISSUE THREAD

**Issue by fuzetsu** [aome510/spotify-player#399]
**Describe the bug**
Album cover image rendering is glitchy in kitty (the terminal app) running on Mac OS:
- image is stretched
- image dupes and stacks at bottom left of the screen when you navigate to help screen `?`

Of note is that this works fine in iterm2 (and maybe most terminal emulators?) 
I suppose this might be a bug in kitty? difference in how images are cleaned up between screens?

**To Reproduce**
Open any song with album art and notice image is stretched. Press `?` to open help screen and 

**Expected behaviour**
Image should appear and disappear as expected and should be scaled appropriately. 

**Screenshots**
<img width="174" alt="image" src="https://github.com/aome510/spotify-player/assets/848652/7051d7fc-d791-469e-817e-e879737c70f9">

**Environment**

- OS: MacOS 14.3.1
- Application version: 0.17.1
- Kitty version: 0.33.1

**Comment by aome510** [comment]
@fuzetsu thanks for reporting. Can confirm this issue also happens to me with `image` on `iterm2`. I didn't notice this issue as I don't use `?` for help page anymore 😅 .

**Comment by aome510** [comment]
Should be fixed with #400. Can you try the latest `master`?

**Comment by fuzetsu** [comment]
Thanks! Tried out latest `master` but now I'm seeing no image at all (in all terminals). 

I just cloned the repo and used `cargo run`.

**Comment by aome510** [comment]
> Thanks! Tried out latest `master` but now I'm seeing no image at all (in all terminals).
> 
> I just cloned the repo and used `cargo run`.

should be `cargo run --features image`.

**Comment by fuzetsu** [comment]
Just saw that 🤦 

Thanks!

**Comment by fuzetsu** [comment]
Main bug seems to be fixed now!

Images are still a bit squeezed in kitty though, I'm now thinking it might be a config issue on my side though because of line height 🤔

![image](https://github.com/aome510/spotify-player/assets/848652/5a0cc91c-4847-43a6-84fe-81484d121fa7)

**Comment by fuzetsu** [comment]
Hmm, yeah looks fine with other fonts. My problem then I guess 😆 
![image](https://github.com/aome510/spotify-player/assets/848652/4d7d32cc-a87d-449c-bff4-2bbad617c308)

**Comment by n-ameless** [comment]
![image](https://github.com/aome510/spotify-player/assets/134816182/b10f4ba3-633a-43b9-a1aa-43f31ac68a0f)
![image](https://github.com/aome510/spotify-player/assets/134816182/bacac48f-0ef2-4921-9b27-c12992d33fac)
still occuring on 0.17.2 for me

**Comment by aome510** [comment]
> ![image](https://private-user-images.githubusercontent.com/134816182/319473998-b10f4ba3-633a-43b9-a1aa-43f31ac68a0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzUzNDAsIm5iZiI6MTcxMjIzNTA0MCwicGF0aCI6Ii8xMzQ4MTYxODIvMzE5NDczOTk4LWIxMGY0YmEzLTYzM2EtNDNiOS1hMWFhLTQzZjMxYWM2OGEwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQxMjUwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTY2NGEzYWMxNDFmMzY4ZTkxMmYxYzIwNGM4YTk1NzYzZjQ5OWYyZDEzZDgzNzgwNWQ0OWU2MDBhMzEzNDBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9imLuDbKEQ7TshG4mVsiwMq1kUwQ9nTuHdeL3UR8Tik) ![image](https://private-user-images.githubusercontent.com/134816182/319474183-bacac48f-0ef2-4921-9b27-c12992d33fac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzUzNDAsIm5iZiI6MTcxMjIzNTA0MCwicGF0aCI6Ii8xMzQ4MTYxODIvMzE5NDc0MTgzLWJhY2FjNDhmLTBlZjItNDkyMS05YjI3LWMxMjk5MmQzM2ZhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQxMjUwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDdhOTdkOTM5ZDRkOTU1ZGU0YjliOWFjNjE0ZTAxZDZkYTM1NmEwNTQ0NzAxY2QxZTZjMDFmNTQ4NjlmYjg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V0myXnyGXxw8zt8WNmR5ZGyBXRqu9O3rgeMs-3jDJbY) still occuring on 0.17.2 for me

Is this behaviour consistent? What terminal are you using?

**Comment by n-ameless** [comment]
This behavior is consistent on Kitty terminal on NixOS. Using latest kitty and spotify-player on nixpkgs unstable.

**Comment by icep0ps** [comment]
I was having the same problem, I kind of fixed this by setting adding the following to the app.toml

```
cover_img_length = 12
cover_img_width = 5
```

**Comment by diegoulloao** [comment]
> I was having the same problem, I kind of fixed this by adding the following to the app.toml
> 
> ```
> cover_img_length = 12
> cover_img_width = 5
> ```

same issue, it depends of the line height you're using, you can play with the `cover_img_length` value till the image is squared
