### ISSUE TITLE
MPRIS support?

### ISSUE THREAD

**Issue by alosarjos** [aome510/spotify-player#40]
Hi there! Just found this project. It looks great! Congratulations on it.

Do you plan on adding MPRIS support so it can be controlled with media keys on Linux?

**Comment by aome510** [comment]
Yeah, it was on the roadmap :). However, I'm using MacOS now so MPRIS doesn't really work 😢 for me.

If there are many people requesting this feature, I can implement one. 

For now, I guess you can use `spotify_player` as a [remote player](https://github.com/aome510/spotify-player#spotify-connect) to control another client, such as Spotify official client or [`spotifyd`](https://github.com/Spotifyd/spotifyd). then the media keys should work.

**Comment by alosarjos** [comment]
I've been using [spotiyd](https://github.com/Spotifyd/spotifyd) + [spotify-tui](https://github.com/Rigellute/spotify-tui) for some time, but there are some issues with spotifyd, and the repo looks like it's dying...

**Comment by aome510** [comment]
Oh, thanks for the context, you mean `spotify-tui` is dying? I can still see some active developments with `spotifyd`

**Comment by alosarjos** [comment]
No, I meant `spotifyd`.  Some periodic commit bursts on master, which I guess are some MR being checked from time to time. Milestones haven't changed in 3 months...

**Comment by elkrien** [comment]
Definitely MPRIS support would be great. For now I use playerctl to control my players by my bar and for now I need to use ncspot because of this. I really like spotify-player and that's the only way that keeps me with ncspot for now :( Please implement MPRIS...

**Comment by alosarjos** [comment]
That crate looks promising. If you need someone to test the MPRIS on Linux just mention me whenever it's on a branch and will give it a try ;)

**Comment by aome510** [comment]
@alosarjos @elkrien I have added the cross-platform media control support. Can you try it out by running the latest build from the `master` branch:

```sh
git clone https://github.com/aome510/spotify-player.git && cd spotify-player
cargo run
```

I have tested the support on MacOS and briefly on Ubuntu 22.04, but couldn't test it on Windows.

**Comment by alosarjos** [comment]
Tested on Arch Linux with Gnome. Looks good to me. Multimedia keys work. Control from the MPRIS notification work. The media info changes correctly. Looks great!!!

**Comment by elkrien** [comment]
Tested on Arch Linux + LeftWM. Works great without any problems :)
I'm not able to test on Windows.

**Comment by aome510** [comment]
Thanks guys 🙇
