### ISSUE TITLE
Opening and closing pop up messes up the UI

### ISSUE THREAD

**Issue by m-torhan** [aome510/spotify-player#403]
**Describe the bug**
After opening a pop up and closing it the UI is messed up. Doing it couple times make is even worse. After resizing terminal window, the UI is fixed.

**To Reproduce**
1. Run `spotify_player`
2. Open pop up (i.e. queue or help)
3. Close it
4. UI is messed up

**Expected behaviour**
UI looks like before opening pop up.

**Screenshots**
![Screenshot from 2024-03-25 13-05-30](https://github.com/aome510/spotify-player/assets/38363382/a643c902-9531-4e7b-b494-e6e994542d94)
![Screenshot from 2024-03-25 13-05-37](https://github.com/aome510/spotify-player/assets/38363382/0c725133-3729-42eb-a0f9-082517cdc429)
![Screenshot from 2024-03-25 13-05-37](https://github.com/aome510/spotify-player/assets/38363382/d4fa316b-991a-4128-98ae-12ea7ff4b3db)
Without sixel:
![Screenshot from 2024-03-25 13-05-44](https://github.com/aome510/spotify-player/assets/38363382/20e6acf5-adda-4376-8d79-51609eb6b72d)
![Screenshot from 2024-03-25 13-05-46](https://github.com/aome510/spotify-player/assets/38363382/77775f5a-8111-4b51-93a7-6792fd7b6273)
![Screenshot from 2024-03-25 13-05-49](https://github.com/aome510/spotify-player/assets/38363382/41cdfe60-624a-409f-8d26-8d1373bcf9ef)

**Environment**

- OS: arch-linux
- Application version: 0.17.1
- Application features: `--no-default-features --features sixel,lyric-finder,media-control,image`

**Note**
This issue does not reproduce on v0.17.0.

**Comment by aome510** [comment]
It should be fixed with #400. Can you check the latest main? Related #399
