### ISSUE TITLE
Unable show album cover in tmux.

### ISSUE THREAD

**Issue by xbunax** [aome510/spotify-player#404]
+ Unable show album cover in tmux. Left is `tmux`, right is `iterm2`

![image](https://github.com/aome510/spotify-player/assets/50800571/4a1a81a6-0d6c-4483-a999-008180220a6a)

+ I don't know wether this is the problem of `spotify_player` or the `tmux`. Like the [issue](https://github.com/ranger/ranger/issues/539)

+ This is my system info
```
                    'c.          xbunax@MacBook-Air-3.local
                 ,xNMM.          --------------------------
               .OMMMMo           OS: macOS 14.4.1 23E224 arm64
               OMMM0,            Host: Mac14,2
     .;loddo:' loolloddol;.      Kernel: 23.4.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 12 hours, 46 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 1 (port), 238 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.9
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 2560x1440
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Amethyst
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: iTerm2
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal Font: MesloLGS-NF-Regular 14
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Apple M2
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Apple M2
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 2950MiB / 16384MiB
       .cooc,.    .,coo:.
```
+ the version of `spotify_player`
```
spotify_player 0.17.1
```

**Comment by aome510** [comment]
I believe it's `tmux` issue. I remember some terminal emulators, e.g `tmux` or `allacrity`, don't support rendering full-resolution images. That said, it's weird to not see anything rendered. What does the image area look like if running `tmux` inside other terminals than `iterm2`?

**Comment by xbunax** [comment]
> I believe it's `tmux` issue. I remember some terminal emulators, e.g `tmux` or `allacrity`, don't support rendering full-resolution images. That said, it's weird to not see anything rendered. What does the image area look like when running `tmux` inside other terminals than `iterm2`?

<img width="955" alt="image" src="https://github.com/aome510/spotify-player/assets/50800571/77c08f67-8ed0-4825-86c5-4911844cf6fa">

I use `kitty` to run `tmux`, but the result is the same

**Comment by Keep-Simple** [comment]
+1

**Comment by mdkcore0** [comment]
> I believe it's `tmux` issue. I remember some terminal emulators, e.g `tmux` or `allacrity`, don't support rendering full-resolution images. That said, it's weird to not see anything rendered. What does the image area look like when running `tmux` inside other terminals than `iterm2`?

as aome510 said, it depends on your terminal emulator and tmux; for example, alacritty do not support sixel (there is a build that do enable that), and tmux needs to be compiled with the `--enable-sixel` flag (was added on version 3.4)

finally, spotify-player must be built with image or sixel enabled, maybe this is the issue you are facing here

this is what it looks likes with the image feature enabled, running on alacritty/tmux (catppuccin-mocha btw? :p): 
![image](https://github.com/aome510/spotify-player/assets/1218078/b5ad7aaf-6e3a-499e-9790-682c82d5e88a)

**Comment by xbunax** [comment]
> --enable-sixel

Interesting, I build `tmux` and `spotify_player` with image feature, but the image still disappear wether it's in `iterm2` or `kitty`
<img width="1462" alt="image" src="https://github.com/aome510/spotify-player/assets/50800571/6924897b-0bb5-44b8-b01e-7f54ba9a005d">

**Comment by aome510** [comment]
I think `tmux` doesn't support render image in full resolution, image is still rendered when running in terminal that doesn't support full resolution based on @mdkcore0's comment. My guess is that the terminal renders full-resolution image but tmux doesn't know how to handle the image, so it just renders a black screen.

I'll close this issue for now as I'm not sure if there is anything we can do from `spotify_player` side

**Comment by CalebAnders** [comment]
i hate to open a closed issue but i did want to comment that [yazi](https://github.com/sxyazi/yazi) can render full images inside of tmux, whereas i too am getting a blank image with iTerm2 and tmux in spotify_player.

**Comment by funkycode** [comment]
using kitty with tmux - the spotify_player will hang if setting `TERM` to `xterm-kitty`, while if using `tmux-256color` it does work but no image support.
while kitty does show properly images inside tmux with no issues.
![image](https://github.com/user-attachments/assets/0c621471-7499-4daa-a2f9-650f249d75e8)

**Comment by mirai-ux** [comment]
same issue as @funkycode 
set -g default-terminal "xterm-kitty"
![image](https://github.com/user-attachments/assets/06eb54fe-f465-4a70-8aa2-b1e590834385)

set -g default-terminal "tmux-256color"
![image](https://github.com/user-attachments/assets/53451103-c8c4-4754-8084-7f59acc9355a)
