### ISSUE TITLE
Control + S doesnt set to Shuffle

### ISSUE THREAD

**Issue by dbt0815** [aome510/spotify-player#406]
**Describe the bug**
Title says it.

**To Reproduce**
Press C+s

**Expected behaviour**
should start shuffle mode

**Environment**

- OS: Arch
- Application version: latest
- Application features: 

**Additional context**
maybe the problem is in front of the screen

edit: the problem was indeed in front of the screen.

**Comment by aome510** [comment]
Hi @dbt0815, following up, can you provide more details? Otherwise, I'll close this issue

**Comment by dbt0815** [comment]
can you read the edit?

**Comment by aome510** [comment]
Yes, but "in front of the screen" is very vague. Like I already mentioned w/o logs, backtraces, or pictures, I couldn't understand the issue.
