### ISSUE TITLE
Incorrect Playlist Order in Library

### ISSUE THREAD

**Issue by PuffyDucks** [aome510/spotify-player#408]
**Describe the bug**
The playlist order on the library page is out of order. Before it would show your custom playlist order, but now its somewhat seems like recent order? I'm not sure because some of my old playlists show up at the top. 

**To Reproduce**
Open the library page and compare the order of the playlists to the order of the playlists on the Spotify app. 

**Additional context**
I'm guessing Spotify did another one of their wacky API changes. Is it even fixable without action from Spotify?

**Comment by aome510** [comment]
I noticed the out of order occasionally depending on the day, but it's not consistent. Today, my library shows order by **recents**. Will try to see if there is an option to sort the playlist by **recents** to make the order more consistent

**Comment by PuffyDucks** [comment]
Looks like Spotify has fixed the issue in the API.
