### ISSUE TITLE
Add option to disable album art and reduce header height

### ISSUE THREAD

**Issue by rolanday** [aome510/spotify-player#409]
**Is your feature request related to a problem? Please describe.**
Album are is highly pixelated when used inside a tmux session, which I assume it limitation of tmux and not a Spotify-player issue (see attached). Regardless, I run the player inside a split window at bottom of my terminal (Neovim above) and the window is relatively short in height. The screenshot shows the player in area reserved for it w/o needing to compromise my preferred overall window sizing (just two lines for playlists to appear and a lot of dead space above).

<img width="450" alt="Screenshot 2024-04-10 at 8 51 54 PM" src="https://github.com/aome510/spotify-player/assets/3402123/9536e4ba-a408-4bc9-a2ae-55791b73b297">

**Describe the solution you'd like**
 I don't need or care for the album are and would like an option to change the header height so there is more room for browsing files, etc., in the lower part of player app.

**Describe alternatives you've considered**
Simply trade-off editor space to make more room for libraries, playlists , etc.

**Additional context**
Thank you for spotty_player! It completes me :0)

**Comment by aome510** [comment]
Album image is not the default feature. How did u install `spotify_player`? If installed via `cargo install spotify_player` for example, album art should not be included

**Comment by rolanday** [comment]
Hi @aome510 , I brew installed it using `brew install spotify_player`.  I didn't find anything in the [config doc](https://github.com/aome510/spotify-player/blob/master/docs/config.md) indicating covert art can be disabled, but sounds like possible -- can you please share details.

 I didn't try changing cover are size go 1x1 . which reduce the size, but didn't affect header height -- which is main thing  I'm after of possible. It's a nice to have for me so just checking, otherwise just very happy that this app exists! Thank you again.

**Comment by aome510** [comment]
@rolanday thanks for the kind words ❤️ . Glad to hear that you enjoy using my project.

> I brew installed it using brew install spotify_player. I didn't find anything in the [config doc](https://github.com/aome510/spotify-player/blob/master/docs/config.md) indicating covert art can be disabled, but sounds like possible -- can you please share details.

Brew package includes some additional features such as `image`, `lyric-finder`, `notify`, etc. Those features are not runtime feature, so disable using configs is not supported. If you have [`cargo`](https://doc.rust-lang.org/cargo/getting-started/installation.html#install-rust-and-cargo) installed, you can install the "vanilla" application using `cargo install spotify_player` command. 

Also what do you mean by header height?

**Comment by aome510** [comment]
If you want the playback window to be vertically smaller. You can set `playback_window_width` to a smaller value.

**Comment by rolanday** [comment]
@aome510 , yes, playback window is the better term. ty, and I'll give it (and vanilla version) a try. Thanks again, and  you should add a buy me a coffee link!

**Comment by aome510** [comment]
Great! Will close this issue for now. Feel free to reopen it if you encounter any similar issue.

I don't really care about donations. I would prefer people to contribute back to the project if they enjoy using it!

**Comment by rolanday** [comment]
> Great! Will close this issue for now. Feel free to reopen it if you encounter any similar issue.
> 
> I don't really care about donations. I would prefer people to contribute back to the project if they enjoy using it!

@aome510 , works like a charm /w the cargo installer ver and changing window with value. Thank you!!
