### ISSUE TITLE
Ask confirmation before quiting

### ISSUE THREAD

**Issue by miguelbarao** [aome510/spotify-player#412]
**Is your feature already implemented in the latest `master`?**
Not implemented.

**Is your feature request related to a problem? Please describe.**
I tend to use `q` to close a window, but it immediately quits the application and stops playing. This is frustrating.

**Describe the solution you'd like**
Asking for confirmation before quitting could prevent this.

**Comment by aome510** [comment]
it might be better for you to re-bind `q` to `ClosePopup` and use another shortcut to quite the app

**Comment by miguelbarao** [comment]
Thanks for the suggestion. This solves it.
