### ISSUE TITLE
Insert whitespace into `playback_format`

### ISSUE THREAD

**Issue by apprehensions** [aome510/spotify-player#416]
**Is your feature request related to a problem? Please describe.**
The image needs to be at an abnormal scale to be rendered properly, and is rendered above the playback text.

**Describe the solution you'd like**
Allow whitespace to be rendered in `playback_format`

**Describe alternatives you've considered**
Not using images

**Additional context**
![image](https://github.com/aome510/spotify-player/assets/47404953/4520524a-25b7-4bb5-a0bf-e8243904e308)
Above image is configured with
```toml
playback_format = "                         {track}\n     {artists} - {album}\n{metadata}"
```

**Comment by aome510** [comment]
> The image needs to be at an abnormal scale to be rendered properly, and is rendered above the playback text.

Is this `sixel`? WDYM by "rendered properly", e.g do you want to the image to be closer to the progress bar vertically?

**Comment by apprehensions** [comment]
Thanks cutie
