### ISSUE TITLE
Daemonize device ?

### ISSUE THREAD

**Issue by midnightexigent** [aome510/spotify-player#42]
Currently whenever we leave the TUI, music stops playing. It would be better if music kept playing in the background. 

Is such a feature in the roadmap ?

**Comment by midnightexigent** [comment]
Actually after looking a bit further into this, I noticed that librespot itself is already a pretty feature-complete device/daemon. Is there any reason spotify-player needs to wrap and be a device itself ? Can't it just be a tui client ?

**Comment by aome510** [comment]
> Currently whenever we leave the TUI, music stops playing. It would be better if music kept playing in the background.

So `spotify-player` is made to be a TUI alternative to official Spotify app. Similar to the Spotify app, if you start streaming music there, quit the app will stop playing the music.

> Is such a feature in the roadmap ?

Not in a roadmap atm, but add a `--daemon` option should be trivial and it will become handy when [media control support](https://github.com/aome510/spotify-player/issues/40) is implemented. Without that, there is no point of running the app as a daemon as the only thing you can do with it is play music, e.g cannot toggle play/pause, next, prev, etc.

**Comment by jesyspa** [comment]
As an alternative here: spotifyd already works as a spotify daemon, and by setting default_device I can automatically play from that.  It would be nice if I could disable the spotify_player device entirely, since in such a setup I never want to play from it.

**Comment by aome510** [comment]
>  It would be nice if I could disable the spotify_player device entirely, since in such a setup I never want to play from it.

You can disable the integrated client entirely by building the app without `streaming` feature (included as default features). One way to do it is:

```
cargo install spotify_player --no-default-features
```

**Comment by aome510** [comment]
>  It would be nice if I could disable the spotify_player device entirely, since in such a setup I never want to play from it.

You can disable the integrated client entirely by building the app without `streaming` feature (included as default features). One way to do it is:

```
cargo install spotify_player --no-default-features
```

**Comment by jesyspa** [comment]
Thanks, that's good to know.  It would be a bit of a hassle to compile manually (I'm using the AUR package right now).
If you're open to it, I could put together a patch that adds this as a configuration option?  Or is there something that makes that difficult to implement?

**Comment by jesyspa** [comment]
Cool, I'll take a look this weekend!
`default_device` does work, but I often have two or more spotify_players open (my workflow involves multiple X sessions on one machine), and the list gets quite long which makes it a hassle if I e.g. want to switch the audio to my phone.  So it's a minor thing, really.

**Comment by aome510** [comment]
> default_device does work, but I often have two or more spotify_players open (my workflow involves multiple X sessions on one machine), and the list gets quite long which makes it a hassle if I e.g. want to switch the audio to my phone

Look forward to your PR! Just a note that there is `SwitchDevice` command that allows you to transfer the playback to another device in case u may miss it.

**Comment by cheyngoodman** [comment]
This feature could help `spotify-player` replace [`spotifyd`](https://github.com/Spotifyd/spotifyd). It seems extremely useful when combined with [CLI commands](https://github.com/aome510/spotify-player/pull/159).

With both features, `spotify-player` ould completely replace my `spotifyd`+`spotify-tui` workflow.

**Comment by aome510** [comment]
@cheyngoodman in case u may miss, you don't need a "spotifyd+spotify-tui" kind of workflow with `spotify-player` as the app itself has an integrated Spotify client for streaming, so you don't need another client like `spotifyd`.

I think the daemon device is only good when you use with the CLI app to control the music **without an UI**. Is that what you means by your "spotifyd+spotify-tui" workflow?

**Comment by cheyngoodman** [comment]
Right, I wish to use the UI for browsing or managing playlists occasionally, but I'm mostly playing music without the interface.

I'm hoping to completely replace `spotify-tui` with `spotify_player` for controlling the music without a UI. Then, if possible with this daemon feature I can also replace `spotifyd` with `spotify_player`.

I'm getting close to my preferred workflow with `spotifyd` for playing without UI + `playerctl` for controlling + `spotify_player` for browsing. It's almost perfect but `playerctl` cannot like/unlike and struggles with volume.

I'm hoping `spotify_player` replace all the spotify related apps I use.
