### ISSUE TITLE
Crashing on startup on Linux Mint

### ISSUE THREAD

**Issue by vitorcsantos** [aome510/spotify-player#424]
Hello, I have been using the application with no problems on my Windows machine, but when I tried running it on Linux just now, it encountered a problem and hangs on a blank terminal after launch. It launched "properly" once, with the message about setting up the Spotify connect properly, but it became unresponsive. I closed it and relaunched, and now it hangs/crashes 100% of the time. Looking into the logs, I found this excerpt on the backtrace (that Github doesn't let me upload so I'll copy and paste what I believe is the relevant part:

`Got a panic: PanicInfo {
    payload: Any { .. },
    message: Some(
        byte index 31 is not a char boundary; it is inside '殻' (bytes 30..33) of `GHOST IN THE SHELL Series -攻殻機動隊シリーズ- • Spotify`,
    ),
    location: Location {
        file: "/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.26.2/src/text/line.rs",
        line: 477,
        col: 59,
    },
    can_unwind: true,
    force_no_backtrace: false,
}`

From what it looks like, the japanese characters in one of my saved playlists caused it to break. Attached below is the log file from that same execution, hopefully it is helpful in finding the solution. 
[spotify-player-24-04-22-09-06.log](https://github.com/aome510/spotify-player/files/15062690/spotify-player-24-04-22-09-06.log)

- OS: Linux Mint Cinnamon
- Application version: v0.18.0

**Comment by vitorcsantos** [comment]
Yup, trying on v0.17.2 got it working correctly again, no issues in loading or playing that playlist. Now I noticed you updated 0.18 just yesterday, I think my Windows version might also be on 0.17.2 and didn't show that same error. I'm going to try downloading the latest and see if it also breaks there.

**Comment by aome510** [comment]
Should be fixed in [`v0.18.1`](https://github.com/aome510/spotify-player/releases/tag/v0.18.1)

**Comment by joshka** [comment]
The Ratatui bug for this is https://github.com/ratatui-org/ratatui/issues/1032
