### ISSUE TITLE
Search from CLI

### ISSUE THREAD

**Issue by davepgreene** [aome510/spotify-player#425]
**Is your feature already implemented in the latest `master`?**
No

**Is your feature request related to a problem? Please describe.**
Right now the current method for getting search-like information from Spotify via the CLI is to use `spotify_player get item <TYPE> --name`. Unfortunately this only returns a single result rather than the list of results that the TUI returns when searching. 

**Describe the solution you'd like**
A new CLI command called `search` which allows users to do the same kind of search that the TUI does.

**Describe alternatives you've considered**
N/A

**Additional context**
From poking through the codebase (I'm not super familiar with Rust so I'm sure I've missed something here) it looks like the CLI does item retrieval calls out directly to the `artist`, `track`, `playlist`, and `track` methods in rspotify.  Would it be too much work to wire up the `search` method as well?

**Comment by kadinsayani** [comment]
Hi, I'd like to give this a try if that's okay with you? Thanks!

**Comment by aome510** [comment]
yes, please do. Lmk when you have a PR up
