### ISSUE TITLE
Spotify_player plays over internal speaker and not HDMI

### ISSUE THREAD

**Issue by mrfatboy** [aome510/spotify-player#437]
I have spotify_player running on a MacMini 2012 under Ubuntu 22.04.  Spotify-Player and my computer name show up in the device list. When either is selected, the music is played through the mac mini's internal speaker and not out through the hdmi port like the other apps that I am running.

Is there a way to configure which audio out that the local spotify-player uses?

**Comment by aome510** [comment]
Can you share the log and provide with features you use to build the app? With the default audio backend (`rodio`), I'm pretty sure that music will be played from the current device the system uses. In other words, it should be the same as other apps. 

> Is there a way to configure which audio out that the local spotify-player uses?

No, audio is handled by a third-party library. The app itself is not responsible for low-level audio handling.

**Comment by mrfatboy** [comment]
Let me do some more investigating and I will get back to you tomorrow.

**Comment by mrfatboy** [comment]
I found the problem. It was my issue. Please mark this as closed.
