### ISSUE TITLE
Can't connect to my Spotify account 

### ISSUE THREAD

**Issue by adityjoshi** [aome510/spotify-player#445]
When I am entering my username client_id and password with client_secret it is showing error. Please help
<img width="1057" alt="Screenshot 2024-05-04 at 11 00 23 AM" src="https://github.com/aome510/spotify-player/assets/111140014/038c6311-4d1e-4c4e-8f38-08a0a2351a3b">

**Comment by aome510** [comment]
Username/password is your Spotify’s username/password not client secret and id

**Comment by adityjoshi** [comment]
Thank You for the help.
