### ISSUE TITLE
Binary AUR package?

### ISSUE THREAD

**Issue by nathanielevan** [aome510/spotify-player#450]
First off, many thanks for spotify-player, it's been serving me well so far. That said, I'm still using a relatively old ThinkPad so compile times aren't insignificant -- would greatly appreciate it if a binary AUR package is made available similar to `spotify-tui-bin`. I understand the need for individual users to customise their compiled build, but that will still be covered by the original package or through manual compile, so this request shouldn't change that.

**Comment by aome510** [comment]
another option would be downloading the binary directly in https://github.com/aome510/spotify-player/releases/tag/v0.18.1

**Comment by blackthorne7** [comment]
@nathanielevan do you have a specific audio backend in mind?

**Comment by nathanielevan** [comment]
@aome510 Right, apologies for not checking the releases directly. Though, that said, I'd love to be able to update it along with other programs I have installed with pacman.

@blackthorne7 The features and audio backend that come compiled with the standard `spotify-player` AUR package serve my needs just fine, so I think I just need the same thing but precompiled. Would greatly appreciate your assistance. :)

**Comment by aome510** [comment]
Just a note that this project doesn't handle/mantain any external packaging (AUR, homebrew, etc). I'll close this issue for now.
