### ISSUE TITLE
Title overflows when too long

### ISSUE THREAD

**Issue by apprehensions** [aome510/spotify-player#454]
**Describe the bug**
When listening to a song with a long name, the name overflows to the the album cover & metadata

**To Reproduce**
Listen to a song with a long title, such as 't​á​lcunnana d​ë​hajma tun dejl b​ë​natsë abcul​’​han dlhenic ëlh inagat, jahadlhë adrhasha indauzgl​ë​n nu dlhevusao ibajngra nava l​í​eshtamhan ëf novejhan conetc dan​ë​ctc qin, ëf tu dlhicad​ë​trh​ë​nna bë ablhundrhaba judjenan alh​ë​tangrasë shidandlham​ë​së inqom' by Trhä

**Expected behaviour**
The song title doesn't overflow everywhere.

**Screenshots**
![image](https://github.com/aome510/spotify-player/assets/47404953/f8bb19fd-2e03-44bf-9b9d-e3bdcdfd376b)

If listened to another song,
The previous album cover appears (no song played previously):
![20240525_222926](https://github.com/aome510/spotify-player/assets/47404953/f95d9775-9b4a-442f-aecb-82afeb0b401b)
Default app.toml:
![image](https://github.com/aome510/spotify-player/assets/47404953/f43bd350-69bc-4a60-9e01-9d7dbce7160b)

**Comment by cwillsey06** [comment]
😭

**Comment by aome510** [comment]
can you fix this issue by increasing `playback_window_width`?

**Comment by apprehensions** [comment]
`playback_window_width` **Shouldn't** be an option, and it isn't. There is nothing next to the playback window.

**Comment by aome510** [comment]
`playback_window_width` actually is a quite confusing naming. `width` here refers to the vertical spaces and I thought if you increase the vertical spaces then overflowing is not an issue anymore?

**Comment by apprehensions** [comment]
The option you're talking about was removed in 2030b4ee94d1f7a4b6cb64d7fa56aa5336f3414e.

**Comment by apprehensions** [comment]
Here's something interesting:
```
Error: Failed to initialize the Spotify data

Caused by:
    Filename too long (os error 36)
```
```
open("/home/sewn/.cache/spotify-player/image/t\303\241lcunnana d\303\253hajma tun dejl b\303\253nats\303\253 abcul\342\200\231han dlhenic \303\253lh inagat, jahadlh\303\253 adrhasha indauzgl\303\253n nu dlhevusao ibajngra nava l\303\255eshtamhan \303\253f novejhan conetc dan\303\253ctc qin, \303\253f tu dlhicad\303\253trh\303\253nna b\303\253 ablhundrhaba judjenan alh\303\253tangras\303\253 shidandlham\303\253s\303\253 inqom-Trh\303\244-cover-3E2sVJ.jpg", O_WRONLY|O_CREAT|O_TRUNC|O_LARGEFILE|O_CLOEXEC, 0666) = -1 ENAMETOOLONG (Filename too long)
```

**Comment by aome510** [comment]
> The option you're talking about was removed in [2030b4e](https://github.com/aome510/spotify-player/commit/2030b4ee94d1f7a4b6cb64d7fa56aa5336f3414e).

no it's renamed to `layout.playback_window_height`



> Here's something interesting:
> 
> ```
> Error: Failed to initialize the Spotify data
> 
> Caused by:
>     Filename too long (os error 36)
> ```
> 
>  ```
> open("/home/sewn/.cache/spotify-player/image/t\303\241lcunnana d\303\253hajma tun dejl b\303\253nats\303\253 abcul\342\200\231han dlhenic \303\253lh inagat, jahadlh\303\253 adrhasha indauzgl\303\253n nu dlhevusao ibajngra nava l\303\255eshtamhan \303\253f novejhan conetc dan\303\253ctc qin, \303\253f tu dlhicad\303\253trh\303\253nna b\303\253 ablhundrhaba judjenan alh\303\253tangras\303\253 shidandlham\303\253s\303\253 inqom-Trh\303\244-cover-3E2sVJ.jpg", O_WRONLY|O_CREAT|O_TRUNC|O_LARGEFILE|O_CLOEXEC, 0666) = -1 ENAMETOOLONG (Filename too long)
> ```

right, that's also an issue, so we also need to truncate the title when saving file

**Comment by apprehensions** [comment]
Why not save the file with it's spotify ID?

**Comment by apprehensions** [comment]
> no it's renamed to `layout.playback_window_height`

![20240804_191839](https://github.com/user-attachments/assets/44a47932-64c1-4fbf-a15c-74833afd9aff)

**Comment by aome510** [comment]
> Why not save the file with it's spotify ID?

because I think it's useful to be able to search the cover images using album's name or artist's name

**Comment by aome510** [comment]
> > no it's renamed to `layout.playback_window_height`
> 
> ![20240804_191839](https://private-user-images.githubusercontent.com/47404953/354914709-44a47932-64c1-4fbf-a15c-74833afd9aff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3ODg3MzcsIm5iZiI6MTcyMjc4ODQzNywicGF0aCI6Ii80NzQwNDk1My8zNTQ5MTQ3MDktNDRhNDc5MzItNjRjMS00ZmJmLWExNWMtNzQ4MzNhZmQ5YWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDE2MjAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNDUyNjM1ZDc4MjNhMWE1NTk5NDQ5NjVhNWNmZTVjMGJjYWZlNWE4Y2I5NDNmNjA2MTY2ODkyOTI1ODdjNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JdUfY8Slrqdt6_CpM6Xd5hnsQwsTNPKZrKG1SdwYBbs)

I see, is it because you use spaces in `playback_format` to add paddings? I think we should disable wrapping when rendering the playback data, then we can also have truncating for free.
