### ISSUE TITLE
Adjust playback speed functionality

### ISSUE THREAD

**Issue by jobvisser03** [aome510/spotify-player#465]
First-off, great piece of software, hats off!

It would be great if you could adjust the playback rate or speed of the song.

Spotify only supports this for podcasts, not music. 

There are extensions for the spotify web player that let you alter the playback speed like: [Spotify speed extension](https://github.com/intOrfloat/spotitySpeedExtension) These don't work when you play the song using Spotify Connect though.

So it would be great to have a parameter `--playback-speed` that let's you tweak how fast or slow the music is played.

**Comment by aome510** [comment]
Can you elaborate? What do you mean by "playback rate"?

**Comment by jobvisser03** [comment]
@aome510 sorry for being too brief. Updated the description.

**Comment by aome510** [comment]
Thanks @jobvisser03. I get what you mean now. I don't think it's possible to adjust streaming speed rate as Spotify doesn't officially support that feature.

**Comment by aome510** [comment]
Closed as it's not possible to implement by `spotify_player`
