### ISSUE TITLE
larger cover art picture

### ISSUE THREAD

**Issue by plasmoduck** [aome510/spotify-player#469]
How can I get a larger cover art picture?

I am using kitty and have played around with cover_img_scale and color_img_length etc. The image size increases but it cover the text of the playback window. Is there a way to move the text of the playback window to the right?

**Comment by aome510** [comment]
Have you tried `color_img_width`? An image's size can be tweaked with `color_img_length` and `color_img_width`.  `cover_img_scale` is **only needed** for engine that doesn't render the image nicely inside a pre-allocated rectangle like `sixel`.
