### ISSUE TITLE
[feature]: move cursor 10 lines down and up by pressing ctrl+d and ctrl+u respectively

### ISSUE THREAD

**Issue by diegoulloao** [aome510/spotify-player#470]
**Is your feature already implemented in the latest `master`?**
No

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Some editors like nvim and vim allows you to move the cursor 10 lines down by pressing `ctrl+d` and up by `ctrl+u`.
It would be cool to have this feature to move quickly throughout the list, playlist or search results.

**Comment by aome510** [comment]
It should already possible with `PageSelectPreviousOrScrollUp` and `PageSelectNextOrScrollDown`. You can configure the page size with `page_size_in_rows` config option.

**Comment by diegoulloao** [comment]
> It should already be possible with `PageSelectPreviousOrScrollUp` and `PageSelectNextOrScrollDown`. You can configure the page size with `page_size_in_rows` config option.

I mean, for vim/nvim users it would be great to do it using the `ctrl + d` and `ctrl + u` keybinding too.
Those two ways could live together. There are also other terminal applications that use the same keybindings to move around up and down. I'd be very nice to have it here too.

**Comment by aome510** [comment]
You can add bindings to ctrl+u and ctrl+d right?

**Comment by diegoulloao** [comment]
> You can add bindings to ctrl+u and ctrl+d right?

idk, it is possible? how?

**Comment by diegoulloao** [comment]
Great, I didn't know about this. Anyway I think it would be great to have these keymaps built-in the app.
