### ISSUE TITLE
Sixel album image is very small

### ISSUE THREAD

**Issue by OpenSauce04** [aome510/spotify-player#476]
**Describe the bug**
The image of the album of the currently playing song which appears in the "Playback" section is very small, as shown in the attached screenshot

**To Reproduce**
1. Compile with sixel support enabled
2. Play any song
3. Observe the bug 

**Expected behaviour**
The album cover should appear at the correct size as shown in the project readme

**Log and backtrace**
N/A

**Screenshots**
![image](https://github.com/aome510/spotify-player/assets/48618519/69f5c820-ffd1-4680-bd40-58c909c1c079)

**Environment**

- OS: Gentoo Linux
- Application version: 0.18.2
- Application features: image,media-control,pulseaudio-backend,sixel,streaming

**Additional context**
In the screenshot above, I am using Wezterm

**Comment by aome510** [comment]
Did u try `cover_img_scale` to make it bigger? See **notes** in https://github.com/aome510/spotify-player?tab=readme-ov-file#image

**Comment by OpenSauce04** [comment]
Ah, I was unaware of this setting. Thanks for the pointer
