### ISSUE TITLE
Zsh Album Cover Issues?

### ISSUE THREAD

**Issue by ninjada** [aome510/spotify-player#485]
only using default macos terminal. anyone had any luck with the config image settings for Zsh? tried a dozen combos with no luck, just a pixelated mess.

should i just switch to iterm2?

btw. thank you for this player, glad i stumbled upon it. been stuck bypassing the terrible mac app for ages with the also terrible web-player to get spatial audio and dreaming of something with this level of control.

**Comment by plasmoduck** [comment]
Try kitty or iterm2 and see if it works. Some terminals lack the support.

**Comment by Bi0s-Lain** [comment]
> Try kitty or iterm2 and see if it works. Some terminals lack the support.

how do you do that ?

**Comment by aome510** [comment]
> > Try kitty or iterm2 and see if it works. Some terminals lack the support.
> 
> how do you do that ?

If you have the app installed with [`image` feature](https://github.com/aome510/spotify-player?tab=readme-ov-file#image) and run it on iterm2 and kitty, then image should work out of the box
