### ISSUE TITLE
Bigger text size for playback pane.

### ISSUE THREAD

**Issue by plasmoduck** [aome510/spotify-player#486]
Is there a way to increase the font size in the playback area whilst keeping the same smaller font size for the rest of the program?

**Comment by aome510** [comment]
No I don't think it's possible. AFAICT, [the `ratatui` library](https://github.com/ratatui-org/ratatui) `spotify_player` uses for rendering doesn't support changing the terminal's font size.

Maybe you can raise this to `ratatui` team instead to see if they can add such feature.

**Comment by joshka** [comment]
The terminal font-size is what it is. That's not something a terminal library can control as they render characters to cells, not pixel. I wrote a [tui-big-text](https://crates.io/crates/tui-big-text) crate for using 8x8, 4x4 etc. cells to write to the display to get around this a little, but that might be too big for this.
