### ISSUE TITLE
Play icon always attached to {track} value

### ISSUE THREAD

**Issue by aNNiMON** [aome510/spotify-player#487]
**Describe the bug**
I'd like to change a playback format so that the artists are followed by the track title. However, the playback icon is attached to a track title.

**To Reproduce**
1. Change `playback_format`:
    ```toml
    playback_format = """
    {artists} – {track}
    {album}
    {metadata}"""
    ````
2. Restart the app

**Expected behaviour**
Playback icon should be at the start of the line, before the artists.

**Actual behaviour**
Playback icon attached to the track title

![image](https://github.com/aome510/spotify-player/assets/1321838/e566ef1f-bd4a-4433-a7c0-ba07ac91efd4)

**Environment**
- OS: Windows 11
- Application version: 0.18.2

**Comment by JadonBelair** [comment]
seems simple enough, i could take a crack at this
