### ISSUE TITLE
Good repository

### ISSUE THREAD

**Issue by MAFLIXD** [aome510/spotify-player#490]
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug.

**Expected behaviour**

**Log and backtrace**
Log and backtrace of a run reproducing the bug to help debug the issue, which are usually located in `$HOME/.cache/spotify-player/`.

Please refer to [this URL](https://github.com/aome510/spotify-player?tab=readme-ov-file#logging) for more details.

**Screenshots**

**Environment**

- OS:
- Application version:
- Application features: if applicable, provide [cargo features](https://doc.rust-lang.org/cargo/reference/features.html) used to build `spotify_player`

**Additional context**

**Comment by aome510** [comment]
A bug indeed 😳
