### ISSUE TITLE
GetBrowseCategories - status code 502 bad gateway

### ISSUE THREAD

**Issue by japopich** [aome510/spotify-player#499]
**Describe the bug**
When pressing `g b` to get to the browse page I get an http error: status code 502 Bad Gateway in the log and a subsequent blank page in the application.

**To Reproduce**
Press `g b`

**Expected behaviour**
Open the spotify browse page

**Log and backtrace**
`2024-07-08T17:14:22.636700Z ERROR client_request{request=GetBrowseCategories}: spotify_player::client::handlers: Failed to handle client request: http error: status code 502 Bad Gateway`

**Environment**

- OS: Arch Linux
- Application version: 0.19.1
- Application features: cargo build --release --no-default-features --features pulseaudio-backend,streaming,lyric-finder,media-control,notify,sixel,fzf

**Additional context**
This was working in the last version 0.18.2

**Comment by aome510** [comment]
Still works for me in the latest version.

This `50x` error is mainly because of internal errors with Spotify server, which should be resolved after a day or so

**Comment by japopich** [comment]
I will mark this as resolved, cheers!
