### ISSUE TITLE
When in openCommandHelp, difficult to get out

### ISSUE THREAD

**Issue by khalua** [aome510/spotify-player#505]
When pressing "?" a very helpful screen shows up, but then there is no easy way to get out or close that screen and go back to what you were previously doing.  If you are 3 levels deep into a browse session, for example, no easy way to get back except to go through the 3 steps to get to it again.

Why not treat "?" it like a pop up and have the ESC key take you back to where you previously were? 

Or maybe pressing "?" again toggles the help commands on and off.

**Comment by aome510** [comment]
`CommandHelp` used to be popup. It was changed to a page to allow searching in the page. Search creates another popup and `spotify_player` supports only one active popup. You can press `backspace` to exit the command help page.

**Comment by khalua** [comment]
ahh backspace! perfect. TY. I think it would be helpful to add "close help" to the PreviousPage description... something like 
"go to previous page / close help" or in Commands title at top of window "Commands (backspace to exit)"
