### ISSUE TITLE
Add foreign language support for lyrics

### ISSUE THREAD

**Issue by smlocke** [aome510/spotify-player#509]
For `lyric-finder`, how do we feel about adding support for non-Western characters when displaying lyrics? 

Current state: Hangul characters don't render on lyrics page.
Environment: Windows 10 laptop running spotify_player.exe via command line and via PowerShell
![image](https://github.com/user-attachments/assets/1691a9f8-0f3b-498a-9084-507e87a7a01b)

**Comment by aome510** [comment]
ayo, no way I'm listening to the same album when replying to this issue 😮 . Anyway, Hangul works well for me:

<img width="1425" alt="image" src="https://github.com/user-attachments/assets/1878a706-668e-4b37-bfac-ab4a9b1d8121">

How the characters are rendered does not depend on the application itself but your terminal's font

**Comment by smlocke** [comment]
Bro's got taste! Thank you for responding, I'll have to go poke at my font.

I can file a separate issue for this, but I wanted you to consider a related matter: `stan Dreamcatcher, stream Justice`
