### ISSUE TITLE
Autoscroll Lyrics

### ISSUE THREAD

**Issue by felifluid** [aome510/spotify-player#513]
#### Feature
Add auto scrolling to the lyrics, so it always shows and highlights the current line.
Extending on this idea it could only show the current, previous and next line.

#### Disclaimer
I'm not sure if this is even possible, or if it would even be worth the hustle.

**Comment by xdBronch** [comment]
until something like this happens, could search be added to the lyrics page? it seems to be the only place where search doesnt work. i assume because its more of a filter than a search in the rest of the program?
