### ISSUE TITLE
Add better lyrics support with synced lyrics using librespot.

### ISSUE THREAD

**Issue by abdul2801** [aome510/spotify-player#521]
**Is your feature already implemented in the latest `master`?**
Partially implemented.
**Is your feature request related to a problem? Please describe.**
Currently the lyrics support uses an external api which is unreliable and dosent support synced lyrics.

**Describe the solution you'd like**
The github master and dev version of librespot supports getting lyrics from spotify with the synced timestamp.Will need to update librespot libraries to newer version , fix breaking changes and implement the lyrics.

**Additional context**
I am interested in working on this if it aligns with the project's needs.

**Comment by aome510** [comment]
I would prefer waiting `librespot` to release a new version than integrating the latest, unstable dev version.

Related: https://github.com/aome510/spotify-player/issues/513

**Comment by JingYenLoh** [comment]
Now that spotify-player is using librespot 0.6 which seems to have lyrics support, what changes are necessary to support this? I skimmed through the documentation and it seems like one can retrieve lyrics using a [SpotifyId](https://docs.rs/librespot-metadata/0.6.0/librespot_metadata/lyrics/struct.Lyrics.html#method.get), but I'm not sure how to retrieve the ID. Can it be extracted via the currently playing item?
