### ISSUE TITLE
Remap / rebind keymap to action

### ISSUE THREAD

**Issue by arouene** [aome510/spotify-player#523]
**Describe the bug**
It does not seem possible to remap a kemap (like C-p which is bind to "SelectPreviousOrScrollUp") to an action (like "AddToPlaylist").

**To Reproduce**
I have this **keymap.toml**

```
[[keymaps]]
command = "SelectPreviousOrScrollUp"
key_sequence = "k"

[[actions]]
action = "AddToPlaylist"
key_sequence = "C-p"
```

**Expected behaviour**
SelectPreviousOrScrollUp is k
AddToPlaylist is C-p

**Environment**

- OS: Linux Fedora 40
- Application version: 0.19.1

**Comment by arouene** [comment]
Besides, why do we make a difference between a keymap and an action?

**Comment by aome510** [comment]
> Besides, why do we make a difference between a keymap and an action?

I think you mean `command` and `action`. The difference is that `action` performs on a specific item (input) while `command` is supposed to be a general operation w/o input.

**Comment by arouene** [comment]
Oh ok, I see, thank you !

**Comment by aome510** [comment]
You can bind `C-p` for an action by binding `C-p` to `command = "None"` to allow re-use the binding.

**Comment by arouene** [comment]
I did try that, but C-p is just not bind to anything

```
[[keymaps]]
command = "SelectPreviousOrScrollUp"
key_sequence = "k"

[[keymaps]]
command = "None"
key_sequence = "C-p"

[[actions]]
action = "AddToPlaylist"
key_sequence = "C-p"
```

**Comment by aome510** [comment]
I see, then it's bug that doesn't allow to re-use `None` command. It should be easy to update https://github.com/aome510/spotify-player/blob/58a5ace777293ed04fb0da44075a27d777822501/spotify_player/src/config/keymap.rs#L416 to ignore `None` command.

**Comment by arouene** [comment]
Fixed in PR
