### ISSUE TITLE
Daemon mode: Is there a way to quit daemon mode ?  More documentaion is needed

### ISSUE THREAD

**Issue by armfem** [aome510/spotify-player#527]
**Is your feature already implemented in the latest `master`?**
I've been using `spotify-player` for a while. Lately, I started using daemon mode, which works as a charm, thanks for the implementation. Nevertheless I have some questions which are not given in the README file, I tried to read the code but quite note fluent in rust; therefore choose rather to open a Issue.

**Is your feature request related to a problem? Please describe.**
The problem is global for daemon usage. I will like to know how to stop the daemon (I do not know if several daemons can be started?), where the logs of the application can be found, and usual daemon administration stuff. If I'm pointed to the information maybe I could help write the documentation for :)

**Describe the solution you'd like**
The ideal solution will be to have all this documented on the README file.

Great project, so practical and nice :1st_place_medal:

**Comment by aome510** [comment]
`spotify_player` doesn't provide a way to stop a running daemon. The more correct way would be you kill the process yourself with `kill` or other related commands as an app instance should be self-contained without any knowledge about running instances.

**Comment by armfem** [comment]
Ok, I added an aliase in case you want to add it to the documentation to close it easily 

`alias spot_kill='kill $(pidof spotify_player)'`

Thanks for the answer :)
