### ISSUE TITLE
Config volume at 55% shows 54% in UI

### ISSUE THREAD

**Issue by Column01** [aome510/spotify-player#530]
**Describe the bug**
When I set my config's volume to `55` which is comfortable for me, the app launches at 54% volume. I thought "oh well maybe it's offset for some reason" so I set it to 56 in the config, and the app launches with 56% volume... very odd indeed.

**To Reproduce**

- Set config volume to 55
- launch app
- volume is 54%

**Expected behaviour**

- Volume should be 55% in the app

**Log and backtrace**

[spotify-player-24-07-31-17-58.zip](https://github.com/user-attachments/files/16447557/spotify-player-24-07-31-17-58.zip)

**Screenshots**

![powershell_mZOMlTIhZb](https://github.com/user-attachments/assets/c0b3ba50-b263-4e8a-9b0f-441dd202d335)

**Environment**

- OS: Windows 10
- Application version: git latest (built from source at [this commit](https://github.com/aome510/spotify-player/commit/fdb846e86e040b7d6ea45b0f578dd1ce7abd0008))
- Application features: `image,lyric-finder,media-control` built with `--release` on

**Additional context**

**Comment by aome510** [comment]
Likely because how `volume` is set in https://github.com/aome510/spotify-player/blob/fdb846e86e040b7d6ea45b0f578dd1ce7abd0008/spotify_player/src/streaming.rs#L171. It might be easy to tweak the calculation so that the percentage is right

**Comment by Column01** [comment]
I don't think it can be fixed due to librespot's volume needing to be a u16 number like that. It's a rounding error as `65535 * 0.55` is not a whole number

**Comment by Column01** [comment]
One way that could "fix" it is to display the volume percentage in the UI as whatever its set in the config lol

**Comment by aome510** [comment]
> I don't think it can be fixed due to librespot's volume needing to be a u16 number like that. It's a rounding error as `65535 * 0.55` is not a whole number

right.

> One way that could "fix" it is to display the volume percentage in the UI as whatever its set in the config lol

The volume is what received from Spotify API, so it cannot be changed based on the configs

**Comment by Column01** [comment]
> The displayed volume is what received from Spotify API, so it cannot be changed based on the configs

Ah yes, I assume this would be a problem if you used the app to adjust the volume for other applications and of course as the user changes the volume using the hotkey it wouldn't update the config's value accordingly and this would still show 55%, bummer! Not sure what to do about this then other than suck it up :P

**Comment by Column01** [comment]
Actually, on this line in the client the volume is an i8, I think whats happening here is the UI is displaying this value AFAIK and instead of rounding (`36044/65535 = 0.5499961852445259` rounded up would be 55%), it's chopping the decimals off making it "floor" the value and display 54% (again as far as I can tell)

https://github.com/aome510/spotify-player/blob/314631f9ce74e6449c929ca94d8e0ca553dd97c1/spotify_player/src/cli/client.rs#L404

**Comment by Column01** [comment]
But I don't fully understand the `is_offset` check so idk what that code block does if its not offset or what constitutes that flag being set

**Comment by Column01** [comment]
Further digging revealed what you said is true (not that I doubted it, just wanted to know more). Rspotify returns the `volume_percentage` which is a u32 meaning our decimals are lost somewhere outside our control :(

Gonna close this as afaik there is nothing that can be done to fix this
