### ISSUE TITLE
Synced lyrics support

### ISSUE THREAD

**Issue by 71zenith** [aome510/spotify-player#536]
**Is your feature already implemented in the latest `master`?**
No

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Lyrics that would sync with track
I've found this [sptlrx](https://github.com/raitonoberu/sptlrx) which provides a tui with synced lyrics and with my limited testing has more lyrics availability. They use an api to fetch the lyrics and feel like this can be reasonably ported over

It works with mpris, so it can be run externally

**Describe alternatives you've considered**
None

**Additional context**

**Comment by NickTheWilder** [comment]
Related: #521 #513
