### ISSUE TITLE
Secret Management for the spotify connect token

### ISSUE THREAD

**Issue by Mcrtin** [aome510/spotify-player#543]
**Is your feature already implemented in the latest `master`?**
I don't think so, but please show me otherwise.

**Is your feature request related to a problem? Please describe.**
I'm using Spotify-player with home-manager for a declarative config. However, I don't want to leak my secrets in my config, because the get evaluated and put into the world-readable nix store.

**Describe the solution you'd like**
Add a 'token command' field like spotifyd's 'password_cmd' or neomutt's 'account_command' (https://neomutt.org/feature/account-cmd)

**Describe alternatives you've considered**
Not putting the key in the upstream repo.

**Additional context**
I'm using nixos + home-manager + sops-nix

**Comment by aome510** [comment]
For secret, do you mean `client_id`? Should be addressed by https://github.com/aome510/spotify-player/pull/548
