### ISSUE TITLE
The Spotify generated Daily Mix playlists don't update

### ISSUE THREAD

**Issue by achmed13** [aome510/spotify-player#544]
**Describe the bug**
The Daily Mix playlists do not update. They have been the same for weeks.

**To Reproduce**
View the Daily Mix 1 playlist. Wait a day or two and view it again. The track list doesn't update.

**Expected behaviour**
The Daily Mix playlists should update daily.

**Environment**
Windows 11
Spotify Player 0.19.1

**Comment by aome510** [comment]
Mine does update daily. Did you confirm that it matches the songs on the office app? Maybe also restart the app to clear the cache to make sure.

**Comment by achmed13** [comment]
Thanks for the quick response. It does match the desktop Spotify player, so I’ll watch for a few more days and see if it is actually changing in either app.

**Comment by aome510** [comment]
Will close this issue for now. Feel free to re-open it if you don't think the daily is updated
