### ISSUE TITLE
Not able to install spotify-player with image or sixel feature

### ISSUE THREAD

**Issue by ManiArasteh** [aome510/spotify-player#550]
Howdy, again. I'm not able to install spotify-player with image/sixel feature. 
My operating system: Microsoft Windows 11 23H2 10.0.22631.4037
Cargo throws error:
`'image' feature has no binary. 'cargo install' is only for installing programs. `
Something like this.

**Comment by aome510** [comment]
What command did you use to install?

**Comment by ManiArasteh** [comment]
Wait a minute. I think I ran incorrect command

**Comment by ManiArasteh** [comment]
Aha. I ran incorrect command. Let me close it.
