### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by xArcGit** [aome510/spotify-player#555]
**Describe the bug**
Username: <user>
Password for <user>: 
Failed to authenticate, 2 tries left

**Expected behaviour**
I am unable to login in spotify-player try three time same problem

**Log and backtrace**
INFO spotify_player::auth: Creating a new session with new authentication credentials
WARN spotify_player::auth: Failed to authenticate: Login failed with reason: Bad credentials

**Environment**

- OS: Arch
- Application version: 0.19.1

**Additional context**
I can login in Spotify web

**Comment by LarssonMartin1998** [comment]
I also have this exact issue on MacOS and on my Arch machine. I read somewhere that Spotify had changed their API so something is outdated but I am not too readup on he issue.

**Comment by ManiArasteh** [comment]
Read README.md, please.
