### ISSUE TITLE
Moving Tracks Up an Down a Playlist

### ISSUE THREAD

**Issue by tsuliwaensis** [aome510/spotify-player#558]
What is the command to move a track up and down a playlist? The readme says it's `C-k`, but I don't know what the `C` represents. I've tried upper case C, lowercase c, Command-C, Control-C. I feel like an idiot.

**Comment by aome510** [comment]
`C-k` is `Control-k`

**Comment by tsuliwaensis** [comment]
That doesn't work for me. All the other commands work, but anything that invovles Control does not. I'm using the built-in Mac terminal (zsh) and a wireless keyboard.

**Comment by aome510** [comment]
I guess it depends on your terminal's settings, which may ignore the `control` key. `control` works fine for me on MacOS using `Iterm2` terminal

**Comment by tsuliwaensis** [comment]
I was trying to reorder my Liked Songs, which you can't manually reorder. I don't have an issue moving tracks around with my created playlists.
