### ISSUE TITLE
Blurred Thumbnail

### ISSUE THREAD

**Issue by Yuki638** [aome510/spotify-player#563]
Thumbnail blurred for some reason 
![screenshot_15092024_203331](https://github.com/user-attachments/assets/753e77b0-0ef4-40f9-a944-cb485fe1f3a6)

**Comment by aome510** [comment]
Most likely because your terminal doesn't support rendering images at full resolution. Please refer to https://github.com/aome510/spotify-player?tab=readme-ov-file#image for more details
