### ISSUE TITLE
Device selection not showing any devices

### ISSUE THREAD

**Issue by Duck-s** [aome510/spotify-player#566]
**Devices remains blank on the terminal**
When pressing **D** the devices tab opens but there is nothing inside and nothing to select pressing enter does nothing
i can go to the spotify app on my phone and manually change it to spotify_player and that works but i can not change it from within the app

**Screenshots**
![image](https://github.com/user-attachments/assets/faa1bde5-2e2e-4840-a0e6-2ed1582467df)

**Environment**

- OS: Arch (KDE)
- Application version: 0.19.1
- Application features: cargo install spotify_player --no-default-features --features pulseaudio-backend,streaming,media-control --locked

**Apologies in advance im new**
Sorry im new to the linux and github world and am unfamiliar with a lot
I will probably need precise instructions if you need anything (file or command output) but i am happy to give anything required though it may need patience as i will probably need help getting it.

**Comment by apprehensions** [comment]
> When spotify_player runs with your own client_id, press D (default shortcut for SwitchDevice command) to get the list of available devices, then press enter (default shortcut for ChooseSelected command) to connect to the selected device.

I think a warning should be added to indicate this within the tui.

**Comment by aome510** [comment]
> > When spotify_player runs with your own client_id, press D (default shortcut for SwitchDevice command) to get the list of available devices, then press enter (default shortcut for ChooseSelected command) to connect to the selected device.
> 
> I think a warning should be added to indicate this within the tui.

there is a similar warning in the log. Agree that it's helpful to have the message in TUI because I saw people open similar issues before. The difficult part is where to display the message

**Comment by aome510** [comment]
> Its all set up with my client id and such so that I can change the devices from the mobile app or browser to get audio but not from within the app.

Does that mean you already followed what described in https://github.com/aome510/spotify-player?tab=readme-ov-file#spotify-connect? Can you provide a log in `~/.cache/spotify_player/`?

**Comment by Duck-s** [comment]
I have the cache credentials.json saved yes and it logs me in perfectly fine it's just devices that won't load anything. I can see what device is currently playing from up by the music at the top but have no ability to change it within the D menu.

**Comment by aome510** [comment]
`client_id` is not the cached credentials but the config value you set in `app.toml`. For example, https://github.com/aome510/spotify-player/blob/9c47701cd6adc45c2d61721ccbdfae54ba67a523/examples/app.toml#L2

If you don't set this value, a default value will be used and you will not be able to see any devices

**Comment by aome510** [comment]
@Duck-s do you still have problems with device selection? Otherwise, I will close this issue

**Comment by ai-zac** [comment]
as
