### ISSUE TITLE
customized font

### ISSUE THREAD

**Issue by elogikalaf** [aome510/spotify-player#575]
it would be cool to have the option to select a font for this TUI app. I don't want to change the font of the terminal as a whole.

an option in the configuration to select a font file to be used by this TUI app.

**Comment by w-lfchen** [comment]
i'm 90% sure that's not possible to implement.
are there any existing projects which feature such an option?

**Comment by elogikalaf** [comment]
oh 
I didn't realize that it's that hard. I naively assumed it's easy to implement. thanks for taking the time to answer me.
