### ISSUE TITLE
repeat track doesn't work

### ISSUE THREAD

**Issue by elogikalaf** [aome510/spotify-player#577]
I use ctrl + R to set the repeat mode to track, but when the song ends it just goes on to the next song.

**To Reproduce**
use ctrl + R to put repeat mode to track, wait for the song to end.

**Expected behaviour**
the current song should be repeated.

**Screenshots**
![image](https://github.com/user-attachments/assets/6fb3cd24-7c8d-4253-89a7-435d7f152760)

**Environment**

- OS: Fedora 40
- Application version: spotify_player 0.19.1

**Comment by aome510** [comment]
This is expected. Please use `ToggleFakeTrackRepeatMode` instead if you want to repeat a song. See https://github.com/aome510/spotify-player/issues/247. This is due to a restriction of third-party library that `spotify_player` cannot fix

**Comment by elogikalaf** [comment]
thanks this seems to work out.
may I ask why even include the repeat track mode? seems a bit misleading

**Comment by aome510** [comment]
This doesn't work only for the integrated client provided by `librespot` (relevant issue: https://github.com/librespot-org/librespot/issues/19). The repeat track mode works when you stream music from external source like official Spotify client

**Comment by RichardBray** [comment]
Is there a visual way to see if `ToggleFakeTrackRepeatMode` is turned on?
