### ISSUE TITLE
Cant open spotify_player in tmux

### ISSUE THREAD

**Issue by marbinkaraus** [aome510/spotify-player#586]
I cant open the spotify_player while beeing in a tmux session, is it possible to implement that?

**Comment by marbinkaraus** [comment]
Found the issue, it was in my tmux config.
set -g default-terminal 'screen-256color'

**Comment by krishna4040** [comment]
still unable to open spotify player in tmux session, it used to open earlier, it started coming lately, is there any fix to this?
