### ISSUE TITLE
0.20 release on scoop?

### ISSUE THREAD

**Issue by einarpersson** [aome510/spotify-player#587]
Hi! I saw that there was a new big update released (0.20.0), but when I try to update it via scoop it says that the latest version is installed (0.19.1).

Do you need to do something extra to make it available to scoop? Or is there just a delay?

**Comment by aome510** [comment]
Hi, we don't maintain external packages (scoop, AUR, etc) in this repo. Please contact the corresponding maintainer to ask for an upgrade

**Comment by NickTheWilder** [comment]
@aome510 who is the maintainer for scoop?
