### ISSUE TITLE
Allow configuring the ap_port

### ISSUE THREAD

**Issue by bartlibert** [aome510/spotify-player#59]
The proxy at my work is really strict on outgoing ports. I see from the librespot logs that most of the time, for authentication, the ap tries to connect to a server using port 4070 (e.g. ap-gew1.spotify.com:4070). This times out in the end, because the port is blocked.

I did a quick hack here:
https://github.com/aome510/spotify-player/blob/52908a4d13a5cb72503a9eafa536e9a47e6f9a60/spotify_player/src/auth.rs#L39

and here:
https://github.com/aome510/spotify-player/blob/52908a4d13a5cb72503a9eafa536e9a47e6f9a60/spotify_player/src/auth.rs#L82

To use a SessionConfig with ap_port Some(443) instead of the defaults, and now the app works.

Would it be possible to implement a possibility to configure this port in the config file?

Thanks!

**Comment by aome510** [comment]
Thanks for taking a look into this.

> Would it be possible to implement a possibility to configure this port in the config file?

That should be easy. Will create a patch by EOD.

**Comment by aome510** [comment]
@bartlibert created the patch [here](https://github.com/aome510/spotify-player/pull/60). Can you check out the branch and run the app locally to see if the patch works.

`ap_port` is configurable by adding a `app_port={port}` line in your `app.toml`.

**Comment by bartlibert** [comment]
I tested the port setting with this branch, and it works fine, thanks! I have no proxy available to test, so that part is untested, but I guess it's very similar, so it should work as well.
