### ISSUE TITLE
Build failing on arm in void linux

### ISSUE THREAD

**Issue by bougyman** [aome510/spotify-player#601]
**Describe the bug**

After updating to 0.20.0, arm (6 and 7) builds are now failing for the spotify-player package

**To Reproduce**

These builds are automated in void-linux github actions. To reproduce simply create a PR updating
the version to 0.20.0

https://github.com/void-linux/void-packages/actions/runs/11687808367/job/32546762512
https://github.com/void-linux/void-packages/actions/runs/11631015422/job/32391178874

**Expected behaviour**

The build to succeed

**Log and backtrace**

We don't get to this point, since the build is failing. Build output in the 2 jobs above

Please refer to [this URL](https://github.com/aome510/spotify-player?tab=readme-ov-file#logging) for more details.

**Screenshots**

**Environment**

- OS: void linux
- Application version: 0.20.0
- Application features: if applicable, provide [cargo features](https://doc.rust-lang.org/cargo/reference/features.html) used to build `spotify_player`

**Additional context**

**Comment by aome510** [comment]
Might be related to https://github.com/aome510/spotify-player/issues/596. Not sure how the build process works for void-linux but can you try to build with the latest `master`?

**Comment by rlees85** [comment]
Make sure LTO is disabled  for the build- however you do that in void linux.

**Comment by aome510** [comment]
Should be fixed with latest `master`
