### ISSUE TITLE
build failure on alpine linux

### ISSUE THREAD

**Issue by thoughtpatterns** [aome510/spotify-player#611]
**Describe the bug**
the cargo package fails to build on the `ring` subpackage.

**To Reproduce**
build [this apkbuild](https://moe.pastes.sh/APKBUILD), or run the following command, on alpine.
```sh
cargo install --git https://github.com/aome510/spotify-player --no-default-features --features 'fzf,lyric-finder,media-control,pulseaudio-backend,sixel,streaming'
```

**Expected behaviour**
The package should build. I imagine there's a way around this to get ring working on musl but was unable to find an applicable method when searching.

**[Build log](https://moe.pastes.sh/spotify-player-log)**

**Environment**

`Linux x230 6.6.61-0-lts #1-Alpine SMP PREEMPT_DYNAMIC 2024-11-14 19:34:11 x86_64 Linux`
`spotify_player 0.20.1`

Let me know if any other environment information could be helpful here. Thanks!

**Comment by aome510** [comment]
Should be fixed with latest `master`. See #598
