### ISSUE TITLE
Player not starting...

### ISSUE THREAD

**Issue by gand0rf** [aome510/spotify-player#615]
So, long story short. Upgraded system, moved files over to nvme, and have been working on getting things set back up. Got spotify_player working again a couple of days ago. Get a message from Spotify this morning that they noticed "sus" activity and changed my password for me. Got my password updated. Now spotify player will not start even after re-registering with my account.

Error:
```
Error: initialize new Spotify session

Caused by:
    0: new streaming connection
    1: initialize spirc
    2: Permission denied { Login failed with reason: Bad credentials }
```

I have been working on trying to figure this out. going so far as to create a new app on spotify to get a new client ID. 
I also tried using the ID form the docs, but nothing. Looked around for a bit but didn't find anything that helped.

OS: Xubuntu 24.04
Version: 0.20.1

**Comment by aome510** [comment]
try to re-authenticate the application with `spotify_player authenticate` or delete the cached `credentials.json` in `~/.cache/spotify_player` then re-run the app

**Comment by evolutionxbox** [comment]
I've done this and I still see there error. I also do not have a `~/.cache/spotify_player` folder.

**Comment by gand0rf** [comment]
@aome510 Just wanted to touch base. I haven't had a chance to try this out myself. Been traveling for work this week. But I installed player in my worklaptops wsl term, and it loads just fine. Except for there is no spotify deamom for it to connect to, but I was just testing the launching and connecting it to my account. Should get back home tonight to see if this works for me.

**Comment by gand0rf** [comment]
@aome510 That fixed it!! Thank you. Done on my end. Not sure if you want to leave this open for evolutionxobx's issue or not.

**Comment by aome510** [comment]
I think it might be something unrelated. Will close this for now

**Comment by evolutionxbox** [comment]
@aome510 I'll create a new ticket if I can, because no matter how many times I run `spotify_player authenticate` (and follow the link) no `credentials.json` is created.
