### ISSUE TITLE
Allow changing step for volume up/down

### ISSUE THREAD

**Issue by repparw** [aome510/spotify-player#616]
Allow to set a different step for volumeup/down keymaps instead of always using 5.

Maybe a config option, or an optional argument after the command (volumeup 2 instead of volumeup)

**Comment by DOD-101** [comment]
If we change this into being an adjustable amount, would it not also make sense to have just one command (e.g. `VolumeChange`) to adjust the volume up or down. Then you could simply pass a positive or negative value. 

This would also then similar to the CLI option to change the volume. Thoughts @aome510

**Comment by aome510** [comment]
> If we change this into being an adjustable amount, would it not also make sense to have just one command (e.g. `VolumeChange`) to adjust the volume up or down. Then you could simply pass a positive or negative value.
> 
> This would also then similar to the CLI option to change the volume. Thoughts @aome510?

sounds good

**Comment by repparw** [comment]
Sorry just checking this, but this makes it have a different format from all other commands.

Maybe make offset implicit. e.g "VolumeChange -2"

This also affects nix/home-manager configs... can't pass {{}} to command when the module expects strings.

`  programs.spotify-player = {
    enable = true;
    keymaps = [
      {
        command = { VolumeChange = { offset = 2 } };
        key_sequence = "0";
      }
      {
        command = { VolumeChange = { offset = -2 } };
        key_sequence = "9";
      }
      {
        command = "Mute";
        key_sequence = "m";
      }
      {
        command = "NextTrack";
        key_sequence = "n";
      }
      {
        command = "PreviousTrack";
        key_sequence = "b";
      }
      {
        command = "PreviousTrack";
        key_sequence = "p";
      }
      {
        command = "PreviousPage";
        key_sequence = "q";
      }
      {
        command = "FocusNextWindow";
        key_sequence = "l";
      }
      {
        command = "FocusPreviousWindow";
        key_sequence = "h";
      }
      {
        command = "Quit";
        key_sequence = "C-q";
      }
      {
        command = "LibraryPage";
        key_sequence = "g h";
      }
      {
        command = "LyricPage";
        key_sequence = "g l";
      }
    ];
    actions = [
      {
        action = "CopyLink";
        key_sequence = "y";
        target = "PlayingTrack";
      }
      {
        action = "CopyLink";
        key_sequence = "Y";
      }
      {
        action = "GoToArtist";
        key_sequence = "g A";
        target = "PlayingTrack";
      }
      {
        action = "GoToAlbum";
        key_sequence = "g B";
        target = "PlayingTrack";
      }
      {
        action = "ToggleLiked";
        key_sequence = "C-l";
        target = "PlayingTrack";
      }
    ];
`

**Comment by DOD-101** [comment]
> Sorry just checking this

No worries mate. 

I just checked and this does work with home manager: 

```nix
        {
          command = {
            VolumeChange = {
              offset = 2;
            };
          };
          key_sequence = "0";
        }
```

The TOML output looks a bit different but works the same. 

Do keep in mind that this hasn't yet made it into a release, meaning if you want to use this currently, you will need to build from source.
