### ISSUE TITLE
SearchPage functionality broken

### ISSUE THREAD

**Issue by DefacedFace** [aome510/spotify-player#630]
Attempting to make a search for a song or album on the SearchPage currently does not work for me. 

MacOs Sonoma

**Comment by aome510** [comment]
Please include all necessary information as indicated in the issue template. Can you ensure that you're using the latest version of the app `0.20.3`?

**Comment by DefacedFace** [comment]
Whoops didn't realize there was an update. fixed.

**Comment by mr-majkel** [comment]
Hi @aome510, I'm on 0.20.3 (wsl linux), but I'm still experiencing the issue with search if I use my custom client id in the config. The default spotify client id works (i.e. commenting out the `client_id` from `app.toml` file), but I somehow experience more stopped playbacks this way (didn't look into the reasons yet into the log). If understood the changes in #618 the search should be handled by the default client id, right?

This is the example error message captured by spotify_player in the log when doing the search with the custom `client_id`:

```
ERROR client_request{request=Search("star wars")}: spotify_player::client::handlers: Failed to handle client request: json parse error: invalid type: null, expected struct SimplifiedPlaylist at line 1 column 1412: invalid type: null, expected struct SimplifiedPlaylist at line 1 column 1412
```
