### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by DoomDoggo64** [aome510/spotify-player#633]
Im unable to authenticate/ login
im able to login on spotify-tui 

- OS: arch
- Application version:0.19.1
- Application features: full pipe

**Additional context**

**Comment by Gustav2137** [comment]
See: https://aur.archlinux.org/packages/spotify-player-full-pipe
Seems like the package is not maintained.
https://aur.archlinux.org/packages/spotify-player should work, as I was updated 9 days ago.

**Comment by DoomDoggo64** [comment]
Thank you so much for the help will close the post
