### ISSUE TITLE
lyric_finder fork

### ISSUE THREAD

**Issue by cycle-five** [aome510/spotify-player#639]
Per the the comment on this PR https://github.com/aome510/spotify-player/pull/632#issuecomment-2543378887 I have forked lyric_finder on it's own here https://github.com/cycle-five/lyric-finder

**Comment by aome510** [comment]
Thank you!

**Comment by cycle-five** [comment]
Can you transfer ownership of the crates.io to me there? https://crates.io/users/cycle-five

**Comment by aome510** [comment]
> https://crates.io/users/cycle-five

Sent you an owner invitation
