### ISSUE TITLE
Play/Pause icon 

### ISSUE THREAD

**Issue by Selmer443** [aome510/spotify-player#67]
I noticed recently spotify-player switched to this icon for me? Im not sure if im able to configure an option to switch the icon or not, just noticed it one day. I'll keep digging to see if I can change it but figured I'd ask to see if theres an easy fix.
![29-07-2022-21-08-34](https://user-images.githubusercontent.com/93581805/181871825-036d50c7-d78b-4e51-a955-441541f24e61.png)

**Comment by aome510** [comment]
Unfortunately, it’s not configurable atm. I can add a quick change to allow configure play/pause icons

**Comment by aome510** [comment]
Unfortunately, it’s not configurable atm. I can add a quick change to allow configure play/pause icons

**Comment by aome510** [comment]
Should be fixed by #68. Can you try the latest build of `master` and confirm that the icons are configurable by changing the [app.toml](https://github.com/aome510/spotify-player/blob/master/examples/app.toml) file?

**Comment by Selmer443** [comment]
yeah, im a bit unsure how to use #68 specifically. Is there a way to use it through the aur?

**Comment by aome510** [comment]
Hi @Selmer443, do you happen to have [Rust+Cargo](https://www.rust-lang.org/tools/install) installed in your system? If yes, you can test the latest build on `main` by building one:

1. Create a `.config/spotify-player/app.toml` config file and configure the play/pause icons:
```toml
play_icon = "="
pause_icon = ">"
```
2. Clone this repo and run a local build
```
git clone https://github.com/aome510/spotify-player.git && cd spotify-player
cargo run
```
3. Observe that the play/pause icons are changed compared to the default values

>  Is there a way to use it through the aur?

Right now, `aur` only supports the latest release not the latest development change. Either you need to wait for the new release or add a new `spotify-player-nightly` package. I don't have access to Arch laptop, so I cannot help on this

**Comment by Selmer443** [comment]
works perfectly for me, just curious if I wanted to have easy access to running spotify-player like I was with the aur package making the command "spotify-player" available globally. Would I run a separate cargo command ? or will I have to navigate to the spotify-player folder each time i'd like to start the program.

**Comment by aome510** [comment]
> --Just to clarify, the icons are entirely configurable now and I have tested it with multiple icons.

Great to hear that.

>  just curious if I wanted to have easy access to running spotify-player like I was with the aur package making the command "spotify-player" available globally

`cargo run` should produce a binary in `target/debug/spotify_player`. You can link that binary to a folder in your path, e.g 
```
ln -s $PWD/target/debug/spotify_player /usr/local/bin/
```

Note that `cargo run` is a debug run/build, so if you want your app to run fast, you can build a `release` version. Same steps can be used here

```
cargo build --release
ln -s $PWD/target/release/spotify_player /usr/local/bin/
```

**Comment by Selmer443** [comment]
thanks so much! sorry it took me a bit to get back to you. Only been using linux for a bit now but your comments are super helpful, ill make sure to read up more on linking things and use your method for now.
