### ISSUE TITLE
spotify_player fails to play any track, Spotify changes?

### ISSUE THREAD

**Issue by 0323pin** [aome510/spotify-player#69]
@aome510 

The player jumps through songs and when reaching the end of the list it starts over again. Killing the app is the only way out of this loop.

Attached the log file, although it generates several of these one after the other.

Backtraces are empty :(

ClientID has been hidden on the log file.

If you need to check my configurations see, https://codeberg.org/pin/leftwm-netbsd/src/branch/main/.config/spotify-player

[spotify-player-22-08-04-09:32.log](https://github.com/aome510/spotify-player/files/9257647/spotify-player-22-08-04-09.32.log)

**EDIT:** Downgraded to 0.9.3 and the bug is already present there. I've been on holiday and just pushed the updates.
Downgraded to 0.9.2 and it's the same, then downgraded to 0.9.0 and the same happens.

I'm lost, I start to think that something else is causing this. I've also built 0.8.0 just to be sure, as I know this one worked before and it does the same :(
I've no clue how to fix this or what is causing it.

**Comment by 0323pin** [comment]
@aome510 just got confirmed that `ncspot` is behaving the same for a fellow NetBSD developer, that claims it was working yesterday but, not today. So, not an issue with `spotify-player`.
Are you aware of any changes at the Spotify end? Are you having any issues yourself?
I've merged the latest `librespot`, should that dependency be updated?

A lot of questions, I know.

**Comment by aome510** [comment]
> Are you aware of any changes at the Spotify end? Are you having any issues yourself?

I'm not. Just quickly tested with `0.9.3` on my local and still works. It also worked yesterday for me.

> I've merged the latest librespot, should that dependency be updated?

I don't know there is a new update for `librespot`. I can bump a new version.

My best guess is this is because of some Spotify client bug, so let's wait for a few days to see if the issue still persists.

**Comment by 0323pin** [comment]
@aome510 Thanks for checking at your end, really appreciated.
I've tried today and it's still the same, I'll give it a few days.

The reason I was mentioning `librespot` is the ChangeLog provided with the release of v0.4.2, quoting

> this point release is mainly to blacklist the ap-gew4 and ap-gue1 access points that caused librespot to fail to playback anything.

So, I thought this could be related. Anyway, `librespot` is preparing some major changes, I'd recommend to check it out, again quoting,

> Development will now shift to the new HTTP-based API, targeted for a future v0.5.0 release. The new-api branch will therefore be promoted to dev. This is a major departure from the old API and although it brings many exciting new things, it is also likely to introduce new bugs and some regressions.

Shall I close this issue? I'm convinced this is not an issue with `spotify-player`.

**Comment by aome510** [comment]
> The reason I was mentioning `librespot` is the ChangeLog provided with the release of v0.4.2, quoting
> 
> > this point release is mainly to blacklist the ap-gew4 and ap-gue1 access points that caused librespot to fail to playback anything.
> 
> So, I thought this could be related. Anyway, `librespot` is preparing some major changes, I'd recommend to check it out, again quoting,
> 
> > Development will now shift to the new HTTP-based API, targeted for a future v0.5.0 release. The new-api branch will therefore be promoted to dev. This is a major departure from the old API and although it brings many exciting new things, it is also likely to introduce new bugs and some regressions.

Ah, I see. Thanks for the information.

> Shall I close this issue? I'm convinced this is not an issue with `spotify-player`.

Let's close if for now. Will open again if I find any issues related to `spotify-player`

**Comment by 0323pin** [comment]
@aome510 Found the issue. It has been in front of my eyes all the time. From `ncspot`release notes

> Update to librespot 0.4.2
Should fix ChannelError issues (ncspot skipping through all tracks) which were previously fixed with a workaround in /etc/hosts (https://github.com/hrkfdn/ncspot/issues/864

See the referenced issue and https://github.com/librespot-org/librespot/issues/972 on `librespot`.

Locally adding `104.199.65.124  ap-gew4.spotify.com` to `/etc/hosts` fixes the issue.
Anyway, updating to `librespot`-0.4.2 is the right solution.

Regards,
pin

**Comment by aome510** [comment]
> @aome510 Found the issue. It has been in front of my eyes all the time. From `ncspot`release notes
> 
> > Update to librespot 0.4.2
> > Should fix ChannelError issues (ncspot skipping through all tracks) which were previously fixed with a workaround in /etc/hosts ([hrkfdn/ncspot#864](https://github.com/hrkfdn/ncspot/issues/864)
> 
> See the referenced issue and [librespot-org/librespot#972](https://github.com/librespot-org/librespot/issues/972) on `librespot`.
> 
> Locally adding `104.199.65.124 ap-gew4.spotify.com` to `/etc/hosts` fixes the issue. Anyway, updating to `librespot`-0.4.2 is the right solution.
> 
> Regards, pin

@0323pin Thanks for the context. Great to know that it's now fixed. I'll release a new version soon with the deps upgrade

**Comment by 0323pin** [comment]
Thanks!
I've posted a brief note for NetBSD users, https://mail-index.netbsd.org/pkgsrc-users/2022/08/10/msg036056.html
I want to avoid complains, as I'm the maintainer of all the Spotify clients 😄

**Comment by aome510** [comment]
@0323pin release new version [`0.9.5`](https://github.com/aome510/spotify-player/releases/tag/v0.9.5) with the `librespot` upgrade. I also specify the latest build of `souvlaki` in [Cargo.toml](https://github.com/aome510/spotify-player/blob/v0.9.5/spotify_player/Cargo.toml#L40), so you can build the app with `media-control` feature. Please lmk if something doesn't work.

**Comment by 0323pin** [comment]
@aome510 Thanks! Unfortunately, pulling `souvlaki` from git is not such a good idea. Within pkgsrc distfiles should not be pulled from the internet at compile time and builds should be done in offline mode, so I hit the following error,

```
===> Building for spotify-player-0.9.5
error: failed to get `souvlaki` as a dependency of package `spotify_player v0.9.5 (/usr/pkgsrc/wip/spotify-player/work/spotify-player-0.9.5/spotify_player)`

Caused by:
  failed to load source for dependency `souvlaki`

Caused by:
  Unable to update https://github.com/Sinono3/souvlaki#b7020dfa

Caused by:
  can't checkout from 'https://github.com/Sinono3/souvlaki': you are in the offline mode (--offline)
*** Error code 101

Stop.
```

I can patch this but, have no time for it today.

**Comment by 0323pin** [comment]
@aome510 ok, just a few hours after and not tomorrow 😄 
I couldn't resist.

All good, no hacks in `/etc/hosts` needed anymore and I can listen to music again.
Thank you!
I'll merge this on the main repo before  sleeping tonight.

**Comment by 0323pin** [comment]
I know this maybe unrelated but, I didn't want to create a new issue.
Yesterday, I streamed music without an itch for over an hour.
Today, I mostly get `No playback found. Please make sure there is a running Spotify client and try to connect to it using the 'SwitchDevice' command.`

Sometimes it works but mostly it doesn't and I get that error.

[spotify-player-22-08-11-06:57.log](https://github.com/aome510/spotify-player/files/9306206/spotify-player-22-08-11-06.57.log)

**Comment by aome510** [comment]
> Today, I mostly get No playback found. Please make sure there is a running Spotify client and try to connect to it using the 'SwitchDevice' command.

Did you get that during startup or after using the app for a while?

I just look into the log, 

> 2022-08-11T04:57:48.168309Z  INFO spotify_player::streaming: Initializing a new integrated player with device_id=c5e6a5a2-69ac-40aa-9d52-d39810a5bab5
> ...
> 2022-08-11T04:57:48.328265Z  INFO spotify_player: No playing device found on startup, trying to connect to an available device
> 2022-08-11T04:57:48.389242Z  INFO spotify_player::client: Available devices: []
> 2022-08-11T04:57:48.389275Z  INFO spotify_player::client: No available device found, use the integrated device (id=c5e6a5a2-69ac-40aa-9d52-d39810a5bab5)
> 2022-08-11T04:57:48.455336Z ERROR Client_request{request=Player(TransferPlayback("c5e6a5a2-69ac-40aa-9d52-d39810a5bab5", false))}: spotify_player::client::handlers: Failed to handle client request: http error: status code 404 Not Found

it seems it failed to find a device to connect to on startup, which can be because of 
1. initializing the integrated device failed
2. initializing the integrated device succeeded but the device wasn't shown up in the device list when the `get_device` API is called

To confirm 1, did you get any backtrace errors?
To confirm 2, does it show any devices when you press `D` (`SwitchDevice` command)?

**Comment by 0323pin** [comment]
@aome510 Thanks! This happens at startup, as you already figured out.
I only use the integrated device, I've never used the app to control another running device. Yes, I do get backtraces but, they are empty.

Pressing `D` shows an empty list, as I only use the integrated device.
Could it be `librespot` failing to start?

**Comment by aome510** [comment]
> Could it be librespot failing to start?

I guess it could be the case. But, it's pretty weird there is no error backtrace.

> Pressing D shows an empty list, as I only use the integrated device.

Even if you only use the integrated device, press `D` should also show that device unless you don't specify your own `client_id` in the `app.toml`. In that case, `get_device` always return empty.

Does this issue happen every time you open the app? Also, does press `R` (`RestartIntegratedClient` command) work?

**Comment by 0323pin** [comment]
I've logged in on my working Windows machine on chrome, then launched the app on NetBSD and I can control the device.

> Does this issue happen every time you open the app?

No, sometimes it works as expected.

Logged off in Windows and re-launched the player. Got the same error but, got the device in the list when pressing `D`.
Killed and restarted the app 6 times and twice it worked as expected.

This is though to debug.

**Comment by 0323pin** [comment]
When failing it always generates a backtrace,

![2022-08-11-081404_1366x768_scrot](https://user-images.githubusercontent.com/90570748/184074698-53c63332-c5ea-4323-97d4-3e23a4205275.png)

But these are all empty.

**Comment by aome510** [comment]
> When failing it always generates a backtrace,

The app generates a backtrace file and a log file whenever it starts. Empty backtrace probably means no error.

Based on my experience, as I experienced a similar issue before [1]. This was more because,
> initializing the integrated device succeeded but the device wasn't shown up in the device list when the get_device API is called

The app starts by registering an integrated device then connecting to an available device. The connect process can fail if the newly registered device hasn't been notified to the Spotify server.

This can be fixed by either calling `SwitchDevice` (`D`) command to manually connect to one or `RestartIntegratedClient` (`R`) to restart the integrated device then connect to it.

[1] This issue used to happen more frequently for me before I made some changes to improve the register-connect progress. I'll take another look to see if I can fix this.

**Comment by 0323pin** [comment]
Thank you for the explanation.
It's running now, playing music while I work on some documents.
I'll try `D` and `R` when this happens again or, I'll just restarts until it works.

> [1] This issue used to happen more frequently for me before I made some changes to improve the register-connect progress. I'll take another look to see if I can fix this.

Awesome but, no rush, it does work.

**Comment by aome510** [comment]
> wrong place for this, I know ... just to let you know souvlaki has provided a new release, https://github.com/Sinono3/souvlaki/issues/25

Thanks for letting me know. Will update the app shortly

**Comment by 0323pin** [comment]
@aome510 Take your time. This week I'm rather busy with real life work. I'm still doing package updates but, don't have that much time to play with package build options, even though it's not that difficult :)
Better focus on it when doing, so I don't miss anything.
