### ISSUE TITLE
Dependency on Alsa libs but Rodio is default?

### ISSUE THREAD

**Issue by braheezy** [aome510/spotify-player#70]
Just curious why the `alsa` system library is needed when `rodio-backend` is the default audio choice? Thanks!

**Comment by aome510** [comment]
`rodio` uses [`cpal`](https://github.com/RustAudio/cpal) for playback control. `cpal` uses `alsa` to do audio I/O on Linux. That's the reason why `alsa` lib is needed, at least for Linux. `cpal` also supports `jack`, but rn for `spotify-player`, it's not configurable.

**Comment by braheezy** [comment]
Gotcha. Thanks for the info!
