### ISSUE TITLE
adding to shared playlist

### ISSUE THREAD

**Issue by a1fishie** [aome510/spotify-player#82]
I am part of a few shared playlists, by that I mean where the owner has enabled the "Collaborative Playlist" function, as seen below 
![image](https://user-images.githubusercontent.com/104651507/191013171-12b58a42-afd9-474b-8998-263a1866eb73.png)
I was wondering if there's a possibility to add songs to playlists like that in spotify-player

**Comment by aome510** [comment]
I think it's possible. Currently, the `AddToPlaylist` action only lists the playlists owned by user. 

For additional confirmation, are collaborative playlists listed in the **Playlists** tab of the **Library** page when you first open the app?

**Comment by a1fishie** [comment]
They are, however it also includes playlist i have hearted

**Comment by aome510** [comment]
@a1fishie created #83. I couldn't test it as I don't have any collaborative playlists. Can you checkout the branch and run the app to test the new changes?

**Comment by a1fishie** [comment]
Yeah, it seemingly works fine, thank you!
