### ISSUE TITLE
How to shuffle

### ISSUE THREAD

**Issue by arthurhawron** [aome510/spotify-player#85]
This is probably stupid, but when I press shuffle keybind (C-s), it opens up a shortcut menu and there is no shuffle option. Can someone please clarify the shortcut?

**Comment by aome510** [comment]
> when I press shuffle keybind (C-s), it opens up a shortcut menu and there is no shuffle option

which shortcut does it open? Is it similar to the one below?
<img width="794" alt="Screen Shot 2022-11-14 at 10 03 03 AM" src="https://user-images.githubusercontent.com/40011582/201693386-bbce0143-8539-4117-bbd1-dbeb1c2fd303.png">

If not, I guess `C-s` is probably the shortcut to open a shortcut menu for your terminal. You can bind `Shuffle` command to another key in your `.config/spotify-player/keymap.tom`. More details: https://github.com/aome510/spotify-player/blob/master/doc/config.md#keymaps

**Comment by arthurhawron** [comment]
I don't think it is a terminal shortcut menu, as it has details such as sorting by album and artist name. Here is an image
![file](https://user-images.githubusercontent.com/83101428/201886310-b59fe9de-8793-46de-af31-b20f128bb14b.png)

**Comment by arthurhawron** [comment]
So I changed the keymap.toml so that the shortcut for shuffle was "s h", and now it shows up in the shortcut menu:
![file](https://user-images.githubusercontent.com/83101428/201887212-73aabbe3-9fdc-4c9b-85f1-0d4d9ff679fb.png)

**Comment by aome510** [comment]
> I don't think it is a terminal shortcut menu, as it has details such as sorting by album and artist name. Here is an image

Oh I see. I think it's because the app or the terminal doesn't recognize the `control-s` combination and it is parsed as a `s` key. That's why the shortcut menu for commands with `s` key prefix is shown. One possible workaround is to change the shortcut like u already did. Hope that's not too much of a trouble.
