### ISSUE TITLE
what media control suppose to do?

### ISSUE THREAD

**Issue by diegoulloao** [aome510/spotify-player#86]
It's not clear what media control suppose to do, I have activated it in macos building the application with the media-control feature flag and adding enable_media_control set to true in the app.toml file inside .config.

It's not making anything... What is supposed to do?

By the way, excellent work, the best spotify tui I could find (I have tried a lot).

**Comment by aome510** [comment]
> By the way, excellent work, the best spotify tui I could find (I have tried a lot).

Thanks for the kind words 💪 

> It's not making anything... What is supposed to do?

It allows you to control the playback (next, prev, play, pause) using the media keys or macos's media control panel without interacting directly with the `spotify-player`. It should also work with bluetooth headphone/earphone's media controls. 

To confirm that the media control actually works with `spotify-player`, you can check the macos's media control panel (it should show the track `spotify-player` is currently playing):
<img width="323" alt="Screen Shot 2022-11-19 at 3 50 58 PM" src="https://user-images.githubusercontent.com/40011582/202871176-3bac418c-73dd-43db-8616-732c2f878cf4.png">

**Comment by diegoulloao** [comment]
For some reason it's not working. Should I restart my iterm2?
By the way, how I build the application passing multiple --features?

**Comment by aome510** [comment]
> For some reason it's not working. Should I restart my iterm2?

Not sure if `iterm2` is the problem here. Can you send me the latest application log (should be inside `.cache/spotify-player`)?

> By the way, how I build the application passing multiple --features?

You can do it by passing `--features` multiple times. For example, to build app with `image` and `lyric_finder` features enabled.

```
cargo [install|build] --features image --features lyric_finder
```

**Comment by diegoulloao** [comment]
I understand...

Now it's working, my mistake. I put it inside the device section.

Thanks for the help.

**Comment by aome510** [comment]
> Now it's working, my mistake. I put it inside the device section.

Great to hear that. I'll close this issue for now.
