### ISSUE TITLE
add to a new playlist / create a playlist?

### ISSUE THREAD

**Issue by diegoulloao** [aome510/spotify-player#87]
I was trying to add a song to a new playlist but I couldn't find the option. Also I think isn't possible to create a new playlist from the user playlist view.

Is there a way to do it?

Sorry for open 2 bugs in 1 day.

**Comment by aome510** [comment]
> Sorry for open 2 bugs in 1 day.

No problem lol.

> I was trying to add a song to a new playlist but I couldn't find the option. Also I think isn't possible to create a new playlist from the user playlist view.
> 
> Is there a way to do it?

Currently, iirc, `spotify-player` doesn't support creating a new playlist. It does support adding song to already existed playlist, which can be triggered by `ShowActionsOnSelectedItem` or `ShowActionsOnCurrentTrack` commands. You can then choose `AddToPlaylist` action from the popup list

**Comment by diegoulloao** [comment]
It would be nice to add support to it 😁

**Comment by aome510** [comment]
> It would be nice to add support to it

It should be easy to implement. However, I currently don't have much time as I'm quite busy with school. PRs are welcome though 💪

**Comment by diegoulloao** [comment]
I would like to but I don't know a word of Rust.

Interested in learning btw 👀
