### ISSUE TITLE
Repeat a single track

### ISSUE THREAD

**Issue by arch-btw** [aome510/spotify-player#88]
Hello :)

Thank you very much for this great project.

I was wondering if it's possible to repeat a single track? So far, I only found these 2 options:

1) Repeat context
2) Off

Thank you for your help!

**Comment by aome510** [comment]
Hi @arch-btw, hope u like `spotify-player`. It's not possible to repeat single track if u play music through the integrated player. This is [a well-known issue](https://github.com/librespot-org/librespot/issues/984) of `librespot`, which is the library I use to implement the integrated player. Note that u can still repeat a single track if u play another client and use `spotify-player` like a remote player, like the official Spotify one.

**Comment by aome510** [comment]
Close this issue for now as it's related to a third-party library and cannot be fixed within `spotify_player`.

**Comment by Foxtrod89** [comment]
> 

What you saying is _librespot_  doesn't support basic functionality like repeat/shuffle. It seems like bells and whistles overweight common sense... Oddly but yes!

**Comment by aome510** [comment]
librespot does support repeat/shuffle. The only thing it doesn't support is **repeating a single track**, for example in an album or playlist.

Related: https://github.com/librespot-org/librespot/issues/19
