### ISSUE TITLE
[Feature request] Artist / album / track radio

### ISSUE THREAD

**Issue by tobiasrenkin** [aome510/spotify-player#90]
Hi,

really love the client. However, I really miss the ability to play artist / album / track radios. To me these are really one of the top spotify features, and it would be nice if these could be added.

Thanks!

**Comment by aome510** [comment]
Hi @tobiasrenkin, great to hear that you like `spotify-player`. The app does support play artist / album / track radios. You can do this by select an artist / album / track item, trigger `ShowActionsOnSelectedItem` (bind to `g a` by default) then select `BrowseRecommendations` action. A radio page is then generated using [get-recommendations API](https://developer.spotify.com/console/get-recommendations/).

This radio page is kinda different from what you have in the official app in a way that it's a radio playlist with finite songs (50 max) while the official one is an "infinite" list.

**Comment by tobiasrenkin** [comment]
OK thanks that works!

Still, it would be great to have a better way to play an Album or Artist radio. Most of the time I am in the context view, for example for an Album. What you suggest gives recommendations based on a song, not on an album or an artist. To get that, I need to go back to the search page, search for the Album or Artist that is already playing and then trigger the action on that result.

**Comment by aome510** [comment]
> Still, it would be great to have a better way to play an album or artist radio. Most of the time I am in the context view, for example for an Album. What you suggest gives recommendations based on a song, not on an album or an artist. To get that, I need to go back to the search page, search for the Album or Artist that is already playing and then trigger the action on that result.

Yeah, you're absolutely right :). I realized that recently and will work on an improvement soon.

**Comment by aome510** [comment]
@tobiasrenkin implemented new features in https://github.com/aome510/spotify-player/pull/92. Either you can try the latest build of `master` branch or wait for new release, which should be coming soon.

Now, the app supports all track, album, artist, playlist radios like Spotify. In addition, `spotify-player` now uses different APIs that allow the recommended tracks shown up in the radio page similar to what of the official Spotify app.

I added several `GoTo...Radio` actions for each Spotify item type, so you won't need to go back to search page to trigger an action.

**Comment by aome510** [comment]
Should be fixed in https://github.com/aome510/spotify-player/releases/tag/v0.10.0. Feel free to reopen this issue if encounter any related issues.
