### ISSUE TITLE
 Explicit Albums on Artists Page

### ISSUE THREAD

**Issue by braheezy** [aome510/spotify-player#96]
Depending on the genre of music (like hip-hop), it's commonplace to release 2 versions of an album: an explicit version and an edited "radio" version. When using the Spotify desktop client, you'll see both albums under an Artist page and can pick the one you want. The Explicit songs are marked with an "E" icon.

With `spotify_player`, if I am viewing an Artist's page, I seem to only be shown the "radio" version. I noted I can do a **g**lobal **s**earch with the Album name to find both versions and play the explicit version there.

It would be convenient to access the explicit version from the Artists' Albums page too.

**Comment by aome510** [comment]
@braheezy can you provide an example of such artist with both explicit/edited "radio" albums? This can be helpful to implement the feature

**Comment by braheezy** [comment]
Yeah I think I got one here.

 Kendrick Lamar has the esteemed album "To Pimp A Butterfly". It's listed once here:
![Screenshot from 2023-01-18 12-10-57](https://user-images.githubusercontent.com/11700503/213284415-dbbab3fd-9125-4be1-a46b-3c597545b988.png)

About near the timestamp in the screenshot is where you can start to tell it's the clean version. 

---
Here's the result from the Global Search. One of those in the Albums view is the explicit version (maybe another feature? annotate the difference?).

![Screenshot from 2023-01-18 12-15-25](https://user-images.githubusercontent.com/11700503/213285443-5c2d146b-ad93-4675-8f0b-29cd88c85c3c.png)
