### ISSUE TITLE
terminal ansi colors

### ISSUE THREAD

**Issue by wael444** [aome510/spotify-player#97]
by default, it seems that spotify_player uses it's own colors. for a CLI/TUI application i don't think this is a very good idea. spotify_player should use the terminal's colors - aka ANSI colors.

**Comment by aome510** [comment]
By the app's own colors, I'll assume that you're referring to the required colors mentioned in [theme's palette documentation](https://github.com/aome510/spotify-player/blob/master/doc/config.md#palette). 

I believe defining the app's own colors this way allows to define more custom themes. I'm not too sure about the approaches other CLI/TUI applications take. Any resources would be helpful.

**Comment by wael444** [comment]
thats not exactly what i meant; for example a program can use the current terminals colors, for example heres a simple printf that will use ANSI to ask the terminal to print the text in red, and then reset the colors:
```sh
printf '\033[31mi am in red\n\033[0m'
```
i believe many programs do this; such as spotify-tui.

**Comment by aome510** [comment]
> thats not exactly what i meant; for example a program can use the current terminals colors,

Thanks for the clarification. Does that mean adding a new theme, e.g called "default", that uses the terminal's default colors should work?

**Comment by wael444** [comment]
i guess?

**Comment by wael444** [comment]
IMO there shouldnt be themes built in into spotify-player. the default and the only default should be ANSI colors and supports themes via configuration; with templates/themes from the project repo.

**Comment by euglevi** [comment]
I think this feature is a must in terms of theming. I change my terminal theme quite often, it looks like a downsize having to change the spotify-player theme too.

**Comment by aome510** [comment]
This issue should be resolved by #107. 

The default theme change can be considered as a breaking change, so there should a while till it's released with a new major version.

In the meantime, @wael444, @euglevi, can you guys test the latest build of the `master` branch to see if it works as expected? **Note** it requires to update the theme's configurations, so please refer to [themes documentation](https://github.com/aome510/spotify-player/blob/master/doc/config.md#themes) for references. Feel free to reopen this issue if encounter any related issues.

**Comment by wael444** [comment]
Yes. though the color of the green accent is a little too light, should be the default green color `2` instead of `10`

**Comment by aome510** [comment]
> Yes. though the color of the green accent is a little too light, should be the default green color `2` instead of `10`

Which component are you referring? I think it depends on the terminal's theme. The theme looks fine for mine:

<img width="1436" alt="Screen Shot 2023-01-17 at 2 01 15 PM" src="https://user-images.githubusercontent.com/40011582/212988040-97276dc1-be07-4a23-a0a0-1ad5eb68784f.png">

If things don't work, you can always create a new theme based on the "default" theme and update the corresponding component styles.

**Comment by wael444** [comment]
![image](https://user-images.githubusercontent.com/47404953/212989495-79730647-2e13-4d7f-9c90-bb166827353e.png)

**Comment by euglevi** [comment]
It seems to me it works well. Thank you! I have tried with a few themes. I will try more in the next days, but I have no reason to think I will experience any issues.
